# Generated by Django 5.0 on 2026-03-02 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0006_passwordresetcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationcode',
            name='username',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Логин'),
        ),
    ]
