# Generated by Django 5.0 on 2026-04-03 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0012_doctorreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='exam_summary',
            field=models.TextField(blank=True, default='', verbose_name='Итоги обследования'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='prescribed_medications',
            field=models.TextField(blank=True, default='', verbose_name='Назначенные препараты'),
        ),
    ]
