# Generated by Django 5.0 on 2026-01-28 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('type', models.CharField(choices=[('Поликлиника', 'Поликлиника'), ('Больница', 'Больница'), ('Детская', 'Детская'), ('Спец. клиника', 'Спец. клиника')], max_length=50, verbose_name='Тип')),
                ('address', models.CharField(max_length=300, verbose_name='Адрес')),
                ('waiting_time', models.IntegerField(default=10, verbose_name='Среднее ожидание (мин)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Больница',
                'verbose_name_plural': 'Больницы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(editable=False, max_length=6, unique=True, verbose_name='Код записи')),
                ('patient_name', models.CharField(max_length=200, verbose_name='Имя пациента')),
                ('specialty', models.CharField(choices=[('Терапевт', 'Терапевт'), ('Хирург', 'Хирург'), ('Стоматолог', 'Стоматолог'), ('Педиатр', 'Педиатр')], max_length=50, verbose_name='Специальность')),
                ('datetime', models.DateTimeField(verbose_name='Дата и время приёма')),
                ('queue_position', models.IntegerField(default=1, verbose_name='Место в очереди')),
                ('status', models.CharField(choices=[('confirmed', 'Подтверждена'), ('cancelled', 'Отменена'), ('completed', 'Завершена')], default='confirmed', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='appointments.hospital', verbose_name='Больница')),
            ],
            options={
                'verbose_name': 'Запись',
                'verbose_name_plural': 'Записи',
                'ordering': ['-created_at'],
            },
        ),
    ]
