# Generated by Django 5.0 on 2026-02-27 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_verificationcode_appointment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='specialty',
            field=models.CharField(choices=[('Терапевт', 'Терапевт'), ('Хирург', 'Хирург'), ('Стоматолог', 'Стоматолог'), ('Педиатр', 'Педиатр'), ('Кардиолог', 'Кардиолог'), ('Невролог', 'Невролог'), ('Офтальмолог', 'Офтальмолог'), ('Дерматолог', 'Дерматолог'), ('Эндокринолог', 'Эндокринолог'), ('Гинеколог', 'Гинеколог'), ('Уролог', 'Уролог'), ('Психиатр', 'Психиатр')], max_length=50, verbose_name='Специальность'),
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='ФИО врача')),
                ('specialty', models.CharField(choices=[('Терапевт', 'Терапевт'), ('Хирург', 'Хирург'), ('Стоматолог', 'Стоматолог'), ('Педиатр', 'Педиатр'), ('Кардиолог', 'Кардиолог'), ('Невролог', 'Невролог'), ('Офтальмолог', 'Офтальмолог'), ('Дерматолог', 'Дерматолог'), ('Эндокринолог', 'Эндокринолог'), ('Гинеколог', 'Гинеколог'), ('Уролог', 'Уролог'), ('Психиатр', 'Психиатр')], max_length=50, verbose_name='Специальность')),
                ('cabinet', models.CharField(blank=True, max_length=20, verbose_name='Кабинет')),
                ('work_days', models.CharField(default='Пн-Пт', max_length=100, verbose_name='Рабочие дни')),
                ('work_hours', models.CharField(default='08:00-18:00', max_length=50, verbose_name='Рабочие часы')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to='appointments.hospital', verbose_name='Больница')),
            ],
            options={
                'verbose_name': 'Врач',
                'verbose_name_plural': 'Врачи',
                'ordering': ['specialty', 'full_name'],
            },
        ),
        migrations.AddField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='appointments.doctor', verbose_name='Врач'),
        ),
    ]
