server {
    listen 80;
    server_name medqueue.me www.medqueue.me _;

    location /.well-known/acme-challenge/ {
        root /var/www/letsencrypt;
        default_type "text/plain";
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    http2 on;
    server_name medqueue.me www.medqueue.me _;

    ssl_certificate /etc/letsencrypt/live/medqueue.me/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/medqueue.me/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;

    location /css/ {
        alias /staticfiles/css/;
    }

    location /js/ {
        alias /staticfiles/js/;
    }

    location /images/ {
        alias /staticfiles/images/;
    }

    location /video/ {
        alias /staticfiles/video/;
    }

    location / {
        proxy_pass http://backend:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header X-Forwarded-Host $host;
    }
}
