--
-- PostgreSQL database dump
--

\restrict qhQffPNIfzYZc9sFhWzVfXzQGgT1LhYgoiEIUakQBAcV82stU9R4wIGxS2hnUL4

-- Dumped from database version 15.18
-- Dumped by pg_dump version 15.18

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: appointments_appointment; Type: TABLE; Schema: public; Owner: medqueue
--

CREATE TABLE public.appointments_appointment (
    id bigint NOT NULL,
    code character varying(6) NOT NULL,
    patient_name character varying(200) NOT NULL,
    specialty character varying(50) NOT NULL,
    datetime timestamp with time zone NOT NULL,
    queue_position integer NOT NULL,
    status character varying(20) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    hospital_id bigint NOT NULL,
    user_id integer,
    doctor_id bigint,
    comment text NOT NULL,
    doctor_recommendation text NOT NULL,
    exam_summary text NOT NULL,
    prescribed_medications text NOT NULL,
    prescription_confirmed boolean NOT NULL,
    prescription_confirmed_at timestamp with time zone,
    prescription_confirmed_by character varying(200) NOT NULL
);


ALTER TABLE public.appointments_appointment OWNER TO medqueue;

--
-- Name: appointments_appointment_id_seq; Type: SEQUENCE; Schema: public; Owner: medqueue
--

ALTER TABLE public.appointments_appointment ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.appointments_appointment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: appointments_cardverificationcode; Type: TABLE; Schema: public; Owner: medqueue
--

CREATE TABLE public.appointments_cardverificationcode (
    id bigint NOT NULL,
    code character varying(6) NOT NULL,
    is_used boolean NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    created_at timestamp with time zone NOT NULL,
    card_id bigint NOT NULL,
    user_id integer NOT NULL
);


ALTER TABLE public.appointments_cardverificationcode OWNER TO medqueue;

--
-- Name: appointments_cardverificationcode_id_seq; Type: SEQUENCE; Schema: public; Owner: medqueue
--

ALTER TABLE public.appointments_cardverificationcode ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.appointments_cardverificationcode_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: appointments_doctor; Type: TABLE; Schema: public; Owner: medqueue
--

CREATE TABLE public.appointments_doctor (
    id bigint NOT NULL,
    full_name character varying(200) NOT NULL,
    specialty character varying(50) NOT NULL,
    cabinet character varying(20) NOT NULL,
    work_days character varying(100) NOT NULL,
    work_hours character varying(50) NOT NULL,
    is_active boolean NOT NULL,
    hospital_id bigint NOT NULL,
    user_id integer
);


ALTER TABLE public.appointments_doctor OWNER TO medqueue;

--
-- Name: appointments_doctor_id_seq; Type: SEQUENCE; Schema: public; Owner: medqueue
--

ALTER TABLE public.appointments_doctor ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.appointments_doctor_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: appointments_doctorinvitecode; Type: TABLE; Schema: public; Owner: medqueue
--

CREATE TABLE public.appointments_doctorinvitecode (
    id bigint NOT NULL,
    code character varying(12) NOT NULL,
    specialty character varying(50) NOT NULL,
    is_used boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    hospital_id bigint,
    used_by_id integer
);


ALTER TABLE public.appointments_doctorinvitecode OWNER TO medqueue;

--
-- Name: appointments_doctorinvitecode_id_seq; Type: SEQUENCE; Schema: public; Owner: medqueue
--

ALTER TABLE public.appointments_doctorinvitecode ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.appointments_doctorinvitecode_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: appointments_doctorreview; Type: TABLE; Schema: public; Owner: medqueue
--

CREATE TABLE public.appointments_doctorreview (
    id bigint NOT NULL,
    patient_name character varying(200) NOT NULL,
    rating smallint NOT NULL,
    comment text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    doctor_id bigint NOT NULL,
    CONSTRAINT appointments_doctorreview_rating_check CHECK ((rating >= 0))
);


ALTER TABLE public.appointments_doctorreview OWNER TO medqueue;

--
-- Name: appointments_doctorreview_id_seq; Type: SEQUENCE; Schema: public; Owner: medqueue
--

ALTER TABLE public.appointments_doctorreview ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.appointments_doctorreview_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: appointments_hospital; Type: TABLE; Schema: public; Owner: medqueue
--

CREATE TABLE public.appointments_hospital (
    id bigint NOT NULL,
    name character varying(200) NOT NULL,
    type character varying(50) NOT NULL,
    address character varying(300) NOT NULL,
    waiting_time integer NOT NULL,
    is_active boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    phone character varying(50) NOT NULL,
    description text NOT NULL,
    latitude double precision,
    longitude double precision
);


ALTER TABLE public.appointments_hospital OWNER TO medqueue;

--
-- Name: appointments_hospital_id_seq; Type: SEQUENCE; Schema: public; Owner: medqueue
--

ALTER TABLE public.appointments_hospital ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.appointments_hospital_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: appointments_passwordresetcode; Type: TABLE; Schema: public; Owner: medqueue
--

CREATE TABLE public.appointments_passwordresetcode (
    id bigint NOT NULL,
    email character varying(254) NOT NULL,
    code character varying(6) NOT NULL,
    created_at timestamp with time zone NOT NULL
);


ALTER TABLE public.appointments_passwordresetcode OWNER TO medqueue;

--
-- Name: appointments_passwordresetcode_id_seq; Type: SEQUENCE; Schema: public; Owner: medqueue
--

ALTER TABLE public.appointments_passwordresetcode ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.appointments_passwordresetcode_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: appointments_paymentcard; Type: TABLE; Schema: public; Owner: medqueue
--

CREATE TABLE public.appointments_paymentcard (
    id bigint NOT NULL,
    card_holder character varying(120) NOT NULL,
    brand character varying(20) NOT NULL,
    last4 character varying(4) NOT NULL,
    exp_month smallint NOT NULL,
    exp_year smallint NOT NULL,
    token character varying(64) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    user_id integer NOT NULL,
    is_verified boolean NOT NULL,
    CONSTRAINT appointments_paymentcard_exp_month_check CHECK ((exp_month >= 0)),
    CONSTRAINT appointments_paymentcard_exp_year_check CHECK ((exp_year >= 0))
);


ALTER TABLE public.appointments_paymentcard OWNER TO medqueue;

--
-- Name: appointments_paymentcard_id_seq; Type: SEQUENCE; Schema: public; Owner: medqueue
--

ALTER TABLE public.appointments_paymentcard ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.appointments_paymentcard_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: appointments_paymenttransaction; Type: TABLE; Schema: public; Owner: medqueue
--

CREATE TABLE public.appointments_paymenttransaction (
    id bigint NOT NULL,
    amount numeric(10,2) NOT NULL,
    currency character varying(10) NOT NULL,
    status character varying(20) NOT NULL,
    transaction_ref character varying(32) NOT NULL,
    merchant_name character varying(120) NOT NULL,
    card_last4 character varying(4) NOT NULL,
    card_brand character varying(20) NOT NULL,
    description character varying(255) NOT NULL,
    authorization_code character varying(12) NOT NULL,
    paid_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL,
    subscription_id bigint,
    user_id integer NOT NULL
);


ALTER TABLE public.appointments_paymenttransaction OWNER TO medqueue;

--
-- Name: appointments_paymenttransaction_id_seq; Type: SEQUENCE; Schema: public; Owner: medqueue
--

ALTER TABLE public.appointments_paymenttransaction ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.appointments_paymenttransaction_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: appointments_userprofile; Type: TABLE; Schema: public; Owner: medqueue
--

CREATE TABLE public.appointments_userprofile (
    id bigint NOT NULL,
    role character varying(20) NOT NULL,
    phone character varying(30) NOT NULL,
    user_id integer NOT NULL
);


ALTER TABLE public.appointments_userprofile OWNER TO medqueue;

--
-- Name: appointments_userprofile_id_seq; Type: SEQUENCE; Schema: public; Owner: medqueue
--

ALTER TABLE public.appointments_userprofile ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.appointments_userprofile_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: appointments_usersubscription; Type: TABLE; Schema: public; Owner: medqueue
--

CREATE TABLE public.appointments_usersubscription (
    id bigint NOT NULL,
    plan character varying(20) NOT NULL,
    status character varying(20) NOT NULL,
    auto_taxi_enabled boolean NOT NULL,
    started_at timestamp with time zone NOT NULL,
    next_billing_date date,
    updated_at timestamp with time zone NOT NULL,
    user_id integer NOT NULL,
    social_reason text NOT NULL,
    social_reason_confirmed_at timestamp with time zone
);


ALTER TABLE public.appointments_usersubscription OWNER TO medqueue;

--
-- Name: appointments_usersubscription_id_seq; Type: SEQUENCE; Schema: public; Owner: medqueue
--

ALTER TABLE public.appointments_usersubscription ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.appointments_usersubscription_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: appointments_verificationcode; Type: TABLE; Schema: public; Owner: medqueue
--

CREATE TABLE public.appointments_verificationcode (
    id bigint NOT NULL,
    email character varying(254) NOT NULL,
    code character varying(6) NOT NULL,
    name character varying(200) NOT NULL,
    password character varying(200) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    role character varying(20) NOT NULL,
    doctor_code character varying(12) NOT NULL,
    username character varying(150) NOT NULL
);


ALTER TABLE public.appointments_verificationcode OWNER TO medqueue;

--
-- Name: appointments_verificationcode_id_seq; Type: SEQUENCE; Schema: public; Owner: medqueue
--

ALTER TABLE public.appointments_verificationcode ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.appointments_verificationcode_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: medqueue
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO medqueue;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: medqueue
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: medqueue
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO medqueue;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: medqueue
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: medqueue
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO medqueue;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: medqueue
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user; Type: TABLE; Schema: public; Owner: medqueue
--

CREATE TABLE public.auth_user (
    id integer NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL
);


ALTER TABLE public.auth_user OWNER TO medqueue;

--
-- Name: auth_user_groups; Type: TABLE; Schema: public; Owner: medqueue
--

CREATE TABLE public.auth_user_groups (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.auth_user_groups OWNER TO medqueue;

--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: medqueue
--

ALTER TABLE public.auth_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_id_seq; Type: SEQUENCE; Schema: public; Owner: medqueue
--

ALTER TABLE public.auth_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_user_permissions; Type: TABLE; Schema: public; Owner: medqueue
--

CREATE TABLE public.auth_user_user_permissions (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_user_user_permissions OWNER TO medqueue;

--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: medqueue
--

ALTER TABLE public.auth_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: medqueue
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id integer NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO medqueue;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: medqueue
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: medqueue
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO medqueue;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: medqueue
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: medqueue
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO medqueue;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: medqueue
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: medqueue
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO medqueue;

--
-- Data for Name: appointments_appointment; Type: TABLE DATA; Schema: public; Owner: medqueue
--

COPY public.appointments_appointment (id, code, patient_name, specialty, datetime, queue_position, status, created_at, updated_at, hospital_id, user_id, doctor_id, comment, doctor_recommendation, exam_summary, prescribed_medications, prescription_confirmed, prescription_confirmed_at, prescription_confirmed_by) FROM stdin;
1	E27M9P	╨Р╨╣╨│╨╡╤А╨╕╨╝ ╨Ц╨░╨║╤Г╨┐╨╛╨▓╨░	╨б╤В╨╛╨╝╨░╤В╨╛╨╗╨╛╨│	2026-05-19 09:00:00+00	1	confirmed	2026-05-19 22:43:07.739112+00	2026-05-19 22:43:07.739118+00	20	\N	256					f	\N	
2	4RBSRK	╨Э╤Г╤А╨╗╨░╨╜ ╨Ъ╨░╤Б╤Л╨╝╨╛╨▓	╨б╤В╨╛╨╝╨░╤В╨╛╨╗╨╛╨│	2026-05-19 10:00:00+00	2	confirmed	2026-05-19 22:43:07.745354+00	2026-05-19 22:43:07.745361+00	20	\N	256					f	\N	
3	SCFW6J	╨Ф╨╕╨╜╨░ ╨б╨╡╨╣╤В╨║╨░╨╗╨╕	╨б╤В╨╛╨╝╨░╤В╨╛╨╗╨╛╨│	2026-05-19 11:00:00+00	3	confirmed	2026-05-19 22:43:07.749189+00	2026-05-19 22:43:07.749193+00	20	\N	256					f	\N	
4	HXTJ25	╨С╨╛╨╗╨░╤В ╨Р╤Е╨╝╨╡╤В╨╛╨▓	╨б╤В╨╛╨╝╨░╤В╨╛╨╗╨╛╨│	2026-05-20 09:00:00+00	1	confirmed	2026-05-19 22:43:07.753581+00	2026-05-19 22:43:07.753587+00	20	\N	256					f	\N	
5	F3VJQL	╨б╨░╤Г╨╗╨╡ ╨Ц╤Г╨╝╨░╨▒╨╡╨║╨╛╨▓╨░	╨Я╨╡╨┤╨╕╨░╤В╤А	2026-05-19 09:00:00+00	1	confirmed	2026-05-19 22:43:07.758823+00	2026-05-19 22:43:07.75883+00	10	\N	257					f	\N	
6	REZS6S	╨Р╨╗mat ╨С╨╡╨║╨╡╨╜╨╛╨▓	╨Я╨╡╨┤╨╕╨░╤В╤А	2026-05-19 10:00:00+00	2	confirmed	2026-05-19 22:43:07.762689+00	2026-05-19 22:43:07.762693+00	10	\N	257					f	\N	
7	5PNGRA	╨Ц╨░╨╜╨░╤А ╨Э╤Г╤А╨╕╨╡╨▓╨░	╨Я╨╡╨┤╨╕╨░╤В╤А	2026-05-19 14:00:00+00	3	confirmed	2026-05-19 22:43:07.767163+00	2026-05-19 22:43:07.767169+00	10	\N	257					f	\N	
8	TAEQW8	╨Р╤Б╤Л╨╗╨▒╨╡╨║ ╨Ю╨╝╨░╤А╨╛╨▓	╨Я╨╡╨┤╨╕╨░╤В╤А	2026-05-20 10:00:00+00	1	confirmed	2026-05-19 22:43:07.771822+00	2026-05-19 22:43:07.771832+00	10	\N	257					f	\N	
9	7UXUES	╨У╤Г╨╗╤М╨╝╨╕╤А╨░ ╨в╨░╤Б╨╛╨▓╨░	╨Э╨╡╨▓╤А╨╛╨╗╨╛╨│	2026-05-19 10:00:00+00	1	confirmed	2026-05-19 22:43:07.776684+00	2026-05-19 22:43:07.77669+00	1	\N	258					f	\N	
10	RPUZXL	╨Х╤А╨╗╨░╨╜ ╨б╨░╤В╤Л╨▒╨░╨╗╨┤╨╕╨╜	╨Э╨╡╨▓╤А╨╛╨╗╨╛╨│	2026-05-19 11:00:00+00	2	confirmed	2026-05-19 22:43:07.781037+00	2026-05-19 22:43:07.781043+00	1	\N	258					f	\N	
11	PEWTU3	╨Ь╨░╨║╨┐╨░╨╗ ╨Ъ╤Г╤Б╨░╨╕╨╜╨╛╨▓╨░	╨Э╨╡╨▓╤А╨╛╨╗╨╛╨│	2026-05-20 09:00:00+00	1	confirmed	2026-05-19 22:43:07.784598+00	2026-05-19 22:43:07.784606+00	1	\N	258					f	\N	
12	C3GLS2	╨а╤Г╤Б╨╗╨░╨╜ ╨Ф╤О╤Б╨╡╨╜╨╛╨▓	╨Э╨╡╨▓╤А╨╛╨╗╨╛╨│	2026-05-20 11:00:00+00	2	confirmed	2026-05-19 22:43:07.789172+00	2026-05-19 22:43:07.789177+00	1	\N	258					f	\N	
\.


--
-- Data for Name: appointments_cardverificationcode; Type: TABLE DATA; Schema: public; Owner: medqueue
--

COPY public.appointments_cardverificationcode (id, code, is_used, expires_at, created_at, card_id, user_id) FROM stdin;
\.


--
-- Data for Name: appointments_doctor; Type: TABLE DATA; Schema: public; Owner: medqueue
--

COPY public.appointments_doctor (id, full_name, specialty, cabinet, work_days, work_hours, is_active, hospital_id, user_id) FROM stdin;
1	╨Р╤Е╨╝╨╡╤В╨╛╨▓╨░ ╨У╤Г╨╗╤М╨╜╨░╤А╨░ ╨б╨╡╤А╨╕╨║╨▒╨░╨╡╨▓╨╜╨░	╨в╨╡╤А╨░╨┐╨╡╨▓╤В	101	╨Я╨╜-╨Я╤В	08:00-18:00	t	1	\N
2	╨б╨╡╨╣╤В╨║╨░╨╗╨╕ ╨Ф╨░╨╜╨╕╤П╤А ╨С╨╡╨║╨╛╨▓╨╕╤З	╨в╨╡╤А╨░╨┐╨╡╨▓╤В	102	╨Я╨╜-╨Я╤В	08:00-18:00	t	1	\N
3	╨Э╤Г╤А╨╗╨░╨╜╨╛╨▓╨░ ╨Р╨╣╨│╨╡╤А╨╕╨╝ ╨Ь╨░╤А╨░╤В╨╛╨▓╨╜╨░	╨Ъ╨░╤А╨┤╨╕╨╛╨╗╨╛╨│	201	╨Я╨╜-╨б╤А-╨Я╤В	09:00-16:00	t	1	\N
4	╨Ф╨╢╨░╨║╤Б╤Л╨▒╨╡╨║╨╛╨▓ ╨в╨╕╨╝╤Г╤А ╨а╨░╤И╨╕╤В╨╛╨▓╨╕╤З	╨Э╨╡╨▓╤А╨╛╨╗╨╛╨│	205	╨Т╤В-╨з╤В	10:00-16:00	t	1	\N
5	╨Ю╨╝╨░╤А╨╛╨▓╨░ ╨б╨░╤Г╨╗╨╡ ╨С╨░╨║╤Л╤В╨╛╨▓╨╜╨░	╨Ю╤Д╤В╨░╨╗╤М╨╝╨╛╨╗╨╛╨│	301	╨Я╨╜-╨Я╤В	08:00-14:00	t	1	\N
6	╨С╨░╨╣╨╢╨░╨╜╨╛╨▓╨░ ╨Ь╨╡╤А╤Г╨╡╤А╤В ╨Р╨╝╨░╨╜╨╢╨╛╨╗╨╛╨▓╨╜╨░	╨в╨╡╤А╨░╨┐╨╡╨▓╤В	110	╨Я╨╜-╨Я╤В	08:00-18:00	t	2	\N
7	╨б╨░╨▒╨╕╤В╨╛╨▓ ╨Р╨╗╨╝╨░╤Б ╨Х╤А╨╗╨░╨╜╨╛╨▓╨╕╤З	╨е╨╕╤А╤Г╤А╨│	212	╨Я╨╜-╨Я╤В	09:00-15:00	t	2	\N
8	╨Ъ╨░╤Б╤Л╨╝╨╛╨▓╨░ ╨Ц╨░╨╜╨░╤А ╨Э╤Г╤А╨╗╨░╨╜╨╛╨▓╨╜╨░	╨Ф╨╡╤А╨╝╨░╤В╨╛╨╗╨╛╨│	114	╨Я╨╜-╨б╤А-╨Я╤В	09:00-14:00	t	2	\N
9	╨в╨╛╨║╤В╨░╤А╨╛╨▓╨░ ╨Ш╨╜╨┤╨╕╤А╨░ ╨б╨╡╤А╨╕╨║╨╛╨▓╨╜╨░	╨н╨╜╨┤╨╛╨║╤А╨╕╨╜╨╛╨╗╨╛╨│	216	╨Т╤В-╨з╤В	10:00-16:00	t	2	\N
10	╨С╨╡╤А╨╕╨║╨╛╨▓╨░ ╨Р╨╣╨╜╤Г╤А ╨Ь╨░╤А╨░╤В╨╛╨▓╨╜╨░	╨в╨╡╤А╨░╨┐╨╡╨▓╤В	105	╨Я╨╜-╨Я╤В	08:00-18:00	t	6	\N
11	╨Ш╤Б╨╝╨░╨│╤Г╨╗╨╛╨▓ ╨а╤Г╤Б╨╗╨░╨╜ ╨Р╨╣╨┤╨░╤А╨╛╨▓╨╕╤З	╨в╨╡╤А╨░╨┐╨╡╨▓╤В	107	╨Я╨╜-╨Я╤В	09:00-17:00	t	6	\N
12	╨б╨╡╨╣╨┤╤Г╨╗╨╗╨░ ╨Р╤Б╨╡╨╗╤М ╨С╨╛╨╗╨░╤В╨╛╨▓╨╜╨░	╨Я╨╡╨┤╨╕╨░╤В╤А	201	╨Я╨╜-╨Я╤В	08:00-16:00	t	6	\N
13	╨Ь╤Г╤А╨░╤В╨╛╨▓ ╨С╨░╨║╤Л╤В ╨Ъ╨░╨╝╨░╨╗╨╛╨▓╨╕╤З	╨Э╨╡╨▓╤А╨╛╨╗╨╛╨│	303	╨Я╨╜-╨б╤А-╨Я╤В	09:00-14:00	t	6	\N
14	╨Ц╤Г╨╜╤Г╤Б╨╛╨▓╨░ ╨У╤Г╨╗╤М╨╜╨░╨╖ ╨С╨░╤Г╤Л╤А╨╢╨░╨╜╨╛╨▓╨╜╨░	╨У╨╕╨╜╨╡╨║╨╛╨╗╨╛╨│	208	╨Я╨╜-╨Я╤В	08:00-16:00	t	6	\N
15	╨Ш╤Б╨║╨░╨║╨╛╨▓╨░ ╨б╨░╤Г╨╗╨╡ ╨Х╤А╨╢╨░╨╜╨╛╨▓╨╜╨░	╨Я╨╡╨┤╨╕╨░╤В╤А	12	╨Я╨╜-╨Я╤В	08:00-16:00	t	9	\N
16	╨Р╨╗╤В╤Л╨╜╨▒╨╡╨║╨╛╨▓╨░ ╨У╤Г╨╗╤М╤Б╨░╨╜╨░ ╨Ъ╨░╨╕╤А╨░╤В╨╛╨▓╨╜╨░	╨Я╨╡╨┤╨╕╨░╤В╤А	14	╨Я╨╜-╨Я╤В	08:00-16:00	t	9	\N
17	╨С╨░╨╣╨┤╨░╤Г╨╗╨╡╤В╨╛╨▓╨░ ╨Ц╤Г╨╗╨┤╤Л╨╖ ╨б╨╡╤А╨╕╨║╨┐╨░╨╡╨▓╨╜╨░	╨Я╨╡╨┤╨╕╨░╤В╤А	16	╨Я╨╜-╨Я╤В	10:00-18:00	t	9	\N
18	╨Ф╨╛╤Б╨╛╨▓╨░ ╨Р╨║╨╝╨░╤А╨░╨╗ ╨Ь╨░╤А╨░╤В╨╛╨▓╨╜╨░	╨Ю╤Д╤В╨░╨╗╤М╨╝╨╛╨╗╨╛╨│	25	╨Я╨╜-╨б╤А-╨Я╤В	09:00-14:00	t	9	\N
19	╨Ъ╤Г╤А╨╝╨░╨╜╨▒╨╡╨║╨╛╨▓╨░ ╨Ь╨╛╨╗╨┤╨╕╤А ╨Х╤А╨╗╨░╨╜╨╛╨▓╨╜╨░	╨Э╨╡╨▓╤А╨╛╨╗╨╛╨│	31	╨Т╤В-╨з╤В	09:00-16:00	t	9	\N
20	╨б╨░╤В╨▒╨░╨╡╨▓╨░ ╨Ы╨╡╨╣╨╗╨░ ╨Ф╤Г╨╗╨░╤В╨╛╨▓╨╜╨░	╨Я╨╡╨┤╨╕╨░╤В╤А	11	╨Я╨╜-╨Я╤В	08:00-16:00	t	10	\N
21	╨Р╨╗╨╡╨╜╨╛╨▓╨░ ╨Ъ╤А╨╕╤Б╤В╨╕╨╜╨░ ╨б╨╡╤А╨│╨╡╨╡╨▓╨╜╨░	╨Я╨╡╨┤╨╕╨░╤В╤А	13	╨Я╨╜-╨Я╤В	09:00-17:00	t	10	\N
22	╨Э╤Г╤А╨╝╨░╨│╨░╨╜╨▒╨╡╤В╨╛╨▓ ╨Р╨╖╨░╨╝╨░╤В ╨Ь╨░╤А╨░╤В╨╛╨▓╨╕╤З	╨е╨╕╤А╤Г╤А╨│	22	╨Я╨╜-╨б╤А-╨Я╤В	09:00-14:00	t	10	\N
23	╨Ц╤Г╨╝╨░╨│╨░╨╗╨╕╨╡╨▓ ╨С╨░╨│╨╗╨░╨╜ ╨б╨╡╤А╨╕╨║╨╛╨▓╨╕╤З	╨е╨╕╤А╤Г╤А╨│	╨Р-101	╨Я╨╜-╨Я╤В	08:00-16:00	t	12	\N
24	╨Ъ╨░╨┐╨░╤А╨╛╨▓╨░ ╨Ц╨░╨╜╨░╤А╨░ ╨С╨╡╤А╨╕╨║╨╛╨▓╨╜╨░	╨в╨╡╤А╨░╨┐╨╡╨▓╤В	╨С-201	╨Я╨╜-╨Я╤В	08:00-16:00	t	12	\N
25	╨в╤Г╤Б╨╕╨┐╨╛╨▓ ╨Ь╨╡╨╕╤А╨▒╨╡╨║ ╨Х╤А╤Г╨╗╨╗╨░╨╜╨╛╨▓╨╕╤З	╨Ъ╨░╤А╨┤╨╕╨╛╨╗╨╛╨│	╨Т-301	╨Я╨╜-╨Я╤В	09:00-15:00	t	12	\N
26	╨б╨░╨│╤Л╨╜╤В╨░╨╡╨▓ ╨Э╤Г╤А╨╢╨░╨╜ ╨Р╤Б╤Л╨╗╨▒╨╡╨║╨╛╨▓╨╕╤З	╨Э╨╡╨▓╤А╨╛╨╗╨╛╨│	╨Т-311	╨Я╨╜-╨Я╤В	10:00-16:00	t	12	\N
27	╨Ф╨╢╤Г╨╝╨░╨▒╨╡╨║╨╛╨▓╨░ ╨Ф╨╕╨╜╨░ ╨Р╨╗╨╕╨▒╨╡╨║╨╛╨▓╨╜╨░	╨г╤А╨╛╨╗╨╛╨│	╨Р-115	╨Т╤В-╨з╤В	09:00-15:00	t	12	\N
28	╨С╨╡╨║╨╛╨▓╨░ ╨Р╨╗╨╕╤П ╨б╨░╨│╨╕╨╜╤В╨░╨╡╨▓╨╜╨░	╨Ъ╨░╤А╨┤╨╕╨╛╨╗╨╛╨│	╨Ъ-102	╨Я╨╜-╨Я╤В	08:00-16:00	t	13	\N
29	╨Ь╤Г╤Б╨╕╨╜ ╨Р╨╖╨╕╨╖ ╨е╨░╨╝╨╕╨┤╨╛╨▓╨╕╤З	╨е╨╕╤А╤Г╤А╨│	╨е-201	╨Я╨╜-╨Я╤В	08:00-16:00	t	13	\N
30	╨Ц╨░╨║╤Б╤Л╨▒╨░╨╡╨▓╨░ ╨Р╨╣╨┤╨░╨╜╨░ ╨б╨╡╤А╨╕╨║╨╛╨▓╨╜╨░	╨Э╨╡╨▓╤А╨╛╨╗╨╛╨│	╨Э-305	╨Я╨╜-╨Я╤В	09:00-15:00	t	13	\N
31	╨Ю╤В╨░╤А╨▒╨░╨╡╨▓ ╨Ъ╨░╨╝╨░╨╗ ╨Ц╨░╨╜╨░╤А╨▒╨╡╨║╨╛╨▓╨╕╤З	╨н╨╜╨┤╨╛╨║╤А╨╕╨╜╨╛╨╗╨╛╨│	╨н-110	╨Т╤В-╨з╤В	10:00-16:00	t	13	\N
32	╨и╨░╨╣╨╝╨╡╤А╨┤╨╡╨╜╨╛╨▓╨░ ╨У╤Г╨╗╤М╨╜╨░╤А ╨г╤А╨░╨╖╨░╨╗╨╕╨╡╨▓╨╜╨░	╨У╨╕╨╜╨╡╨║╨╛╨╗╨╛╨│	╨У-208	╨Я╨╜-╨Я╤В	08:00-15:00	t	13	\N
33	╨а╨░╤Е╨╕╨╝╨╛╨▓╨░ ╨Э╨░╨┤╨╡╨╢╨┤╨░ ╨Т╨╕╤В╨░╨╗╤М╨╡╨▓╨╜╨░	╨е╨╕╤А╤Г╤А╨│	201	╨Я╨╜-╨Я╤В	08:00-16:00	t	14	\N
34	╨Р╨╗╨╕╨▒╨╡╨║╨╛╨▓ ╨б╨░╨╜╨╢╨░╤А ╨Р╨▒╨╡╨╜╨╛╨▓╨╕╤З	╨е╨╕╤А╤Г╤А╨│	203	╨Я╨╜-╨Я╤В	09:00-17:00	t	14	\N
35	╨в╨░╨╢╨╕╨▒╨░╨╡╨▓╨░ ╨Ь╨░╨╗╨╕╤П ╨Ь╨░╤А╨░╤В╨╛╨▓╨╜╨░	╨в╨╡╤А╨░╨┐╨╡╨▓╤В	101	╨Я╨╜-╨Я╤В	08:00-16:00	t	14	\N
36	╨Э╨╕╤П╨╖╨╛╨▓ ╨С╨╡╤А╨╕╨║ ╨Р╤Е╨╝╨╡╤В╨╛╨▓╨╕╤З	╨Ъ╨░╤А╨┤╨╕╨╛╨╗╨╛╨│	305	╨Я╨╜-╨б╤А-╨Я╤В	09:00-15:00	t	14	\N
37	╨б╨╡╨╣╤В╤Е╨░╨╗╨╕ ╨С╨╛╨╗╨░╤В ╨Ь╤Г╤Е╨░╨╝╨╡╨┤╨╛╨▓╨╕╤З	╨Ъ╨░╤А╨┤╨╕╨╛╨╗╨╛╨│	╨Ъ-12	╨Я╨╜-╨Я╤В	09:00-17:00	t	17	\N
38	╨Р╨╣╤В╨▒╨░╨╡╨▓╨░ ╨У╤Г╨╗╤М╨╝╨╕╤А╨░ ╨Х╤А╨╢╨░╨╜╨╛╨▓╨╜╨░	╨Э╨╡╨▓╤А╨╛╨╗╨╛╨│	╨Э-24	╨Я╨╜-╨Я╤В	09:00-17:00	t	17	\N
39	╨Ъ╨╛╨╢╨░╨▒╨╡╨║╨╛╨▓ ╨а╤Г╤Б╨╗╨░╨╜ ╨в╤Г╤А╨╡╨▒╨╡╨║╨╛╨▓╨╕╤З	╨н╨╜╨┤╨╛╨║╤А╨╕╨╜╨╛╨╗╨╛╨│	╨н-31	╨Я╨╜-╨Я╤В	09:00-15:00	t	17	\N
40	╨в╨╛╤И╨╝╨░╤В╨╛╨▓ ╨Р╨│╨┤╨░╨╝ ╨а╨░╤Е╨╕╨╝╨╛╨▓╨╕╤З	╨Ъ╨░╤А╨┤╨╕╨╛╨╗╨╛╨│	101	╨Я╨╜-╨Я╤В	08:00-16:00	t	18	\N
41	╨Р╤Е╨╝╨╡╤В╨╢╨░╨╜╨╛╨▓╨░ ╨С╨╕╨▒╨╕╨│╤Г╨╗╤М ╨б╨╡╨╣╤В╨║╨░╨╗╨╕╨╡╨▓╨╜╨░	╨Ъ╨░╤А╨┤╨╕╨╛╨╗╨╛╨│	103	╨Я╨╜-╨Я╤В	09:00-17:00	t	18	\N
42	╨б╤Г╨╗╨╡╨╣╨╝╨╡╨╜╨╛╨▓ ╨Р╤А╨╝╨░╨╜ ╨Ъ╨╡╨╜╨╢╨╡╨▒╨╡╨║╨╛╨▓╨╕╤З	╨е╨╕╤А╤Г╤А╨│	201	╨Я╨╜-╨Я╤В	08:00-14:00	t	18	\N
43	╨Ш╨▓╨░╨╜╤З╨╡╨╜╨║╨╛ ╨Т╨╕╨║╤В╨╛╤А ╨Ю╨╗╨╡╨│╨╛╨▓╨╕╤З	╨б╤В╨╛╨╝╨░╤В╨╛╨╗╨╛╨│	11	╨Я╨╜-╨Я╤В	08:00-18:00	t	20	\N
44	╨Ь╨╕╤А╨░╤Б╨╛╨▓╨░ ╨Р╨╣╨│╨╡╤А╨╕╨╝ ╨Ъ╨░╤А╨╕╨╝╨╛╨▓╨╜╨░	╨б╤В╨╛╨╝╨░╤В╨╛╨╗╨╛╨│	13	╨Я╨╜-╨Я╤В	09:00-17:00	t	20	\N
45	╨в╨╛╨║╤Б╨░╨╜╨▒╨░╨╡╨▓ ╨Р╨╗╨┐╨░╨╝╤Л╤Б ╨Ф╨╛╤Б╨░╨╜╨╛╨▓╨╕╤З	╨б╤В╨╛╨╝╨░╤В╨╛╨╗╨╛╨│	15	╨Я╨╜-╨б╤А-╨Я╤В	08:00-14:00	t	20	\N
46	╨Ф╨╢╤Г╨╝╨░╨╜╨╕╤П╨╖╨╛╨▓╨░ ╨Э╤Г╤А╨│╤Г╨╗╤М ╨Р╨╗╨╕╨▒╨╡╨║╨╛╨▓╨╜╨░	╨б╤В╨╛╨╝╨░╤В╨╛╨╗╨╛╨│	17	╨Т╤В-╨з╤В	09:00-16:00	t	20	\N
47	╨б╨╛╨║╨╛╨╗╨╛╨▓ ╨Т╨╕╨║╤В╨╛╤А ╨Ь╨╕╤Е╨░╨╣╨╗╨╛╨▓╨╕╤З	╨е╨╕╤А╤Г╤А╨│	201	╨Я╨╜тАУ╨Я╤В	08:00тАУ16:00	t	15	\N
48	╨Ы╨╡╨▒╨╡╨┤╨╡╨▓╨░ ╨Э╨░╤В╨░╨╗╤М╤П ╨Ю╨╗╨╡╨│╨╛╨▓╨╜╨░	╨е╨╕╤А╤Г╤А╨│	202	╨Я╨╜тАУ╨б╨▒	09:00тАУ17:00	t	15	\N
49	╨Ш╨▓╨░╨╜╨╛╨▓╨░ ╨Ь╨░╤А╨╕╨╜╨░ ╨б╨╡╤А╨│╨╡╨╡╨▓╨╜╨░	╨в╨╡╤А╨░╨┐╨╡╨▓╤В	101	╨Я╨╜тАУ╨Я╤В	08:00тАУ16:00	t	15	\N
50	╨Я╨╡╤В╤А╨╛╨▓ ╨Р╨╜╨┤╤А╨╡╨╣ ╨Э╨╕╨║╨╛╨╗╨░╨╡╨▓╨╕╤З	╨в╨╡╤А╨░╨┐╨╡╨▓╤В	102	╨Я╨╜тАУ╨Я╤В	09:00тАУ17:00	t	15	\N
51	╨п╨║╨╛╨▓╨╗╨╡╨▓╨░ ╨Ш╤А╨╕╨╜╨░ ╨Я╨╡╤В╤А╨╛╨▓╨╜╨░	╨Ъ╨░╤А╨┤╨╕╨╛╨╗╨╛╨│	501	╨Я╨╜тАУ╨Я╤В	09:00тАУ16:00	t	15	\N
52	╨Ф╨░╨╜╨╕╨╗╨╛╨▓ ╨Р╨╜╨┤╤А╨╡╨╣ ╨Т╨╕╨║╤В╨╛╤А╨╛╨▓╨╕╤З	╨Ъ╨░╤А╨┤╨╕╨╛╨╗╨╛╨│	502	╨Я╨╜тАУ╨Я╤В	08:00тАУ15:00	t	15	\N
53	╨С╨╛╤А╨╕╤Б╨╛╨▓╨░ ╨Р╨╜╨░╤Б╤В╨░╤Б╨╕╤П ╨Ш╨│╨╛╤А╨╡╨▓╨╜╨░	╨Э╨╡╨▓╤А╨╛╨╗╨╛╨│	601	╨Я╨╜тАУ╨Я╤В	09:00тАУ17:00	t	15	\N
54	╨в╨╕╨╝╨╛╤Д╨╡╨╡╨▓ ╨Х╨▓╨│╨╡╨╜╨╕╨╣ ╨Я╨░╨▓╨╗╨╛╨▓╨╕╤З	╨Э╨╡╨▓╤А╨╛╨╗╨╛╨│	602	╨Я╨╜тАУ╨Я╤В	08:00тАУ15:00	t	15	\N
55	╨б╨╝╨╕╤А╨╜╨╛╨▓╨░ ╨Ю╨╗╤М╨│╨░ ╨Т╨╕╨║╤В╨╛╤А╨╛╨▓╨╜╨░	╨в╨╡╤А╨░╨┐╨╡╨▓╤В	103	╨Т╤ВтАУ╨б╨▒	08:00тАУ16:00	t	12	\N
56	╨Ъ╨╛╨╖╨╗╨╛╨▓ ╨Ф╨╝╨╕╤В╤А╨╕╨╣ ╨Р╨╗╨╡╨║╤Б╨╡╨╡╨▓╨╕╤З	╨в╨╡╤А╨░╨┐╨╡╨▓╤В	104	╨Я╨╜тАУ╨Я╤В	10:00тАУ18:00	t	12	\N
57	╨Э╨╛╨▓╨╕╨║╨╛╨▓ ╨Р╨╗╨╡╨║╤Б╨░╨╜╨┤╤А ╨С╨╛╤А╨╕╤Б╨╛╨▓╨╕╤З	╨е╨╕╤А╤Г╤А╨│	203	╨Я╨╜тАУ╨Я╤В	08:00тАУ15:00	t	12	\N
58	╨Ъ╨╛╨╖╨╗╨╛╨▓╨░ ╨Ш╤А╨╕╨╜╨░ ╨б╨╡╤А╨│╨╡╨╡╨▓╨╜╨░	╨е╨╕╤А╤Г╤А╨│	204	╨Т╤ВтАУ╨б╨▒	09:00тАУ17:00	t	12	\N
59	╨д╤А╨╛╨╗╨╛╨▓╨░ ╨б╨▓╨╡╤В╨╗╨░╨╜╨░ ╨С╨╛╤А╨╕╤Б╨╛╨▓╨╜╨░	╨Ъ╨░╤А╨┤╨╕╨╛╨╗╨╛╨│	503	╨Т╤ВтАУ╨б╨▒	09:00тАУ16:00	t	12	\N
60	╨Р╨╗╨╡╨║╤Б╨╡╨╡╨▓ ╨Ъ╨╛╨╜╤Б╤В╨░╨╜╤В╨╕╨╜ ╨а╨╛╨╝╨░╨╜╨╛╨▓╨╕╤З	╨Ъ╨░╤А╨┤╨╕╨╛╨╗╨╛╨│	504	╨Я╨╜тАУ╨Я╤В	10:00тАУ17:00	t	12	\N
61	╨а╨╛╨╝╨░╨╜╨╛╨▓╨░ ╨Ф╨░╤А╤М╤П ╨Р╨╗╨╡╨║╤Б╨░╨╜╨┤╤А╨╛╨▓╨╜╨░	╨Э╨╡╨▓╤А╨╛╨╗╨╛╨│	603	╨Т╤ВтАУ╨б╨▒	10:00тАУ18:00	t	12	\N
62	╨б╨╡╤А╨│╨╡╨╡╨▓ ╨Т╨╕╤В╨░╨╗╨╕╨╣ ╨Р╨╜╨┤╤А╨╡╨╡╨▓╨╕╤З	╨Э╨╡╨▓╤А╨╛╨╗╨╛╨│	604	╨Я╨╜тАУ╨Я╤В	09:00тАУ16:00	t	12	\N
63	╨Э╨╕╨║╨╕╤В╨╕╨╜╨░ ╨Х╨║╨░╤В╨╡╤А╨╕╨╜╨░ ╨Ю╨╗╨╡╨│╨╛╨▓╨╜╨░	╨Ю╤Д╤В╨░╨╗╤М╨╝╨╛╨╗╨╛╨│	701	╨Я╨╜тАУ╨Я╤В	09:00тАУ16:00	t	12	\N
64	╨Ь╨░╤В╨▓╨╡╨╡╨▓ ╨б╨╡╤А╨│╨╡╨╣ ╨Р╨╗╨╡╨║╤Б╨░╨╜╨┤╤А╨╛╨▓╨╕╤З	╨Ю╤Д╤В╨░╨╗╤М╨╝╨╛╨╗╨╛╨│	702	╨Я╨╜тАУ╨б╨▒	08:00тАУ16:00	t	12	\N
65	╨Ъ╨╛╨▓╨░╨╗╤С╨▓╨░ ╨Э╨░╨┤╨╡╨╢╨┤╨░ ╨Я╨╡╤В╤А╨╛╨▓╨╜╨░	╨У╨╕╨╜╨╡╨║╨╛╨╗╨╛╨│	1001	╨Я╨╜тАУ╨Я╤В	08:00тАУ16:00	t	12	\N
66	╨Ы╨░╨╖╨░╤А╨╡╨▓╨░ ╨Ю╨║╤Б╨░╨╜╨░ ╨Ь╨╕╤Е╨░╨╣╨╗╨╛╨▓╨╜╨░	╨У╨╕╨╜╨╡╨║╨╛╨╗╨╛╨│	1002	╨Я╨╜тАУ╨б╨▒	09:00тАУ17:00	t	12	\N
67	╨У╨╛╨╗╤Г╨▒╨╡╨▓ ╨а╨╛╨╝╨░╨╜ ╨Р╨╗╨╡╨║╤Б╨╡╨╡╨▓╨╕╤З	╨г╤А╨╛╨╗╨╛╨│	1101	╨Я╨╜тАУ╨Я╤В	09:00тАУ16:00	t	12	\N
68	╨Ъ╤Г╨╗╨╕╨║╨╛╨▓ ╨б╤В╨╡╨┐╨░╨╜ ╨Р╨╜╨┤╤А╨╡╨╡╨▓╨╕╤З	╨г╤А╨╛╨╗╨╛╨│	1102	╨Т╤ВтАУ╨б╨▒	08:00тАУ15:00	t	12	\N
69	╨Ъ╨╕╤А╨╕╨╗╨╗╨╛╨▓╨░ ╨Ь╨░╤А╨╕╤П ╨д╤С╨┤╨╛╤А╨╛╨▓╨╜╨░	╨Ф╨╡╤А╨╝╨░╤В╨╛╨╗╨╛╨│	801	╨Я╨╜тАУ╨Я╤В	09:00тАУ16:00	t	12	\N
70	╨С╨╡╨╗╤П╨╡╨▓ ╨Р╨╜╤В╨╛╨╜ ╨б╨╡╤А╨│╨╡╨╡╨▓╨╕╤З	╨Ф╨╡╤А╨╝╨░╤В╨╛╨╗╨╛╨│	802	╨Я╨╜тАУ╨б╨▒	10:00тАУ18:00	t	12	\N
71	╨Я╨╛╨╜╨╛╨╝╨░╤А╤С╨▓╨░ ╨У╨░╨╗╨╕╨╜╨░ ╨Ш╨▓╨░╨╜╨╛╨▓╨╜╨░	╨н╨╜╨┤╨╛╨║╤А╨╕╨╜╨╛╨╗╨╛╨│	901	╨Я╨╜тАУ╨Я╤В	09:00тАУ16:00	t	12	\N
72	╨Ъ╤А╤Л╨╗╨╛╨▓ ╨Ф╨╡╨╜╨╕╤Б ╨Ю╨╗╨╡╨│╨╛╨▓╨╕╤З	╨н╨╜╨┤╨╛╨║╤А╨╕╨╜╨╛╨╗╨╛╨│	902	╨Т╤ВтАУ╨б╨▒	08:00тАУ15:00	t	12	\N
73	╨Э╨╛╨▓╨╕╨║╨╛╨▓╨░ ╨в╨░╤В╤М╤П╨╜╨░ ╨Ш╨▓╨░╨╜╨╛╨▓╨╜╨░	╨в╨╡╤А╨░╨┐╨╡╨▓╤В	105	╨Я╨╜тАУ╨Я╤В	08:00тАУ16:00	t	14	\N
74	╨Ь╨╛╤А╨╛╨╖╨╛╨▓ ╨б╨╡╤А╨│╨╡╨╣ ╨Я╨░╨▓╨╗╨╛╨▓╨╕╤З	╨в╨╡╤А╨░╨┐╨╡╨▓╤В	106	╨Я╨╜тАУ╨б╨▒	09:00тАУ17:00	t	14	\N
75	╨Я╨╛╨┐╨╛╨▓ ╨Э╨╕╨║╨╛╨╗╨░╨╣ ╨Ф╨╝╨╕╤В╤А╨╕╨╡╨▓╨╕╤З	╨е╨╕╤А╤Г╤А╨│	205	╨Я╨╜тАУ╨Я╤В	07:00тАУ15:00	t	14	\N
76	╨б╨╛╨║╨╛╨╗╨╛╨▓ ╨Т╨╕╨║╤В╨╛╤А ╨Ь╨╕╤Е╨░╨╣╨╗╨╛╨▓╨╕╤З	╨е╨╕╤А╤Г╤А╨│	201	╨Я╨╜тАУ╨Я╤В	08:00тАУ16:00	t	14	\N
77	╨п╨║╨╛╨▓╨╗╨╡╨▓╨░ ╨Ш╤А╨╕╨╜╨░ ╨Я╨╡╤В╤А╨╛╨▓╨╜╨░	╨Ъ╨░╤А╨┤╨╕╨╛╨╗╨╛╨│	501	╨Я╨╜тАУ╨Я╤В	09:00тАУ16:00	t	14	\N
78	╨Ф╨░╨╜╨╕╨╗╨╛╨▓ ╨Р╨╜╨┤╤А╨╡╨╣ ╨Т╨╕╨║╤В╨╛╤А╨╛╨▓╨╕╤З	╨Ъ╨░╤А╨┤╨╕╨╛╨╗╨╛╨│	502	╨Я╨╜тАУ╨Я╤В	08:00тАУ15:00	t	14	\N
79	╨С╨╛╤А╨╕╤Б╨╛╨▓╨░ ╨Р╨╜╨░╤Б╤В╨░╤Б╨╕╤П ╨Ш╨│╨╛╤А╨╡╨▓╨╜╨░	╨Э╨╡╨▓╤А╨╛╨╗╨╛╨│	601	╨Я╨╜тАУ╨Я╤В	09:00тАУ17:00	t	14	\N
80	╨в╨╕╨╝╨╛╤Д╨╡╨╡╨▓ ╨Х╨▓╨│╨╡╨╜╨╕╨╣ ╨Я╨░╨▓╨╗╨╛╨▓╨╕╤З	╨Э╨╡╨▓╤А╨╛╨╗╨╛╨│	602	╨Я╨╜тАУ╨Я╤В	08:00тАУ15:00	t	14	\N
81	╨Ю╤Б╨╕╨┐╨╛╨▓╨░ ╨Т╨╡╤А╨░ ╨Э╨╕╨║╨╛╨╗╨░╨╡╨▓╨╜╨░	╨Ю╤Д╤В╨░╨╗╤М╨╝╨╛╨╗╨╛╨│	703	╨Т╤ВтАУ╨Я╤В	10:00тАУ18:00	t	14	\N
82	╨Э╨╕╨║╨╕╤В╨╕╨╜╨░ ╨Х╨║╨░╤В╨╡╤А╨╕╨╜╨░ ╨Ю╨╗╨╡╨│╨╛╨▓╨╜╨░	╨Ю╤Д╤В╨░╨╗╤М╨╝╨╛╨╗╨╛╨│	701	╨Я╨╜тАУ╨Я╤В	09:00тАУ16:00	t	14	\N
83	╨Ь╨╕╤А╨╛╨╜╨╛╨▓╨░ ╨о╨╗╨╕╤П ╨б╨╡╤А╨│╨╡╨╡╨▓╨╜╨░	╨У╨╕╨╜╨╡╨║╨╛╨╗╨╛╨│	1003	╨Т╤ВтАУ╨б╨▒	10:00тАУ18:00	t	14	\N
84	╨Ъ╨╛╨▓╨░╨╗╤С╨▓╨░ ╨Э╨░╨┤╨╡╨╢╨┤╨░ ╨Я╨╡╤В╤А╨╛╨▓╨╜╨░	╨У╨╕╨╜╨╡╨║╨╛╨╗╨╛╨│	1001	╨Я╨╜тАУ╨Я╤В	08:00тАУ16:00	t	14	\N
85	╨У╨╛╨╗╤Г╨▒╨╡╨▓ ╨а╨╛╨╝╨░╨╜ ╨Р╨╗╨╡╨║╤Б╨╡╨╡╨▓╨╕╤З	╨г╤А╨╛╨╗╨╛╨│	1101	╨Я╨╜тАУ╨Я╤В	09:00тАУ16:00	t	14	\N
86	╨Ъ╤Г╨╗╨╕╨║╨╛╨▓ ╨б╤В╨╡╨┐╨░╨╜ ╨Р╨╜╨┤╤А╨╡╨╡╨▓╨╕╤З	╨г╤А╨╛╨╗╨╛╨│	1102	╨Т╤ВтАУ╨б╨▒	08:00тАУ15:00	t	14	\N
87	╨Т╨╗╨░╤Б╨╛╨▓╨░ ╨Ы╤О╨┤╨╝╨╕╨╗╨░ ╨Т╨╕╨║╤В╨╛╤А╨╛╨▓╨╜╨░	╨Ф╨╡╤А╨╝╨░╤В╨╛╨╗╨╛╨│	803	╨Т╤ВтАУ╨б╨▒	08:00тАУ16:00	t	14	\N
88	╨Ъ╨╕╤А╨╕╨╗╨╗╨╛╨▓╨░ ╨Ь╨░╤А╨╕╤П ╨д╤С╨┤╨╛╤А╨╛╨▓╨╜╨░	╨Ф╨╡╤А╨╝╨░╤В╨╛╨╗╨╛╨│	801	╨Я╨╜тАУ╨Я╤В	09:00тАУ16:00	t	14	\N
89	╨Ч╨░╨╣╤Ж╨╡╨▓╨░ ╨Ь╨░╤А╨╕╨╜╨░ ╨Р╨╜╨░╤В╨╛╨╗╤М╨╡╨▓╨╜╨░	╨н╨╜╨┤╨╛╨║╤А╨╕╨╜╨╛╨╗╨╛╨│	903	╨Я╨╜тАУ╨Я╤В	10:00тАУ17:00	t	14	\N
90	╨Я╨╛╨╜╨╛╨╝╨░╤А╤С╨▓╨░ ╨У╨░╨╗╨╕╨╜╨░ ╨Ш╨▓╨░╨╜╨╛╨▓╨╜╨░	╨н╨╜╨┤╨╛╨║╤А╨╕╨╜╨╛╨╗╨╛╨│	901	╨Я╨╜тАУ╨Я╤В	09:00тАУ16:00	t	14	\N
91	╨д╨╡╨┤╨╛╤А╨╛╨▓╨░ ╨Х╨╗╨╡╨╜╨░ ╨о╤А╤М╨╡╨▓╨╜╨░	╨в╨╡╤А╨░╨┐╨╡╨▓╤В	107	╨Я╨╜тАУ╨Я╤В	08:00тАУ14:00	t	1	\N
92	╨Т╨╛╨╗╨║╨╛╨▓ ╨Ш╨│╨╛╤А╤М ╨Ъ╨╛╨╜╤Б╤В╨░╨╜╤В╨╕╨╜╨╛╨▓╨╕╤З	╨в╨╡╤А╨░╨┐╨╡╨▓╤В	108	╨Т╤ВтАУ╨б╨▒	10:00тАУ18:00	t	1	\N
93	╨д╤А╨╛╨╗╨╛╨▓╨░ ╨б╨▓╨╡╤В╨╗╨░╨╜╨░ ╨С╨╛╤А╨╕╤Б╨╛╨▓╨╜╨░	╨Ъ╨░╤А╨┤╨╕╨╛╨╗╨╛╨│	503	╨Т╤ВтАУ╨б╨▒	09:00тАУ16:00	t	1	\N
94	╨Р╨╗╨╡╨║╤Б╨╡╨╡╨▓ ╨Ъ╨╛╨╜╤Б╤В╨░╨╜╤В╨╕╨╜ ╨а╨╛╨╝╨░╨╜╨╛╨▓╨╕╤З	╨Ъ╨░╤А╨┤╨╕╨╛╨╗╨╛╨│	504	╨Я╨╜тАУ╨Я╤В	10:00тАУ17:00	t	1	\N
95	╨а╨╛╨╝╨░╨╜╨╛╨▓╨░ ╨Ф╨░╤А╤М╤П ╨Р╨╗╨╡╨║╤Б╨░╨╜╨┤╤А╨╛╨▓╨╜╨░	╨Э╨╡╨▓╤А╨╛╨╗╨╛╨│	603	╨Т╤ВтАУ╨б╨▒	10:00тАУ18:00	t	1	\N
96	╨б╨╡╤А╨│╨╡╨╡╨▓ ╨Т╨╕╤В╨░╨╗╨╕╨╣ ╨Р╨╜╨┤╤А╨╡╨╡╨▓╨╕╤З	╨Э╨╡╨▓╤А╨╛╨╗╨╛╨│	604	╨Я╨╜тАУ╨Я╤В	09:00тАУ16:00	t	1	\N
97	╨Ь╨░╤В╨▓╨╡╨╡╨▓ ╨б╨╡╤А╨│╨╡╨╣ ╨Р╨╗╨╡╨║╤Б╨░╨╜╨┤╤А╨╛╨▓╨╕╤З	╨Ю╤Д╤В╨░╨╗╤М╨╝╨╛╨╗╨╛╨│	702	╨Я╨╜тАУ╨б╨▒	08:00тАУ16:00	t	1	\N
98	╨Ю╤Б╨╕╨┐╨╛╨▓╨░ ╨Т╨╡╤А╨░ ╨Э╨╕╨║╨╛╨╗╨░╨╡╨▓╨╜╨░	╨Ю╤Д╤В╨░╨╗╤М╨╝╨╛╨╗╨╛╨│	703	╨Т╤ВтАУ╨Я╤В	10:00тАУ18:00	t	1	\N
99	╨С╨╡╨╗╤П╨╡╨▓ ╨Р╨╜╤В╨╛╨╜ ╨б╨╡╤А╨│╨╡╨╡╨▓╨╕╤З	╨Ф╨╡╤А╨╝╨░╤В╨╛╨╗╨╛╨│	802	╨Я╨╜тАУ╨б╨▒	10:00тАУ18:00	t	1	\N
100	╨Т╨╗╨░╤Б╨╛╨▓╨░ ╨Ы╤О╨┤╨╝╨╕╨╗╨░ ╨Т╨╕╨║╤В╨╛╤А╨╛╨▓╨╜╨░	╨Ф╨╡╤А╨╝╨░╤В╨╛╨╗╨╛╨│	803	╨Т╤ВтАУ╨б╨▒	08:00тАУ16:00	t	1	\N
101	╨Ъ╤А╤Л╨╗╨╛╨▓ ╨Ф╨╡╨╜╨╕╤Б ╨Ю╨╗╨╡╨│╨╛╨▓╨╕╤З	╨н╨╜╨┤╨╛╨║╤А╨╕╨╜╨╛╨╗╨╛╨│	902	╨Т╤ВтАУ╨б╨▒	08:00тАУ15:00	t	1	\N
102	╨Ч╨░╨╣╤Ж╨╡╨▓╨░ ╨Ь╨░╤А╨╕╨╜╨░ ╨Р╨╜╨░╤В╨╛╨╗╤М╨╡╨▓╨╜╨░	╨н╨╜╨┤╨╛╨║╤А╨╕╨╜╨╛╨╗╨╛╨│	903	╨Я╨╜тАУ╨Я╤В	10:00тАУ17:00	t	1	\N
103	╨Ш╨▓╨░╨╜╨╛╨▓╨░ ╨Ь╨░╤А╨╕╨╜╨░ ╨б╨╡╤А╨│╨╡╨╡╨▓╨╜╨░	╨в╨╡╤А╨░╨┐╨╡╨▓╤В	101	╨Я╨╜тАУ╨Я╤В	08:00тАУ16:00	t	8	\N
104	╨Я╨╡╤В╤А╨╛╨▓ ╨Р╨╜╨┤╤А╨╡╨╣ ╨Э╨╕╨║╨╛╨╗╨░╨╡╨▓╨╕╤З	╨в╨╡╤А╨░╨┐╨╡╨▓╤В	102	╨Я╨╜тАУ╨Я╤В	09:00тАУ17:00	t	8	\N
105	╨п╨║╨╛╨▓╨╗╨╡╨▓╨░ ╨Ш╤А╨╕╨╜╨░ ╨Я╨╡╤В╤А╨╛╨▓╨╜╨░	╨Ъ╨░╤А╨┤╨╕╨╛╨╗╨╛╨│	501	╨Я╨╜тАУ╨Я╤В	09:00тАУ16:00	t	8	\N
106	╨Ф╨░╨╜╨╕╨╗╨╛╨▓ ╨Р╨╜╨┤╤А╨╡╨╣ ╨Т╨╕╨║╤В╨╛╤А╨╛╨▓╨╕╤З	╨Ъ╨░╤А╨┤╨╕╨╛╨╗╨╛╨│	502	╨Я╨╜тАУ╨Я╤В	08:00тАУ15:00	t	8	\N
107	╨С╨╛╤А╨╕╤Б╨╛╨▓╨░ ╨Р╨╜╨░╤Б╤В╨░╤Б╨╕╤П ╨Ш╨│╨╛╤А╨╡╨▓╨╜╨░	╨Э╨╡╨▓╤А╨╛╨╗╨╛╨│	601	╨Я╨╜тАУ╨Я╤В	09:00тАУ17:00	t	8	\N
108	╨в╨╕╨╝╨╛╤Д╨╡╨╡╨▓ ╨Х╨▓╨│╨╡╨╜╨╕╨╣ ╨Я╨░╨▓╨╗╨╛╨▓╨╕╤З	╨Э╨╡╨▓╤А╨╛╨╗╨╛╨│	602	╨Я╨╜тАУ╨Я╤В	08:00тАУ15:00	t	8	\N
109	╨Э╨╕╨║╨╕╤В╨╕╨╜╨░ ╨Х╨║╨░╤В╨╡╤А╨╕╨╜╨░ ╨Ю╨╗╨╡╨│╨╛╨▓╨╜╨░	╨Ю╤Д╤В╨░╨╗╤М╨╝╨╛╨╗╨╛╨│	701	╨Я╨╜тАУ╨Я╤В	09:00тАУ16:00	t	8	\N
110	╨Ь╨░╤В╨▓╨╡╨╡╨▓ ╨б╨╡╤А╨│╨╡╨╣ ╨Р╨╗╨╡╨║╤Б╨░╨╜╨┤╤А╨╛╨▓╨╕╤З	╨Ю╤Д╤В╨░╨╗╤М╨╝╨╛╨╗╨╛╨│	702	╨Я╨╜тАУ╨б╨▒	08:00тАУ16:00	t	8	\N
111	╨Ъ╨╕╤А╨╕╨╗╨╗╨╛╨▓╨░ ╨Ь╨░╤А╨╕╤П ╨д╤С╨┤╨╛╤А╨╛╨▓╨╜╨░	╨Ф╨╡╤А╨╝╨░╤В╨╛╨╗╨╛╨│	801	╨Я╨╜тАУ╨Я╤В	09:00тАУ16:00	t	8	\N
112	╨С╨╡╨╗╤П╨╡╨▓ ╨Р╨╜╤В╨╛╨╜ ╨б╨╡╤А╨│╨╡╨╡╨▓╨╕╤З	╨Ф╨╡╤А╨╝╨░╤В╨╛╨╗╨╛╨│	802	╨Я╨╜тАУ╨б╨▒	10:00тАУ18:00	t	8	\N
113	╨Я╨╛╨╜╨╛╨╝╨░╤А╤С╨▓╨░ ╨У╨░╨╗╨╕╨╜╨░ ╨Ш╨▓╨░╨╜╨╛╨▓╨╜╨░	╨н╨╜╨┤╨╛╨║╤А╨╕╨╜╨╛╨╗╨╛╨│	901	╨Я╨╜тАУ╨Я╤В	09:00тАУ16:00	t	8	\N
114	╨Ъ╤А╤Л╨╗╨╛╨▓ ╨Ф╨╡╨╜╨╕╤Б ╨Ю╨╗╨╡╨│╨╛╨▓╨╕╤З	╨н╨╜╨┤╨╛╨║╤А╨╕╨╜╨╛╨╗╨╛╨│	902	╨Т╤ВтАУ╨б╨▒	08:00тАУ15:00	t	8	\N
115	╨б╨╝╨╕╤А╨╜╨╛╨▓╨░ ╨Ю╨╗╤М╨│╨░ ╨Т╨╕╨║╤В╨╛╤А╨╛╨▓╨╜╨░	╨в╨╡╤А╨░╨┐╨╡╨▓╤В	103	╨Т╤ВтАУ╨б╨▒	08:00тАУ16:00	t	2	\N
116	╨Ъ╨╛╨╖╨╗╨╛╨▓ ╨Ф╨╝╨╕╤В╤А╨╕╨╣ ╨Р╨╗╨╡╨║╤Б╨╡╨╡╨▓╨╕╤З	╨в╨╡╤А╨░╨┐╨╡╨▓╤В	104	╨Я╨╜тАУ╨Я╤В	10:00тАУ18:00	t	2	\N
117	╨д╤А╨╛╨╗╨╛╨▓╨░ ╨б╨▓╨╡╤В╨╗╨░╨╜╨░ ╨С╨╛╤А╨╕╤Б╨╛╨▓╨╜╨░	╨Ъ╨░╤А╨┤╨╕╨╛╨╗╨╛╨│	503	╨Т╤ВтАУ╨б╨▒	09:00тАУ16:00	t	2	\N
118	╨Р╨╗╨╡╨║╤Б╨╡╨╡╨▓ ╨Ъ╨╛╨╜╤Б╤В╨░╨╜╤В╨╕╨╜ ╨а╨╛╨╝╨░╨╜╨╛╨▓╨╕╤З	╨Ъ╨░╤А╨┤╨╕╨╛╨╗╨╛╨│	504	╨Я╨╜тАУ╨Я╤В	10:00тАУ17:00	t	2	\N
119	╨а╨╛╨╝╨░╨╜╨╛╨▓╨░ ╨Ф╨░╤А╤М╤П ╨Р╨╗╨╡╨║╤Б╨░╨╜╨┤╤А╨╛╨▓╨╜╨░	╨Э╨╡╨▓╤А╨╛╨╗╨╛╨│	603	╨Т╤ВтАУ╨б╨▒	10:00тАУ18:00	t	2	\N
120	╨б╨╡╤А╨│╨╡╨╡╨▓ ╨Т╨╕╤В╨░╨╗╨╕╨╣ ╨Р╨╜╨┤╤А╨╡╨╡╨▓╨╕╤З	╨Э╨╡╨▓╤А╨╛╨╗╨╛╨│	604	╨Я╨╜тАУ╨Я╤В	09:00тАУ16:00	t	2	\N
121	╨Ю╤Б╨╕╨┐╨╛╨▓╨░ ╨Т╨╡╤А╨░ ╨Э╨╕╨║╨╛╨╗╨░╨╡╨▓╨╜╨░	╨Ю╤Д╤В╨░╨╗╤М╨╝╨╛╨╗╨╛╨│	703	╨Т╤ВтАУ╨Я╤В	10:00тАУ18:00	t	2	\N
122	╨Э╨╕╨║╨╕╤В╨╕╨╜╨░ ╨Х╨║╨░╤В╨╡╤А╨╕╨╜╨░ ╨Ю╨╗╨╡╨│╨╛╨▓╨╜╨░	╨Ю╤Д╤В╨░╨╗╤М╨╝╨╛╨╗╨╛╨│	701	╨Я╨╜тАУ╨Я╤В	09:00тАУ16:00	t	2	\N
123	╨Т╨╗╨░╤Б╨╛╨▓╨░ ╨Ы╤О╨┤╨╝╨╕╨╗╨░ ╨Т╨╕╨║╤В╨╛╤А╨╛╨▓╨╜╨░	╨Ф╨╡╤А╨╝╨░╤В╨╛╨╗╨╛╨│	803	╨Т╤ВтАУ╨б╨▒	08:00тАУ16:00	t	2	\N
124	╨Ъ╨╕╤А╨╕╨╗╨╗╨╛╨▓╨░ ╨Ь╨░╤А╨╕╤П ╨д╤С╨┤╨╛╤А╨╛╨▓╨╜╨░	╨Ф╨╡╤А╨╝╨░╤В╨╛╨╗╨╛╨│	801	╨Я╨╜тАУ╨Я╤В	09:00тАУ16:00	t	2	\N
125	╨Ч╨░╨╣╤Ж╨╡╨▓╨░ ╨Ь╨░╤А╨╕╨╜╨░ ╨Р╨╜╨░╤В╨╛╨╗╤М╨╡╨▓╨╜╨░	╨н╨╜╨┤╨╛╨║╤А╨╕╨╜╨╛╨╗╨╛╨│	903	╨Я╨╜тАУ╨Я╤В	10:00тАУ17:00	t	2	\N
126	╨Я╨╛╨╜╨╛╨╝╨░╤А╤С╨▓╨░ ╨У╨░╨╗╨╕╨╜╨░ ╨Ш╨▓╨░╨╜╨╛╨▓╨╜╨░	╨н╨╜╨┤╨╛╨║╤А╨╕╨╜╨╛╨╗╨╛╨│	901	╨Я╨╜тАУ╨Я╤В	09:00тАУ16:00	t	2	\N
127	╨Э╨╛╨▓╨╕╨║╨╛╨▓╨░ ╨в╨░╤В╤М╤П╨╜╨░ ╨Ш╨▓╨░╨╜╨╛╨▓╨╜╨░	╨в╨╡╤А╨░╨┐╨╡╨▓╤В	105	╨Я╨╜тАУ╨Я╤В	08:00тАУ16:00	t	3	\N
128	╨Ь╨╛╤А╨╛╨╖╨╛╨▓ ╨б╨╡╤А╨│╨╡╨╣ ╨Я╨░╨▓╨╗╨╛╨▓╨╕╤З	╨в╨╡╤А╨░╨┐╨╡╨▓╤В	106	╨Я╨╜тАУ╨б╨▒	09:00тАУ17:00	t	3	\N
129	╨п╨║╨╛╨▓╨╗╨╡╨▓╨░ ╨Ш╤А╨╕╨╜╨░ ╨Я╨╡╤В╤А╨╛╨▓╨╜╨░	╨Ъ╨░╤А╨┤╨╕╨╛╨╗╨╛╨│	501	╨Я╨╜тАУ╨Я╤В	09:00тАУ16:00	t	3	\N
130	╨Ф╨░╨╜╨╕╨╗╨╛╨▓ ╨Р╨╜╨┤╤А╨╡╨╣ ╨Т╨╕╨║╤В╨╛╤А╨╛╨▓╨╕╤З	╨Ъ╨░╤А╨┤╨╕╨╛╨╗╨╛╨│	502	╨Я╨╜тАУ╨Я╤В	08:00тАУ15:00	t	3	\N
131	╨С╨╛╤А╨╕╤Б╨╛╨▓╨░ ╨Р╨╜╨░╤Б╤В╨░╤Б╨╕╤П ╨Ш╨│╨╛╤А╨╡╨▓╨╜╨░	╨Э╨╡╨▓╤А╨╛╨╗╨╛╨│	601	╨Я╨╜тАУ╨Я╤В	09:00тАУ17:00	t	3	\N
132	╨в╨╕╨╝╨╛╤Д╨╡╨╡╨▓ ╨Х╨▓╨│╨╡╨╜╨╕╨╣ ╨Я╨░╨▓╨╗╨╛╨▓╨╕╤З	╨Э╨╡╨▓╤А╨╛╨╗╨╛╨│	602	╨Я╨╜тАУ╨Я╤В	08:00тАУ15:00	t	3	\N
133	╨Ь╨░╤В╨▓╨╡╨╡╨▓ ╨б╨╡╤А╨│╨╡╨╣ ╨Р╨╗╨╡╨║╤Б╨░╨╜╨┤╤А╨╛╨▓╨╕╤З	╨Ю╤Д╤В╨░╨╗╤М╨╝╨╛╨╗╨╛╨│	702	╨Я╨╜тАУ╨б╨▒	08:00тАУ16:00	t	3	\N
134	╨Ю╤Б╨╕╨┐╨╛╨▓╨░ ╨Т╨╡╤А╨░ ╨Э╨╕╨║╨╛╨╗╨░╨╡╨▓╨╜╨░	╨Ю╤Д╤В╨░╨╗╤М╨╝╨╛╨╗╨╛╨│	703	╨Т╤ВтАУ╨Я╤В	10:00тАУ18:00	t	3	\N
135	╨С╨╡╨╗╤П╨╡╨▓ ╨Р╨╜╤В╨╛╨╜ ╨б╨╡╤А╨│╨╡╨╡╨▓╨╕╤З	╨Ф╨╡╤А╨╝╨░╤В╨╛╨╗╨╛╨│	802	╨Я╨╜тАУ╨б╨▒	10:00тАУ18:00	t	3	\N
136	╨Т╨╗╨░╤Б╨╛╨▓╨░ ╨Ы╤О╨┤╨╝╨╕╨╗╨░ ╨Т╨╕╨║╤В╨╛╤А╨╛╨▓╨╜╨░	╨Ф╨╡╤А╨╝╨░╤В╨╛╨╗╨╛╨│	803	╨Т╤ВтАУ╨б╨▒	08:00тАУ16:00	t	3	\N
137	╨Ъ╤А╤Л╨╗╨╛╨▓ ╨Ф╨╡╨╜╨╕╤Б ╨Ю╨╗╨╡╨│╨╛╨▓╨╕╤З	╨н╨╜╨┤╨╛╨║╤А╨╕╨╜╨╛╨╗╨╛╨│	902	╨Т╤ВтАУ╨б╨▒	08:00тАУ15:00	t	3	\N
138	╨Ч╨░╨╣╤Ж╨╡╨▓╨░ ╨Ь╨░╤А╨╕╨╜╨░ ╨Р╨╜╨░╤В╨╛╨╗╤М╨╡╨▓╨╜╨░	╨н╨╜╨┤╨╛╨║╤А╨╕╨╜╨╛╨╗╨╛╨│	903	╨Я╨╜тАУ╨Я╤В	10:00тАУ17:00	t	3	\N
139	╨д╨╡╨┤╨╛╤А╨╛╨▓╨░ ╨Х╨╗╨╡╨╜╨░ ╨о╤А╤М╨╡╨▓╨╜╨░	╨в╨╡╤А╨░╨┐╨╡╨▓╤В	107	╨Я╨╜тАУ╨Я╤В	08:00тАУ14:00	t	4	\N
140	╨Т╨╛╨╗╨║╨╛╨▓ ╨Ш╨│╨╛╤А╤М ╨Ъ╨╛╨╜╤Б╤В╨░╨╜╤В╨╕╨╜╨╛╨▓╨╕╤З	╨в╨╡╤А╨░╨┐╨╡╨▓╤В	108	╨Т╤ВтАУ╨б╨▒	10:00тАУ18:00	t	4	\N
141	╨д╤А╨╛╨╗╨╛╨▓╨░ ╨б╨▓╨╡╤В╨╗╨░╨╜╨░ ╨С╨╛╤А╨╕╤Б╨╛╨▓╨╜╨░	╨Ъ╨░╤А╨┤╨╕╨╛╨╗╨╛╨│	503	╨Т╤ВтАУ╨б╨▒	09:00тАУ16:00	t	4	\N
142	╨Р╨╗╨╡╨║╤Б╨╡╨╡╨▓ ╨Ъ╨╛╨╜╤Б╤В╨░╨╜╤В╨╕╨╜ ╨а╨╛╨╝╨░╨╜╨╛╨▓╨╕╤З	╨Ъ╨░╤А╨┤╨╕╨╛╨╗╨╛╨│	504	╨Я╨╜тАУ╨Я╤В	10:00тАУ17:00	t	4	\N
143	╨а╨╛╨╝╨░╨╜╨╛╨▓╨░ ╨Ф╨░╤А╤М╤П ╨Р╨╗╨╡╨║╤Б╨░╨╜╨┤╤А╨╛╨▓╨╜╨░	╨Э╨╡╨▓╤А╨╛╨╗╨╛╨│	603	╨Т╤ВтАУ╨б╨▒	10:00тАУ18:00	t	4	\N
144	╨б╨╡╤А╨│╨╡╨╡╨▓ ╨Т╨╕╤В╨░╨╗╨╕╨╣ ╨Р╨╜╨┤╤А╨╡╨╡╨▓╨╕╤З	╨Э╨╡╨▓╤А╨╛╨╗╨╛╨│	604	╨Я╨╜тАУ╨Я╤В	09:00тАУ16:00	t	4	\N
145	╨Э╨╕╨║╨╕╤В╨╕╨╜╨░ ╨Х╨║╨░╤В╨╡╤А╨╕╨╜╨░ ╨Ю╨╗╨╡╨│╨╛╨▓╨╜╨░	╨Ю╤Д╤В╨░╨╗╤М╨╝╨╛╨╗╨╛╨│	701	╨Я╨╜тАУ╨Я╤В	09:00тАУ16:00	t	4	\N
146	╨Ь╨░╤В╨▓╨╡╨╡╨▓ ╨б╨╡╤А╨│╨╡╨╣ ╨Р╨╗╨╡╨║╤Б╨░╨╜╨┤╤А╨╛╨▓╨╕╤З	╨Ю╤Д╤В╨░╨╗╤М╨╝╨╛╨╗╨╛╨│	702	╨Я╨╜тАУ╨б╨▒	08:00тАУ16:00	t	4	\N
147	╨Ъ╨╕╤А╨╕╨╗╨╗╨╛╨▓╨░ ╨Ь╨░╤А╨╕╤П ╨д╤С╨┤╨╛╤А╨╛╨▓╨╜╨░	╨Ф╨╡╤А╨╝╨░╤В╨╛╨╗╨╛╨│	801	╨Я╨╜тАУ╨Я╤В	09:00тАУ16:00	t	4	\N
148	╨С╨╡╨╗╤П╨╡╨▓ ╨Р╨╜╤В╨╛╨╜ ╨б╨╡╤А╨│╨╡╨╡╨▓╨╕╤З	╨Ф╨╡╤А╨╝╨░╤В╨╛╨╗╨╛╨│	802	╨Я╨╜тАУ╨б╨▒	10:00тАУ18:00	t	4	\N
149	╨Я╨╛╨╜╨╛╨╝╨░╤А╤С╨▓╨░ ╨У╨░╨╗╨╕╨╜╨░ ╨Ш╨▓╨░╨╜╨╛╨▓╨╜╨░	╨н╨╜╨┤╨╛╨║╤А╨╕╨╜╨╛╨╗╨╛╨│	901	╨Я╨╜тАУ╨Я╤В	09:00тАУ16:00	t	4	\N
150	╨Ъ╤А╤Л╨╗╨╛╨▓ ╨Ф╨╡╨╜╨╕╤Б ╨Ю╨╗╨╡╨│╨╛╨▓╨╕╤З	╨н╨╜╨┤╨╛╨║╤А╨╕╨╜╨╛╨╗╨╛╨│	902	╨Т╤ВтАУ╨б╨▒	08:00тАУ15:00	t	4	\N
151	╨Ш╨▓╨░╨╜╨╛╨▓╨░ ╨Ь╨░╤А╨╕╨╜╨░ ╨б╨╡╤А╨│╨╡╨╡╨▓╨╜╨░	╨в╨╡╤А╨░╨┐╨╡╨▓╤В	101	╨Я╨╜тАУ╨Я╤В	08:00тАУ16:00	t	5	\N
152	╨Я╨╡╤В╤А╨╛╨▓ ╨Р╨╜╨┤╤А╨╡╨╣ ╨Э╨╕╨║╨╛╨╗╨░╨╡╨▓╨╕╤З	╨в╨╡╤А╨░╨┐╨╡╨▓╤В	102	╨Я╨╜тАУ╨Я╤В	09:00тАУ17:00	t	5	\N
153	╨п╨║╨╛╨▓╨╗╨╡╨▓╨░ ╨Ш╤А╨╕╨╜╨░ ╨Я╨╡╤В╤А╨╛╨▓╨╜╨░	╨Ъ╨░╤А╨┤╨╕╨╛╨╗╨╛╨│	501	╨Я╨╜тАУ╨Я╤В	09:00тАУ16:00	t	5	\N
154	╨Ф╨░╨╜╨╕╨╗╨╛╨▓ ╨Р╨╜╨┤╤А╨╡╨╣ ╨Т╨╕╨║╤В╨╛╤А╨╛╨▓╨╕╤З	╨Ъ╨░╤А╨┤╨╕╨╛╨╗╨╛╨│	502	╨Я╨╜тАУ╨Я╤В	08:00тАУ15:00	t	5	\N
155	╨С╨╛╤А╨╕╤Б╨╛╨▓╨░ ╨Р╨╜╨░╤Б╤В╨░╤Б╨╕╤П ╨Ш╨│╨╛╤А╨╡╨▓╨╜╨░	╨Э╨╡╨▓╤А╨╛╨╗╨╛╨│	601	╨Я╨╜тАУ╨Я╤В	09:00тАУ17:00	t	5	\N
156	╨в╨╕╨╝╨╛╤Д╨╡╨╡╨▓ ╨Х╨▓╨│╨╡╨╜╨╕╨╣ ╨Я╨░╨▓╨╗╨╛╨▓╨╕╤З	╨Э╨╡╨▓╤А╨╛╨╗╨╛╨│	602	╨Я╨╜тАУ╨Я╤В	08:00тАУ15:00	t	5	\N
157	╨Ю╤Б╨╕╨┐╨╛╨▓╨░ ╨Т╨╡╤А╨░ ╨Э╨╕╨║╨╛╨╗╨░╨╡╨▓╨╜╨░	╨Ю╤Д╤В╨░╨╗╤М╨╝╨╛╨╗╨╛╨│	703	╨Т╤ВтАУ╨Я╤В	10:00тАУ18:00	t	5	\N
158	╨Э╨╕╨║╨╕╤В╨╕╨╜╨░ ╨Х╨║╨░╤В╨╡╤А╨╕╨╜╨░ ╨Ю╨╗╨╡╨│╨╛╨▓╨╜╨░	╨Ю╤Д╤В╨░╨╗╤М╨╝╨╛╨╗╨╛╨│	701	╨Я╨╜тАУ╨Я╤В	09:00тАУ16:00	t	5	\N
159	╨Т╨╗╨░╤Б╨╛╨▓╨░ ╨Ы╤О╨┤╨╝╨╕╨╗╨░ ╨Т╨╕╨║╤В╨╛╤А╨╛╨▓╨╜╨░	╨Ф╨╡╤А╨╝╨░╤В╨╛╨╗╨╛╨│	803	╨Т╤ВтАУ╨б╨▒	08:00тАУ16:00	t	5	\N
160	╨Ъ╨╕╤А╨╕╨╗╨╗╨╛╨▓╨░ ╨Ь╨░╤А╨╕╤П ╨д╤С╨┤╨╛╤А╨╛╨▓╨╜╨░	╨Ф╨╡╤А╨╝╨░╤В╨╛╨╗╨╛╨│	801	╨Я╨╜тАУ╨Я╤В	09:00тАУ16:00	t	5	\N
161	╨Ч╨░╨╣╤Ж╨╡╨▓╨░ ╨Ь╨░╤А╨╕╨╜╨░ ╨Р╨╜╨░╤В╨╛╨╗╤М╨╡╨▓╨╜╨░	╨н╨╜╨┤╨╛╨║╤А╨╕╨╜╨╛╨╗╨╛╨│	903	╨Я╨╜тАУ╨Я╤В	10:00тАУ17:00	t	5	\N
162	╨Я╨╛╨╜╨╛╨╝╨░╤А╤С╨▓╨░ ╨У╨░╨╗╨╕╨╜╨░ ╨Ш╨▓╨░╨╜╨╛╨▓╨╜╨░	╨н╨╜╨┤╨╛╨║╤А╨╕╨╜╨╛╨╗╨╛╨│	901	╨Я╨╜тАУ╨Я╤В	09:00тАУ16:00	t	5	\N
163	╨б╨╝╨╕╤А╨╜╨╛╨▓╨░ ╨Ю╨╗╤М╨│╨░ ╨Т╨╕╨║╤В╨╛╤А╨╛╨▓╨╜╨░	╨в╨╡╤А╨░╨┐╨╡╨▓╤В	103	╨Т╤ВтАУ╨б╨▒	08:00тАУ16:00	t	6	\N
164	╨Ъ╨╛╨╖╨╗╨╛╨▓ ╨Ф╨╝╨╕╤В╤А╨╕╨╣ ╨Р╨╗╨╡╨║╤Б╨╡╨╡╨▓╨╕╤З	╨в╨╡╤А╨░╨┐╨╡╨▓╤В	104	╨Я╨╜тАУ╨Я╤В	10:00тАУ18:00	t	6	\N
165	╨д╤А╨╛╨╗╨╛╨▓╨░ ╨б╨▓╨╡╤В╨╗╨░╨╜╨░ ╨С╨╛╤А╨╕╤Б╨╛╨▓╨╜╨░	╨Ъ╨░╤А╨┤╨╕╨╛╨╗╨╛╨│	503	╨Т╤ВтАУ╨б╨▒	09:00тАУ16:00	t	6	\N
166	╨Р╨╗╨╡╨║╤Б╨╡╨╡╨▓ ╨Ъ╨╛╨╜╤Б╤В╨░╨╜╤В╨╕╨╜ ╨а╨╛╨╝╨░╨╜╨╛╨▓╨╕╤З	╨Ъ╨░╤А╨┤╨╕╨╛╨╗╨╛╨│	504	╨Я╨╜тАУ╨Я╤В	10:00тАУ17:00	t	6	\N
167	╨а╨╛╨╝╨░╨╜╨╛╨▓╨░ ╨Ф╨░╤А╤М╤П ╨Р╨╗╨╡╨║╤Б╨░╨╜╨┤╤А╨╛╨▓╨╜╨░	╨Э╨╡╨▓╤А╨╛╨╗╨╛╨│	603	╨Т╤ВтАУ╨б╨▒	10:00тАУ18:00	t	6	\N
168	╨б╨╡╤А╨│╨╡╨╡╨▓ ╨Т╨╕╤В╨░╨╗╨╕╨╣ ╨Р╨╜╨┤╤А╨╡╨╡╨▓╨╕╤З	╨Э╨╡╨▓╤А╨╛╨╗╨╛╨│	604	╨Я╨╜тАУ╨Я╤В	09:00тАУ16:00	t	6	\N
169	╨Ь╨░╤В╨▓╨╡╨╡╨▓ ╨б╨╡╤А╨│╨╡╨╣ ╨Р╨╗╨╡╨║╤Б╨░╨╜╨┤╤А╨╛╨▓╨╕╤З	╨Ю╤Д╤В╨░╨╗╤М╨╝╨╛╨╗╨╛╨│	702	╨Я╨╜тАУ╨б╨▒	08:00тАУ16:00	t	6	\N
170	╨Ю╤Б╨╕╨┐╨╛╨▓╨░ ╨Т╨╡╤А╨░ ╨Э╨╕╨║╨╛╨╗╨░╨╡╨▓╨╜╨░	╨Ю╤Д╤В╨░╨╗╤М╨╝╨╛╨╗╨╛╨│	703	╨Т╤ВтАУ╨Я╤В	10:00тАУ18:00	t	6	\N
171	╨С╨╡╨╗╤П╨╡╨▓ ╨Р╨╜╤В╨╛╨╜ ╨б╨╡╤А╨│╨╡╨╡╨▓╨╕╤З	╨Ф╨╡╤А╨╝╨░╤В╨╛╨╗╨╛╨│	802	╨Я╨╜тАУ╨б╨▒	10:00тАУ18:00	t	6	\N
172	╨Т╨╗╨░╤Б╨╛╨▓╨░ ╨Ы╤О╨┤╨╝╨╕╨╗╨░ ╨Т╨╕╨║╤В╨╛╤А╨╛╨▓╨╜╨░	╨Ф╨╡╤А╨╝╨░╤В╨╛╨╗╨╛╨│	803	╨Т╤ВтАУ╨б╨▒	08:00тАУ16:00	t	6	\N
173	╨Ъ╤А╤Л╨╗╨╛╨▓ ╨Ф╨╡╨╜╨╕╤Б ╨Ю╨╗╨╡╨│╨╛╨▓╨╕╤З	╨н╨╜╨┤╨╛╨║╤А╨╕╨╜╨╛╨╗╨╛╨│	902	╨Т╤ВтАУ╨б╨▒	08:00тАУ15:00	t	6	\N
174	╨Ч╨░╨╣╤Ж╨╡╨▓╨░ ╨Ь╨░╤А╨╕╨╜╨░ ╨Р╨╜╨░╤В╨╛╨╗╤М╨╡╨▓╨╜╨░	╨н╨╜╨┤╨╛╨║╤А╨╕╨╜╨╛╨╗╨╛╨│	903	╨Я╨╜тАУ╨Я╤В	10:00тАУ17:00	t	6	\N
175	╨Э╨╛╨▓╨╕╨║╨╛╨▓╨░ ╨в╨░╤В╤М╤П╨╜╨░ ╨Ш╨▓╨░╨╜╨╛╨▓╨╜╨░	╨в╨╡╤А╨░╨┐╨╡╨▓╤В	105	╨Я╨╜тАУ╨Я╤В	08:00тАУ16:00	t	7	\N
176	╨Ь╨╛╤А╨╛╨╖╨╛╨▓ ╨б╨╡╤А╨│╨╡╨╣ ╨Я╨░╨▓╨╗╨╛╨▓╨╕╤З	╨в╨╡╤А╨░╨┐╨╡╨▓╤В	106	╨Я╨╜тАУ╨б╨▒	09:00тАУ17:00	t	7	\N
177	╨п╨║╨╛╨▓╨╗╨╡╨▓╨░ ╨Ш╤А╨╕╨╜╨░ ╨Я╨╡╤В╤А╨╛╨▓╨╜╨░	╨Ъ╨░╤А╨┤╨╕╨╛╨╗╨╛╨│	501	╨Я╨╜тАУ╨Я╤В	09:00тАУ16:00	t	7	\N
178	╨Ф╨░╨╜╨╕╨╗╨╛╨▓ ╨Р╨╜╨┤╤А╨╡╨╣ ╨Т╨╕╨║╤В╨╛╤А╨╛╨▓╨╕╤З	╨Ъ╨░╤А╨┤╨╕╨╛╨╗╨╛╨│	502	╨Я╨╜тАУ╨Я╤В	08:00тАУ15:00	t	7	\N
179	╨С╨╛╤А╨╕╤Б╨╛╨▓╨░ ╨Р╨╜╨░╤Б╤В╨░╤Б╨╕╤П ╨Ш╨│╨╛╤А╨╡╨▓╨╜╨░	╨Э╨╡╨▓╤А╨╛╨╗╨╛╨│	601	╨Я╨╜тАУ╨Я╤В	09:00тАУ17:00	t	7	\N
180	╨в╨╕╨╝╨╛╤Д╨╡╨╡╨▓ ╨Х╨▓╨│╨╡╨╜╨╕╨╣ ╨Я╨░╨▓╨╗╨╛╨▓╨╕╤З	╨Э╨╡╨▓╤А╨╛╨╗╨╛╨│	602	╨Я╨╜тАУ╨Я╤В	08:00тАУ15:00	t	7	\N
181	╨Э╨╕╨║╨╕╤В╨╕╨╜╨░ ╨Х╨║╨░╤В╨╡╤А╨╕╨╜╨░ ╨Ю╨╗╨╡╨│╨╛╨▓╨╜╨░	╨Ю╤Д╤В╨░╨╗╤М╨╝╨╛╨╗╨╛╨│	701	╨Я╨╜тАУ╨Я╤В	09:00тАУ16:00	t	7	\N
182	╨Ь╨░╤В╨▓╨╡╨╡╨▓ ╨б╨╡╤А╨│╨╡╨╣ ╨Р╨╗╨╡╨║╤Б╨░╨╜╨┤╤А╨╛╨▓╨╕╤З	╨Ю╤Д╤В╨░╨╗╤М╨╝╨╛╨╗╨╛╨│	702	╨Я╨╜тАУ╨б╨▒	08:00тАУ16:00	t	7	\N
183	╨Ъ╨╕╤А╨╕╨╗╨╗╨╛╨▓╨░ ╨Ь╨░╤А╨╕╤П ╨д╤С╨┤╨╛╤А╨╛╨▓╨╜╨░	╨Ф╨╡╤А╨╝╨░╤В╨╛╨╗╨╛╨│	801	╨Я╨╜тАУ╨Я╤В	09:00тАУ16:00	t	7	\N
184	╨С╨╡╨╗╤П╨╡╨▓ ╨Р╨╜╤В╨╛╨╜ ╨б╨╡╤А╨│╨╡╨╡╨▓╨╕╤З	╨Ф╨╡╤А╨╝╨░╤В╨╛╨╗╨╛╨│	802	╨Я╨╜тАУ╨б╨▒	10:00тАУ18:00	t	7	\N
185	╨Я╨╛╨╜╨╛╨╝╨░╤А╤С╨▓╨░ ╨У╨░╨╗╨╕╨╜╨░ ╨Ш╨▓╨░╨╜╨╛╨▓╨╜╨░	╨н╨╜╨┤╨╛╨║╤А╨╕╨╜╨╛╨╗╨╛╨│	901	╨Я╨╜тАУ╨Я╤В	09:00тАУ16:00	t	7	\N
186	╨Ъ╤А╤Л╨╗╨╛╨▓ ╨Ф╨╡╨╜╨╕╤Б ╨Ю╨╗╨╡╨│╨╛╨▓╨╕╤З	╨н╨╜╨┤╨╛╨║╤А╨╕╨╜╨╛╨╗╨╛╨│	902	╨Т╤ВтАУ╨б╨▒	08:00тАУ15:00	t	7	\N
187	╨д╨╡╨┤╨╛╤А╨╛╨▓╨░ ╨Х╨╗╨╡╨╜╨░ ╨о╤А╤М╨╡╨▓╨╜╨░	╨в╨╡╤А╨░╨┐╨╡╨▓╤В	107	╨Я╨╜тАУ╨Я╤В	08:00тАУ14:00	t	18	\N
188	╨Т╨╗╨░╤Б╨╛╨▓╨░ ╨Ы╤О╨┤╨╝╨╕╨╗╨░ ╨Т╨╕╨║╤В╨╛╤А╨╛╨▓╨╜╨░	╨Ф╨╡╤А╨╝╨░╤В╨╛╨╗╨╛╨│	803	╨Т╤ВтАУ╨б╨▒	08:00тАУ16:00	t	18	\N
189	╨а╨╛╨╝╨░╨╜╨╛╨▓╨░ ╨Ф╨░╤А╤М╤П ╨Р╨╗╨╡╨║╤Б╨░╨╜╨┤╤А╨╛╨▓╨╜╨░	╨Э╨╡╨▓╤А╨╛╨╗╨╛╨│	603	╨Т╤ВтАУ╨б╨▒	10:00тАУ18:00	t	18	\N
190	╨Т╨╛╨╗╨║╨╛╨▓ ╨Ш╨│╨╛╤А╤М ╨Ъ╨╛╨╜╤Б╤В╨░╨╜╤В╨╕╨╜╨╛╨▓╨╕╤З	╨в╨╡╤А╨░╨┐╨╡╨▓╤В	108	╨Т╤ВтАУ╨б╨▒	10:00тАУ18:00	t	19	\N
191	╨Ъ╨╕╤А╨╕╨╗╨╗╨╛╨▓╨░ ╨Ь╨░╤А╨╕╤П ╨д╤С╨┤╨╛╤А╨╛╨▓╨╜╨░	╨Ф╨╡╤А╨╝╨░╤В╨╛╨╗╨╛╨│	801	╨Я╨╜тАУ╨Я╤В	09:00тАУ16:00	t	19	\N
192	╨б╨╡╤А╨│╨╡╨╡╨▓ ╨Т╨╕╤В╨░╨╗╨╕╨╣ ╨Р╨╜╨┤╤А╨╡╨╡╨▓╨╕╤З	╨Э╨╡╨▓╤А╨╛╨╗╨╛╨│	604	╨Я╨╜тАУ╨Я╤В	09:00тАУ16:00	t	19	\N
193	╨Ш╨▓╨░╨╜╨╛╨▓╨░ ╨Ь╨░╤А╨╕╨╜╨░ ╨б╨╡╤А╨│╨╡╨╡╨▓╨╜╨░	╨в╨╡╤А╨░╨┐╨╡╨▓╤В	101	╨Я╨╜тАУ╨Я╤В	08:00тАУ16:00	t	9	\N
194	╨Я╨╡╤В╤А╨╛╨▓ ╨Р╨╜╨┤╤А╨╡╨╣ ╨Э╨╕╨║╨╛╨╗╨░╨╡╨▓╨╕╤З	╨в╨╡╤А╨░╨┐╨╡╨▓╤В	102	╨Я╨╜тАУ╨Я╤В	09:00тАУ17:00	t	9	\N
195	╨д╤А╨╛╨╗╨╛╨▓╨░ ╨б╨▓╨╡╤В╨╗╨░╨╜╨░ ╨С╨╛╤А╨╕╤Б╨╛╨▓╨╜╨░	╨Ъ╨░╤А╨┤╨╕╨╛╨╗╨╛╨│	503	╨Т╤ВтАУ╨б╨▒	09:00тАУ16:00	t	9	\N
196	╨Р╨╗╨╡╨║╤Б╨╡╨╡╨▓ ╨Ъ╨╛╨╜╤Б╤В╨░╨╜╤В╨╕╨╜ ╨а╨╛╨╝╨░╨╜╨╛╨▓╨╕╤З	╨Ъ╨░╤А╨┤╨╕╨╛╨╗╨╛╨│	504	╨Я╨╜тАУ╨Я╤В	10:00тАУ17:00	t	9	\N
197	╨С╨╛╤А╨╕╤Б╨╛╨▓╨░ ╨Р╨╜╨░╤Б╤В╨░╤Б╨╕╤П ╨Ш╨│╨╛╤А╨╡╨▓╨╜╨░	╨Э╨╡╨▓╤А╨╛╨╗╨╛╨│	601	╨Я╨╜тАУ╨Я╤В	09:00тАУ17:00	t	9	\N
198	╨в╨╕╨╝╨╛╤Д╨╡╨╡╨▓ ╨Х╨▓╨│╨╡╨╜╨╕╨╣ ╨Я╨░╨▓╨╗╨╛╨▓╨╕╤З	╨Э╨╡╨▓╤А╨╛╨╗╨╛╨│	602	╨Я╨╜тАУ╨Я╤В	08:00тАУ15:00	t	9	\N
199	╨Ю╤Б╨╕╨┐╨╛╨▓╨░ ╨Т╨╡╤А╨░ ╨Э╨╕╨║╨╛╨╗╨░╨╡╨▓╨╜╨░	╨Ю╤Д╤В╨░╨╗╤М╨╝╨╛╨╗╨╛╨│	703	╨Т╤ВтАУ╨Я╤В	10:00тАУ18:00	t	9	\N
200	╨Э╨╕╨║╨╕╤В╨╕╨╜╨░ ╨Х╨║╨░╤В╨╡╤А╨╕╨╜╨░ ╨Ю╨╗╨╡╨│╨╛╨▓╨╜╨░	╨Ю╤Д╤В╨░╨╗╤М╨╝╨╛╨╗╨╛╨│	701	╨Я╨╜тАУ╨Я╤В	09:00тАУ16:00	t	9	\N
201	╨С╨╡╨╗╤П╨╡╨▓ ╨Р╨╜╤В╨╛╨╜ ╨б╨╡╤А╨│╨╡╨╡╨▓╨╕╤З	╨Ф╨╡╤А╨╝╨░╤В╨╛╨╗╨╛╨│	802	╨Я╨╜тАУ╨б╨▒	10:00тАУ18:00	t	9	\N
202	╨Т╨╗╨░╤Б╨╛╨▓╨░ ╨Ы╤О╨┤╨╝╨╕╨╗╨░ ╨Т╨╕╨║╤В╨╛╤А╨╛╨▓╨╜╨░	╨Ф╨╡╤А╨╝╨░╤В╨╛╨╗╨╛╨│	803	╨Т╤ВтАУ╨б╨▒	08:00тАУ16:00	t	9	\N
203	╨Ч╨░╨╣╤Ж╨╡╨▓╨░ ╨Ь╨░╤А╨╕╨╜╨░ ╨Р╨╜╨░╤В╨╛╨╗╤М╨╡╨▓╨╜╨░	╨н╨╜╨┤╨╛╨║╤А╨╕╨╜╨╛╨╗╨╛╨│	903	╨Я╨╜тАУ╨Я╤В	10:00тАУ17:00	t	9	\N
204	╨Я╨╛╨╜╨╛╨╝╨░╤А╤С╨▓╨░ ╨У╨░╨╗╨╕╨╜╨░ ╨Ш╨▓╨░╨╜╨╛╨▓╨╜╨░	╨н╨╜╨┤╨╛╨║╤А╨╕╨╜╨╛╨╗╨╛╨│	901	╨Я╨╜тАУ╨Я╤В	09:00тАУ16:00	t	9	\N
205	╨б╨╝╨╕╤А╨╜╨╛╨▓╨░ ╨Ю╨╗╤М╨│╨░ ╨Т╨╕╨║╤В╨╛╤А╨╛╨▓╨╜╨░	╨в╨╡╤А╨░╨┐╨╡╨▓╤В	103	╨Т╤ВтАУ╨б╨▒	08:00тАУ16:00	t	10	\N
206	╨Ъ╨╛╨╖╨╗╨╛╨▓ ╨Ф╨╝╨╕╤В╤А╨╕╨╣ ╨Р╨╗╨╡╨║╤Б╨╡╨╡╨▓╨╕╤З	╨в╨╡╤А╨░╨┐╨╡╨▓╤В	104	╨Я╨╜тАУ╨Я╤В	10:00тАУ18:00	t	10	\N
207	╨п╨║╨╛╨▓╨╗╨╡╨▓╨░ ╨Ш╤А╨╕╨╜╨░ ╨Я╨╡╤В╤А╨╛╨▓╨╜╨░	╨Ъ╨░╤А╨┤╨╕╨╛╨╗╨╛╨│	501	╨Я╨╜тАУ╨Я╤В	09:00тАУ16:00	t	10	\N
208	╨Ф╨░╨╜╨╕╨╗╨╛╨▓ ╨Р╨╜╨┤╤А╨╡╨╣ ╨Т╨╕╨║╤В╨╛╤А╨╛╨▓╨╕╤З	╨Ъ╨░╤А╨┤╨╕╨╛╨╗╨╛╨│	502	╨Я╨╜тАУ╨Я╤В	08:00тАУ15:00	t	10	\N
209	╨а╨╛╨╝╨░╨╜╨╛╨▓╨░ ╨Ф╨░╤А╤М╤П ╨Р╨╗╨╡╨║╤Б╨░╨╜╨┤╤А╨╛╨▓╨╜╨░	╨Э╨╡╨▓╤А╨╛╨╗╨╛╨│	603	╨Т╤ВтАУ╨б╨▒	10:00тАУ18:00	t	10	\N
210	╨б╨╡╤А╨│╨╡╨╡╨▓ ╨Т╨╕╤В╨░╨╗╨╕╨╣ ╨Р╨╜╨┤╤А╨╡╨╡╨▓╨╕╤З	╨Э╨╡╨▓╤А╨╛╨╗╨╛╨│	604	╨Я╨╜тАУ╨Я╤В	09:00тАУ16:00	t	10	\N
211	╨Ь╨░╤В╨▓╨╡╨╡╨▓ ╨б╨╡╤А╨│╨╡╨╣ ╨Р╨╗╨╡╨║╤Б╨░╨╜╨┤╤А╨╛╨▓╨╕╤З	╨Ю╤Д╤В╨░╨╗╤М╨╝╨╛╨╗╨╛╨│	702	╨Я╨╜тАУ╨б╨▒	08:00тАУ16:00	t	10	\N
212	╨Ю╤Б╨╕╨┐╨╛╨▓╨░ ╨Т╨╡╤А╨░ ╨Э╨╕╨║╨╛╨╗╨░╨╡╨▓╨╜╨░	╨Ю╤Д╤В╨░╨╗╤М╨╝╨╛╨╗╨╛╨│	703	╨Т╤ВтАУ╨Я╤В	10:00тАУ18:00	t	10	\N
213	╨Ъ╨╕╤А╨╕╨╗╨╗╨╛╨▓╨░ ╨Ь╨░╤А╨╕╤П ╨д╤С╨┤╨╛╤А╨╛╨▓╨╜╨░	╨Ф╨╡╤А╨╝╨░╤В╨╛╨╗╨╛╨│	801	╨Я╨╜тАУ╨Я╤В	09:00тАУ16:00	t	10	\N
214	╨С╨╡╨╗╤П╨╡╨▓ ╨Р╨╜╤В╨╛╨╜ ╨б╨╡╤А╨│╨╡╨╡╨▓╨╕╤З	╨Ф╨╡╤А╨╝╨░╤В╨╛╨╗╨╛╨│	802	╨Я╨╜тАУ╨б╨▒	10:00тАУ18:00	t	10	\N
215	╨Ъ╤А╤Л╨╗╨╛╨▓ ╨Ф╨╡╨╜╨╕╤Б ╨Ю╨╗╨╡╨│╨╛╨▓╨╕╤З	╨н╨╜╨┤╨╛╨║╤А╨╕╨╜╨╛╨╗╨╛╨│	902	╨Т╤ВтАУ╨б╨▒	08:00тАУ15:00	t	10	\N
216	╨Ч╨░╨╣╤Ж╨╡╨▓╨░ ╨Ь╨░╤А╨╕╨╜╨░ ╨Р╨╜╨░╤В╨╛╨╗╤М╨╡╨▓╨╜╨░	╨н╨╜╨┤╨╛╨║╤А╨╕╨╜╨╛╨╗╨╛╨│	903	╨Я╨╜тАУ╨Я╤В	10:00тАУ17:00	t	10	\N
217	╨Э╨╛╨▓╨╕╨║╨╛╨▓╨░ ╨в╨░╤В╤М╤П╨╜╨░ ╨Ш╨▓╨░╨╜╨╛╨▓╨╜╨░	╨в╨╡╤А╨░╨┐╨╡╨▓╤В	105	╨Я╨╜тАУ╨Я╤В	08:00тАУ16:00	t	11	\N
218	╨Ь╨╛╤А╨╛╨╖╨╛╨▓ ╨б╨╡╤А╨│╨╡╨╣ ╨Я╨░╨▓╨╗╨╛╨▓╨╕╤З	╨в╨╡╤А╨░╨┐╨╡╨▓╤В	106	╨Я╨╜тАУ╨б╨▒	09:00тАУ17:00	t	11	\N
219	╨д╤А╨╛╨╗╨╛╨▓╨░ ╨б╨▓╨╡╤В╨╗╨░╨╜╨░ ╨С╨╛╤А╨╕╤Б╨╛╨▓╨╜╨░	╨Ъ╨░╤А╨┤╨╕╨╛╨╗╨╛╨│	503	╨Т╤ВтАУ╨б╨▒	09:00тАУ16:00	t	11	\N
220	╨Р╨╗╨╡╨║╤Б╨╡╨╡╨▓ ╨Ъ╨╛╨╜╤Б╤В╨░╨╜╤В╨╕╨╜ ╨а╨╛╨╝╨░╨╜╨╛╨▓╨╕╤З	╨Ъ╨░╤А╨┤╨╕╨╛╨╗╨╛╨│	504	╨Я╨╜тАУ╨Я╤В	10:00тАУ17:00	t	11	\N
221	╨С╨╛╤А╨╕╤Б╨╛╨▓╨░ ╨Р╨╜╨░╤Б╤В╨░╤Б╨╕╤П ╨Ш╨│╨╛╤А╨╡╨▓╨╜╨░	╨Э╨╡╨▓╤А╨╛╨╗╨╛╨│	601	╨Я╨╜тАУ╨Я╤В	09:00тАУ17:00	t	11	\N
222	╨в╨╕╨╝╨╛╤Д╨╡╨╡╨▓ ╨Х╨▓╨│╨╡╨╜╨╕╨╣ ╨Я╨░╨▓╨╗╨╛╨▓╨╕╤З	╨Э╨╡╨▓╤А╨╛╨╗╨╛╨│	602	╨Я╨╜тАУ╨Я╤В	08:00тАУ15:00	t	11	\N
223	╨Э╨╕╨║╨╕╤В╨╕╨╜╨░ ╨Х╨║╨░╤В╨╡╤А╨╕╨╜╨░ ╨Ю╨╗╨╡╨│╨╛╨▓╨╜╨░	╨Ю╤Д╤В╨░╨╗╤М╨╝╨╛╨╗╨╛╨│	701	╨Я╨╜тАУ╨Я╤В	09:00тАУ16:00	t	11	\N
224	╨Ь╨░╤В╨▓╨╡╨╡╨▓ ╨б╨╡╤А╨│╨╡╨╣ ╨Р╨╗╨╡╨║╤Б╨░╨╜╨┤╤А╨╛╨▓╨╕╤З	╨Ю╤Д╤В╨░╨╗╤М╨╝╨╛╨╗╨╛╨│	702	╨Я╨╜тАУ╨б╨▒	08:00тАУ16:00	t	11	\N
225	╨Т╨╗╨░╤Б╨╛╨▓╨░ ╨Ы╤О╨┤╨╝╨╕╨╗╨░ ╨Т╨╕╨║╤В╨╛╤А╨╛╨▓╨╜╨░	╨Ф╨╡╤А╨╝╨░╤В╨╛╨╗╨╛╨│	803	╨Т╤ВтАУ╨б╨▒	08:00тАУ16:00	t	11	\N
226	╨Ъ╨╕╤А╨╕╨╗╨╗╨╛╨▓╨░ ╨Ь╨░╤А╨╕╤П ╨д╤С╨┤╨╛╤А╨╛╨▓╨╜╨░	╨Ф╨╡╤А╨╝╨░╤В╨╛╨╗╨╛╨│	801	╨Я╨╜тАУ╨Я╤В	09:00тАУ16:00	t	11	\N
227	╨Я╨╛╨╜╨╛╨╝╨░╤А╤С╨▓╨░ ╨У╨░╨╗╨╕╨╜╨░ ╨Ш╨▓╨░╨╜╨╛╨▓╨╜╨░	╨н╨╜╨┤╨╛╨║╤А╨╕╨╜╨╛╨╗╨╛╨│	901	╨Я╨╜тАУ╨Я╤В	09:00тАУ16:00	t	11	\N
228	╨Ъ╤А╤Л╨╗╨╛╨▓ ╨Ф╨╡╨╜╨╕╤Б ╨Ю╨╗╨╡╨│╨╛╨▓╨╕╤З	╨н╨╜╨┤╨╛╨║╤А╨╕╨╜╨╛╨╗╨╛╨│	902	╨Т╤ВтАУ╨б╨▒	08:00тАУ15:00	t	11	\N
229	╨д╨╡╨┤╨╛╤А╨╛╨▓╨░ ╨Х╨╗╨╡╨╜╨░ ╨о╤А╤М╨╡╨▓╨╜╨░	╨в╨╡╤А╨░╨┐╨╡╨▓╤В	107	╨Я╨╜тАУ╨Я╤В	08:00тАУ14:00	t	16	\N
230	╨С╨╡╨╗╤П╨╡╨▓ ╨Р╨╜╤В╨╛╨╜ ╨б╨╡╤А╨│╨╡╨╡╨▓╨╕╤З	╨Ф╨╡╤А╨╝╨░╤В╨╛╨╗╨╛╨│	802	╨Я╨╜тАУ╨б╨▒	10:00тАУ18:00	t	16	\N
231	╨а╨╛╨╝╨░╨╜╨╛╨▓╨░ ╨Ф╨░╤А╤М╤П ╨Р╨╗╨╡╨║╤Б╨░╨╜╨┤╤А╨╛╨▓╨╜╨░	╨Э╨╡╨▓╤А╨╛╨╗╨╛╨│	603	╨Т╤ВтАУ╨б╨▒	10:00тАУ18:00	t	16	\N
232	╨Т╨╛╨╗╨║╨╛╨▓ ╨Ш╨│╨╛╤А╤М ╨Ъ╨╛╨╜╤Б╤В╨░╨╜╤В╨╕╨╜╨╛╨▓╨╕╤З	╨в╨╡╤А╨░╨┐╨╡╨▓╤В	108	╨Т╤ВтАУ╨б╨▒	10:00тАУ18:00	t	17	\N
233	╨Т╨╗╨░╤Б╨╛╨▓╨░ ╨Ы╤О╨┤╨╝╨╕╨╗╨░ ╨Т╨╕╨║╤В╨╛╤А╨╛╨▓╨╜╨░	╨Ф╨╡╤А╨╝╨░╤В╨╛╨╗╨╛╨│	803	╨Т╤ВтАУ╨б╨▒	08:00тАУ16:00	t	17	\N
234	╨б╨╡╤А╨│╨╡╨╡╨▓ ╨Т╨╕╤В╨░╨╗╨╕╨╣ ╨Р╨╜╨┤╤А╨╡╨╡╨▓╨╕╤З	╨Э╨╡╨▓╤А╨╛╨╗╨╛╨│	604	╨Я╨╜тАУ╨Я╤В	09:00тАУ16:00	t	17	\N
235	╨Ъ╤Г╨╖╨╜╨╡╤Ж╨╛╨▓╨░ ╨Р╨╗╨╕╨╜╨░ ╨Т╨╗╨░╨┤╨╕╨╝╨╕╤А╨╛╨▓╨╜╨░	╨б╤В╨╛╨╝╨░╤В╨╛╨╗╨╛╨│	301	╨Я╨╜тАУ╨Я╤В	09:00тАУ18:00	t	20	\N
236	╨Ю╤А╨╗╨╛╨▓ ╨Я╨░╨▓╨╡╨╗ ╨а╨╛╨╝╨░╨╜╨╛╨▓╨╕╤З	╨б╤В╨╛╨╝╨░╤В╨╛╨╗╨╛╨│	302	╨Я╨╜тАУ╨б╨▒	08:00тАУ17:00	t	20	\N
237	╨Х╤А╤И╨╛╨▓╨░ ╨б╨▓╨╡╤В╨╗╨░╨╜╨░ ╨Ш╨│╨╛╤А╨╡╨▓╨╜╨░	╨б╤В╨╛╨╝╨░╤В╨╛╨╗╨╛╨│	303	╨Я╨╜тАУ╨Я╤В	10:00тАУ19:00	t	20	\N
238	╨Ш╨▓╨░╨╜╨╛╨▓╨░ ╨Ь╨░╤А╨╕╨╜╨░ ╨б╨╡╤А╨│╨╡╨╡╨▓╨╜╨░	╨в╨╡╤А╨░╨┐╨╡╨▓╤В	101	╨Я╨╜тАУ╨Я╤В	08:00тАУ16:00	t	13	\N
239	╨Я╨╡╤В╤А╨╛╨▓ ╨Р╨╜╨┤╤А╨╡╨╣ ╨Э╨╕╨║╨╛╨╗╨░╨╡╨▓╨╕╤З	╨в╨╡╤А╨░╨┐╨╡╨▓╤В	102	╨Я╨╜тАУ╨Я╤В	09:00тАУ17:00	t	13	\N
240	╨Ы╨╡╨▒╨╡╨┤╨╡╨▓╨░ ╨Э╨░╤В╨░╨╗╤М╤П ╨Ю╨╗╨╡╨│╨╛╨▓╨╜╨░	╨е╨╕╤А╤Г╤А╨│	202	╨Я╨╜тАУ╨б╨▒	09:00тАУ17:00	t	13	\N
241	╨Э╨╛╨▓╨╕╨║╨╛╨▓ ╨Р╨╗╨╡╨║╤Б╨░╨╜╨┤╤А ╨С╨╛╤А╨╕╤Б╨╛╨▓╨╕╤З	╨е╨╕╤А╤Г╤А╨│	203	╨Я╨╜тАУ╨Я╤В	08:00тАУ15:00	t	13	\N
242	╨п╨║╨╛╨▓╨╗╨╡╨▓╨░ ╨Ш╤А╨╕╨╜╨░ ╨Я╨╡╤В╤А╨╛╨▓╨╜╨░	╨Ъ╨░╤А╨┤╨╕╨╛╨╗╨╛╨│	501	╨Я╨╜тАУ╨Я╤В	09:00тАУ16:00	t	13	\N
243	╨Ф╨░╨╜╨╕╨╗╨╛╨▓ ╨Р╨╜╨┤╤А╨╡╨╣ ╨Т╨╕╨║╤В╨╛╤А╨╛╨▓╨╕╤З	╨Ъ╨░╤А╨┤╨╕╨╛╨╗╨╛╨│	502	╨Я╨╜тАУ╨Я╤В	08:00тАУ15:00	t	13	\N
244	╨С╨╛╤А╨╕╤Б╨╛╨▓╨░ ╨Р╨╜╨░╤Б╤В╨░╤Б╨╕╤П ╨Ш╨│╨╛╤А╨╡╨▓╨╜╨░	╨Э╨╡╨▓╤А╨╛╨╗╨╛╨│	601	╨Я╨╜тАУ╨Я╤В	09:00тАУ17:00	t	13	\N
245	╨в╨╕╨╝╨╛╤Д╨╡╨╡╨▓ ╨Х╨▓╨│╨╡╨╜╨╕╨╣ ╨Я╨░╨▓╨╗╨╛╨▓╨╕╤З	╨Э╨╡╨▓╤А╨╛╨╗╨╛╨│	602	╨Я╨╜тАУ╨Я╤В	08:00тАУ15:00	t	13	\N
246	╨Ю╤Б╨╕╨┐╨╛╨▓╨░ ╨Т╨╡╤А╨░ ╨Э╨╕╨║╨╛╨╗╨░╨╡╨▓╨╜╨░	╨Ю╤Д╤В╨░╨╗╤М╨╝╨╛╨╗╨╛╨│	703	╨Т╤ВтАУ╨Я╤В	10:00тАУ18:00	t	13	\N
247	╨Э╨╕╨║╨╕╤В╨╕╨╜╨░ ╨Х╨║╨░╤В╨╡╤А╨╕╨╜╨░ ╨Ю╨╗╨╡╨│╨╛╨▓╨╜╨░	╨Ю╤Д╤В╨░╨╗╤М╨╝╨╛╨╗╨╛╨│	701	╨Я╨╜тАУ╨Я╤В	09:00тАУ16:00	t	13	\N
248	╨Ы╨░╨╖╨░╤А╨╡╨▓╨░ ╨Ю╨║╤Б╨░╨╜╨░ ╨Ь╨╕╤Е╨░╨╣╨╗╨╛╨▓╨╜╨░	╨У╨╕╨╜╨╡╨║╨╛╨╗╨╛╨│	1002	╨Я╨╜тАУ╨б╨▒	09:00тАУ17:00	t	13	\N
249	╨Ь╨╕╤А╨╛╨╜╨╛╨▓╨░ ╨о╨╗╨╕╤П ╨б╨╡╤А╨│╨╡╨╡╨▓╨╜╨░	╨У╨╕╨╜╨╡╨║╨╛╨╗╨╛╨│	1003	╨Т╤ВтАУ╨б╨▒	10:00тАУ18:00	t	13	\N
250	╨У╨╛╨╗╤Г╨▒╨╡╨▓ ╨а╨╛╨╝╨░╨╜ ╨Р╨╗╨╡╨║╤Б╨╡╨╡╨▓╨╕╤З	╨г╤А╨╛╨╗╨╛╨│	1101	╨Я╨╜тАУ╨Я╤В	09:00тАУ16:00	t	13	\N
251	╨Ъ╤Г╨╗╨╕╨║╨╛╨▓ ╨б╤В╨╡╨┐╨░╨╜ ╨Р╨╜╨┤╤А╨╡╨╡╨▓╨╕╤З	╨г╤А╨╛╨╗╨╛╨│	1102	╨Т╤ВтАУ╨б╨▒	08:00тАУ15:00	t	13	\N
252	╨Ъ╨╕╤А╨╕╨╗╨╗╨╛╨▓╨░ ╨Ь╨░╤А╨╕╤П ╨д╤С╨┤╨╛╤А╨╛╨▓╨╜╨░	╨Ф╨╡╤А╨╝╨░╤В╨╛╨╗╨╛╨│	801	╨Я╨╜тАУ╨Я╤В	09:00тАУ16:00	t	13	\N
253	╨С╨╡╨╗╤П╨╡╨▓ ╨Р╨╜╤В╨╛╨╜ ╨б╨╡╤А╨│╨╡╨╡╨▓╨╕╤З	╨Ф╨╡╤А╨╝╨░╤В╨╛╨╗╨╛╨│	802	╨Я╨╜тАУ╨б╨▒	10:00тАУ18:00	t	13	\N
254	╨Ч╨░╨╣╤Ж╨╡╨▓╨░ ╨Ь╨░╤А╨╕╨╜╨░ ╨Р╨╜╨░╤В╨╛╨╗╤М╨╡╨▓╨╜╨░	╨н╨╜╨┤╨╛╨║╤А╨╕╨╜╨╛╨╗╨╛╨│	903	╨Я╨╜тАУ╨Я╤В	10:00тАУ17:00	t	13	\N
255	╨Я╨╛╨╜╨╛╨╝╨░╤А╤С╨▓╨░ ╨У╨░╨╗╨╕╨╜╨░ ╨Ш╨▓╨░╨╜╨╛╨▓╨╜╨░	╨н╨╜╨┤╨╛╨║╤А╨╕╨╜╨╛╨╗╨╛╨│	901	╨Я╨╜тАУ╨Я╤В	09:00тАУ16:00	t	13	\N
256	╨Р╤Б╨╡╨╗╤М ╨Э╤Г╤А╨╗╨░╨╜╨╛╨▓╨░	╨б╤В╨╛╨╝╨░╤В╨╛╨╗╨╛╨│		╨Я╨╜-╨Я╤В	08:00-18:00	t	20	2
257	╨Р╤А╨╝╨░╨╜ ╨б╨╡╨╣╤В╨║╨░╨╗╨╕	╨Я╨╡╨┤╨╕╨░╤В╤А		╨Я╨╜-╨Я╤В	08:00-18:00	t	10	3
258	╨Ч╨░╤А╨╕╨╜╨░ ╨С╨╡╨║╨╛╨▓╨░	╨Э╨╡╨▓╤А╨╛╨╗╨╛╨│		╨Я╨╜-╨Я╤В	08:00-18:00	t	1	4
\.


--
-- Data for Name: appointments_doctorinvitecode; Type: TABLE DATA; Schema: public; Owner: medqueue
--

COPY public.appointments_doctorinvitecode (id, code, specialty, is_used, created_at, hospital_id, used_by_id) FROM stdin;
\.


--
-- Data for Name: appointments_doctorreview; Type: TABLE DATA; Schema: public; Owner: medqueue
--

COPY public.appointments_doctorreview (id, patient_name, rating, comment, created_at, doctor_id) FROM stdin;
\.


--
-- Data for Name: appointments_hospital; Type: TABLE DATA; Schema: public; Owner: medqueue
--

COPY public.appointments_hospital (id, name, type, address, waiting_time, is_active, created_at, phone, description, latitude, longitude) FROM stdin;
1	╨У╨╛╤А╨╛╨┤╤Б╨║╨░╤П ╨┐╨╛╨╗╨╕╨║╨╗╨╕╨╜╨╕╨║╨░ тДЦ1	╨Я╨╛╨╗╨╕╨║╨╗╨╕╨╜╨╕╨║╨░	╤Г╨╗. ╨У╨╛╨│╨╛╨╗╤П, 53, ╨Р╨╗╨╝╨░╤В╤Л	12	t	2026-05-19 22:42:36.724182+00	+7 (727) 279-50-05	╨Я╨╡╤А╨▓╨░╤П ╨│╨╛╤А╨╛╨┤╤Б╨║╨░╤П ╨┐╨╛╨╗╨╕╨║╨╗╨╕╨╜╨╕╨║╨░ ╨Р╨╗╨╝╨░╤В╤Л тАФ ╨╝╨╜╨╛╨│╨╛╨┐╤А╨╛╤Д╨╕╨╗╤М╨╜╨╛╨╡ ╤Г╤З╤А╨╡╨╢╨┤╨╡╨╜╨╕╨╡ ╨┐╨╡╤А╨▓╨╕╤З╨╜╨╛╨╣ ╨╝╨╡╨┤╨╕╨║╨╛-╤Б╨░╨╜╨╕╤В╨░╤А╨╜╨╛╨╣ ╨┐╨╛╨╝╨╛╤Й╨╕. ╨Ю╨▒╤Б╨╗╤Г╨╢╨╕╨▓╨░╨╡╤В ╨╢╨╕╤В╨╡╨╗╨╡╨╣ ╨Ь╨╡╨┤╨╡╤Г╤Б╨║╨╛╨│╨╛ ╤А╨░╨╣╨╛╨╜╨░. ╨Т╨╡╨┤╤Г╤В ╨┐╤А╨╕╤С╨╝ ╤В╨╡╤А╨░╨┐╨╡╨▓╤В╤Л, ╨┐╨╡╨┤╨╕╨░╤В╤А╤Л, ╤Г╨╖╨║╨╕╨╡ ╤Б╨┐╨╡╤Ж╨╕╨░╨╗╨╕╤Б╤В╤Л. ╨а╨░╨▒╨╛╤В╨░╨╡╤В ╨┤╨╕╨░╨│╨╜╨╛╤Б╤В╨╕╤З╨╡╤Б╨║╨░╤П ╨╗╨░╨▒╨╛╤А╨░╤В╨╛╤А╨╕╤П ╨╕ ╨║╨░╨▒╨╕╨╜╨╡╤В ╨н╨Ъ╨У.	43.257	76.907
2	╨У╨╛╤А╨╛╨┤╤Б╨║╨░╤П ╨┐╨╛╨╗╨╕╨║╨╗╨╕╨╜╨╕╨║╨░ тДЦ2	╨Я╨╛╨╗╨╕╨║╨╗╨╕╨╜╨╕╨║╨░	╤Г╨╗. ╨и╤Г╤Е╨╛╨▓╨░, 37╨С, ╨Р╨╗╨╝╨░╤В╤Л	15	t	2026-05-19 22:42:36.733493+00	+7 (727) 291-22-11	╨Я╨╛╨╗╨╕╨║╨╗╨╕╨╜╨╕╨║╨░ ╨╛╨║╨░╨╖╤Л╨▓╨░╨╡╤В ╨░╨╝╨▒╤Г╨╗╨░╤В╨╛╤А╨╜╨╛-╨┐╨╛╨╗╨╕╨║╨╗╨╕╨╜╨╕╤З╨╡╤Б╨║╤Г╤О ╨┐╨╛╨╝╨╛╤Й╤М ╨▓╨╖╤А╨╛╤Б╨╗╨╛╨╝╤Г ╨╜╨░╤Б╨╡╨╗╨╡╨╜╨╕╤О ╨С╨╛╤Б╤В╨░╨╜╨┤╤Л╨║╤Б╨║╨╛╨│╨╛ ╤А╨░╨╣╨╛╨╜╨░. ╨и╨╕╤А╨╛╨║╨╕╨╣ ╤Б╨┐╨╡╨║╤В╤А ╤Б╨┐╨╡╤Ж╨╕╨░╨╗╨╕╤Б╤В╨╛╨▓: ╤В╨╡╤А╨░╨┐╨╡╨▓╤В, ╨║╨░╤А╨┤╨╕╨╛╨╗╨╛╨│, ╨╜╨╡╨▓╤А╨╛╨╗╨╛╨│, ╨╛╤Д╤В╨░╨╗╤М╨╝╨╛╨╗╨╛╨│, ╤Е╨╕╤А╤Г╤А╨│, ╤Н╨╜╨┤╨╛╨║╤А╨╕╨╜╨╛╨╗╨╛╨│.	43.259	76.892
3	╨У╨╛╤А╨╛╨┤╤Б╨║╨░╤П ╨┐╨╛╨╗╨╕╨║╨╗╨╕╨╜╨╕╨║╨░ тДЦ3	╨Я╨╛╨╗╨╕╨║╨╗╨╕╨╜╨╕╨║╨░	╤Г╨╗. ╨а╨╛╨╖╤Л╨▒╨░╨║╨╕╨╡╨▓╨░, 74, ╨Р╨╗╨╝╨░╤В╤Л	10	t	2026-05-19 22:42:36.73938+00	+7 (727) 243-14-60	╨Я╨╛╨╗╨╕╨║╨╗╨╕╨╜╨╕╨║╨░ ╨╛╨▒╤Б╨╗╤Г╨╢╨╕╨▓╨░╨╡╤В ╨Р╤Г╤Н╨╖╨╛╨▓╤Б╨║╨╕╨╣ ╤А╨░╨╣╨╛╨╜. ╨Ю╤Б╨╜╨░╤Й╨╡╨╜╨░ ╤Б╨╛╨▓╤А╨╡╨╝╨╡╨╜╨╜╤Л╨╝ ╨┤╨╕╨░╨│╨╜╨╛╤Б╤В╨╕╤З╨╡╤Б╨║╨╕╨╝ ╨╛╨▒╨╛╤А╤Г╨┤╨╛╨▓╨░╨╜╨╕╨╡╨╝, ╤А╨░╨▒╨╛╤В╨░╨╡╤В ╨г╨Ч╨Ш-╨║╨░╨▒╨╕╨╜╨╡╤В ╨╕ ╨╗╨░╨▒╨╛╤А╨░╤В╨╛╤А╨╕╤П.	43.259	76.978
4	╨У╨╛╤А╨╛╨┤╤Б╨║╨░╤П ╨┐╨╛╨╗╨╕╨║╨╗╨╕╨╜╨╕╨║╨░ тДЦ4	╨Я╨╛╨╗╨╕╨║╨╗╨╕╨╜╨╕╨║╨░	╤Г╨╗. ╨в╨╛╤А╨░╨╣╨│╤Л╤А╨╛╨▓╨░, 12, ╨Р╨╗╨╝╨░╤В╤Л	14	t	2026-05-19 22:42:36.740622+00	+7 (727) 234-37-97	╨Р╨╝╨▒╤Г╨╗╨░╤В╨╛╤А╨╜╨╛-╨┐╨╛╨╗╨╕╨║╨╗╨╕╨╜╨╕╤З╨╡╤Б╨║╨╛╨╡ ╤Г╤З╤А╨╡╨╢╨┤╨╡╨╜╨╕╨╡ ╨▓ ╨в╤Г╤А╨║╤Б╨╕╨▒╤Б╨║╨╛╨╝ ╤А╨░╨╣╨╛╨╜╨╡. ╨Я╤А╨╕╤С╨╝ ╨▓╨╖╤А╨╛╤Б╨╗╤Л╤Е ╨┐╨╛ 8 ╤Б╨┐╨╡╤Ж╨╕╨░╨╗╤М╨╜╨╛╤Б╤В╤П╨╝. ╨а╨░╨▒╨╛╤В╨░╨╡╤В ╤И╨║╨╛╨╗╨░ ╨╖╨┤╨╛╤А╨╛╨▓╤М╤П ╨┤╨╗╤П ╨┐╨░╤Ж╨╕╨╡╨╜╤В╨╛╨▓ ╤Б ╨┤╨╕╨░╨▒╨╡╤В╨╛╨╝ ╨╕ ╨│╨╕╨┐╨╡╤А╤В╨╛╨╜╨╕╨╡╨╣.	43.261	76.896
5	╨У╨╛╤А╨╛╨┤╤Б╨║╨░╤П ╨┐╨╛╨╗╨╕╨║╨╗╨╕╨╜╨╕╨║╨░ тДЦ5	╨Я╨╛╨╗╨╕╨║╨╗╨╕╨╜╨╕╨║╨░	╤Г╨╗. ╨Ь╨░╨║╨░╤В╨░╨╡╨▓╨░, 141, ╨Р╨╗╨╝╨░╤В╤Л	11	t	2026-05-19 22:42:36.741971+00	+7 (727) 230-22-30	╨Я╨╛╨╗╨╕╨║╨╗╨╕╨╜╨╕╨║╨░ ╨▓ ╨╕╤Б╤В╨╛╤А╨╕╤З╨╡╤Б╨║╨╛╨╝ ╤Ж╨╡╨╜╤В╤А╨╡ ╨│╨╛╤А╨╛╨┤╨░. ╨Т╤Б╨╡ ╨║╨░╨▒╨╕╨╜╨╡╤В╤Л ╨╛╤Б╨╜╨░╤Й╨╡╨╜╤Л ╤Н╨╗╨╡╨║╤В╤А╨╛╨╜╨╜╤Л╨╝╨╕ ╨╛╤З╨╡╤А╨╡╨┤╤П╨╝╨╕. ╨Ш╨╝╨╡╨╡╤В╤Б╤П ╨╛╤В╨┤╨╡╨╗╤М╨╜╤Л╨╣ ╨▓╤Е╨╛╨┤ ╨┤╨╗╤П ╨╝╨░╨╗╨╛╨╝╨╛╨▒╨╕╨╗╤М╨╜╤Л╤Е ╨│╤А╨░╨╢╨┤╨░╨╜.	43.262	76.915
6	╨У╨╛╤А╨╛╨┤╤Б╨║╨░╤П ╨┐╨╛╨╗╨╕╨║╨╗╨╕╨╜╨╕╨║╨░ тДЦ7	╨Я╨╛╨╗╨╕╨║╨╗╨╕╨╜╨╕╨║╨░	╨▒╤Г╨╗╤М╨▓. ╨С╤Г╤Е╨░╤А ╨╢╤Л╤А╨░╤Г, 14, ╨Р╨╗╨╝╨░╤В╤Л	13	t	2026-05-19 22:42:36.743186+00	+7 (727) 248-17-89	╨Я╨╛╨╗╨╕╨║╨╗╨╕╨╜╨╕╨║╨░ тДЦ7 ╤А╨░╤Б╨┐╨╛╨╗╨╛╨╢╨╡╨╜╨░ ╨▓ ╨Э╨░╤Г╤А╤Л╨╖╨▒╨░╨╣╤Б╨║╨╛╨╝ ╤А╨░╨╣╨╛╨╜╨╡. ╨Х╨╢╨╡╨┤╨╜╨╡╨▓╨╜╨╛ ╨┐╤А╨╕╨╜╨╕╨╝╨░╨╡╤В ╨▒╨╛╨╗╨╡╨╡ 500 ╨┐╨░╤Ж╨╕╨╡╨╜╤В╨╛╨▓. ╨а╨░╨▒╨╛╤В╨░╨╡╤В ╨║╤А╤Г╨│╨╗╨╛╤Б╤Г╤В╨╛╤З╨╜╤Л╨╣ ╨┐╤Г╨╜╨║╤В ╨╜╨╡╨╛╤В╨╗╨╛╨╢╨╜╨╛╨╣ ╨┐╨╛╨╝╨╛╤Й╨╕, ╨╝╨╕╨╜╨╕-╨░╨┐╤В╨╡╨║╨░.	43.234	76.925
7	╨У╨╛╤А╨╛╨┤╤Б╨║╨░╤П ╨┐╨╛╨╗╨╕╨║╨╗╨╕╨╜╨╕╨║╨░ тДЦ9	╨Я╨╛╨╗╨╕╨║╨╗╨╕╨╜╨╕╨║╨░	╤Г╨╗. ╨г╤В╨╡╨│╨╡╨╜ ╨▒╨░╤В╤Л╤А╨░, 21, ╨Р╨╗╨╝╨░╤В╤Л	16	t	2026-05-19 22:42:36.751618+00	+7 (727) 264-51-17	╨Ю╨┤╨╜╨░ ╨╕╨╖ ╨║╤А╤Г╨┐╨╜╨╡╨╣╤И╨╕╤Е ╨┐╨╛╨╗╨╕╨║╨╗╨╕╨╜╨╕╨║ ╨Р╨╗╨╝╨░╨╗╨╕╨╜╤Б╨║╨╛╨│╨╛ ╤А╨░╨╣╨╛╨╜╨░. ╨Ю╨▒╨╛╤А╤Г╨┤╨╛╨▓╨░╨╜╨░ ╨╗╨░╨▒╨╛╤А╨░╤В╨╛╤А╨╕╨╡╨╣, ╤А╨╡╨╜╤В╨│╨╡╨╜-╨║╨░╨▒╨╕╨╜╨╡╤В╨╛╨╝, ╨║╨░╨▒╨╕╨╜╨╡╤В╨╛╨╝ ╤Д╤Г╨╜╨║╤Ж╨╕╨╛╨╜╨░╨╗╤М╨╜╨╛╨╣ ╨┤╨╕╨░╨│╨╜╨╛╤Б╤В╨╕╨║╨╕. ╨Ф╨╛╤Б╤В╤Г╨┐╨╜╨░ ╨╖╨░╨┐╨╕╤Б╤М ╤З╨╡╤А╨╡╨╖ ╨┐╨╛╤А╤В╨░╨╗ eGov.	43.28	76.961
8	╨У╨╛╤А╨╛╨┤╤Б╨║╨░╤П ╨┐╨╛╨╗╨╕╨║╨╗╨╕╨╜╨╕╨║╨░ тДЦ12	╨Я╨╛╨╗╨╕╨║╨╗╨╕╨╜╨╕╨║╨░	╤Г╨╗. ╨Я╨╛╨┐╨╛╨▓╨░, 23, ╨Р╨╗╨╝╨░╤В╤Л	10	t	2026-05-19 22:42:36.753505+00	+7 (727) 227-30-06	╨Я╨╛╨╗╨╕╨║╨╗╨╕╨╜╨╕╨║╨░ тДЦ12 ╨▓ ╨Ц╨╡╤В╤Л╤Б╤Г╤Б╨║╨╛╨╝ ╤А╨░╨╣╨╛╨╜╨╡. ╨б╨╛╨▓╨╝╨╡╤Й╨░╨╡╤В ╨░╨╝╨▒╤Г╨╗╨░╤В╨╛╤А╨╜╤Г╤О ╨┐╨╛╨╝╨╛╤Й╤М ╤Б ╨┤╨╜╨╡╨▓╨╜╤Л╨╝ ╤Б╤В╨░╤Ж╨╕╨╛╨╜╨░╤А╨╛╨╝ ╨╜╨░ 30 ╨║╨╛╨╡╨║. ╨Т╨╡╨┤╤С╤В ╤А╨░╨▒╨╛╤В╤Г ╤Б ╨▓╨╡╤В╨╡╤А╨░╨╜╨░╨╝╨╕ ╤В╤А╤Г╨┤╨░.	43.225	76.931
9	╨Ф╨╡╤В╤Б╨║╨░╤П ╨│╨╛╤А╨╛╨┤╤Б╨║╨░╤П ╨┐╨╛╨╗╨╕╨║╨╗╨╕╨╜╨╕╨║╨░ тДЦ1	╨Ф╨╡╤В╤Б╨║╨░╤П	╤Г╨╗. ╨и╨╡╨▓╤З╨╡╨╜╨║╨╛, 118, ╨Р╨╗╨╝╨░╤В╤Л	18	t	2026-05-19 22:42:36.754959+00	+7 (727) 291-51-22	╨Т╨╡╨┤╤Г╤Й╨░╤П ╨┤╨╡╤В╤Б╨║╨░╤П ╨┐╨╛╨╗╨╕╨║╨╗╨╕╨╜╨╕╨║╨░ ╨Р╨╗╨╝╨░╤В╤Л. ╨Я╤А╨╕╨╜╨╕╨╝╨░╨╡╤В ╨┤╨╡╤В╨╡╨╣ ╤Б ╤А╨╛╨╢╨┤╨╡╨╜╨╕╤П ╨┤╨╛ 18 ╨╗╨╡╤В. ╨а╨░╨▒╨╛╤В╨░╤О╤В ╨┐╨╡╨┤╨╕╨░╤В╤А╤Л, ╨┤╨╡╤В╤Б╨║╨╕╨╡ ╨╜╨╡╨▓╤А╨╛╨╗╨╛╨│╨╕, ╨║╨░╤А╨┤╨╕╨╛╨╗╨╛╨│╨╕, ╨╛╤А╤В╨╛╨┐╨╡╨┤╤Л. ╨д╤Г╨╜╨║╤Ж╨╕╨╛╨╜╨╕╤А╤Г╨╡╤В ╨║╨░╨▒╨╕╨╜╨╡╤В ╨╖╨┤╨╛╤А╨╛╨▓╨╛╨│╨╛ ╤А╨╡╨▒╤С╨╜╨║╨░.	43.256	76.93
10	╨Ф╨╡╤В╤Б╨║╨░╤П ╨│╨╛╤А╨╛╨┤╤Б╨║╨░╤П ╨┐╨╛╨╗╨╕╨║╨╗╨╕╨╜╨╕╨║╨░ тДЦ3	╨Ф╨╡╤В╤Б╨║╨░╤П	╤Г╨╗. ╨С╨░╨╣╨╖╨░╨║╨╛╨▓╨░, 280, ╨Р╨╗╨╝╨░╤В╤Л	20	t	2026-05-19 22:42:36.762097+00	+7 (727) 256-10-04	╨Ф╨╡╤В╤Б╨║╨░╤П ╨┐╨╛╨╗╨╕╨║╨╗╨╕╨╜╨╕╨║╨░ ╨▓ ╨С╨╛╤Б╤В╨░╨╜╨┤╤Л╨║╤Б╨║╨╛╨╝ ╤А╨░╨╣╨╛╨╜╨╡. ╨б╨┐╨╡╤Ж╨╕╨░╨╗╨╕╨╖╨╕╤А╤Г╨╡╤В╤Б╤П ╨╜╨░ ╤А╨░╨╜╨╜╨╡╨╣ ╨┤╨╕╨░╨│╨╜╨╛╤Б╤В╨╕╨║╨╡ ╤Г ╨╜╨╛╨▓╨╛╤А╨╛╨╢╨┤╤С╨╜╨╜╤Л╤Е. ╨Ю╨▒╨╛╤А╤Г╨┤╨╛╨▓╨░╨╜ ╨║╨░╨▒╨╕╨╜╨╡╤В ╨░╤Г╨┤╨╕╨╛╨╗╨╛╨│╨╕╨╕ ╨╕ ╨║╨░╨▒╨╕╨╜╨╡╤В ╨╝╨░╤Б╤Б╨░╨╢╨░.	43.249	76.902
11	╨Ф╨╡╤В╤Б╨║╨░╤П ╨│╨╛╤А╨╛╨┤╤Б╨║╨░╤П ╨┐╨╛╨╗╨╕╨║╨╗╨╕╨╜╨╕╨║╨░ тДЦ4	╨Ф╨╡╤В╤Б╨║╨░╤П	╨Ь╨╛╨╜╤В╨░╨╢╨╜╨░╤П ╤Г╨╗., 33, ╨Р╨╗╨╝╨░╤В╤Л	15	t	2026-05-19 22:42:36.767463+00	+7 (727) 264-41-11	╨Ю╨▒╤Б╨╗╤Г╨╢╨╕╨▓╨░╨╡╤В ╨┤╨╡╤В╤Б╨║╨╛╨╡ ╨╜╨░╤Б╨╡╨╗╨╡╨╜╨╕╨╡ ╨Р╨╗╨╝╨░╨╗╨╕╨╜╤Б╨║╨╛╨│╨╛ ╤А╨░╨╣╨╛╨╜╨░. ╨Т ╤Г╤З╤А╨╡╨╢╨┤╨╡╨╜╨╕╨╕ ╤А╨░╨▒╨╛╤В╨░╤О╤В ╨┤╨╡╤В╤Б╨║╨╕╨╣ ╨░╨╗╨╗╨╡╤А╨│╨╛╨╗╨╛╨│, ╨╗╨╛╨│╨╛╨┐╨╡╨┤, ╨┐╤Б╨╕╤Е╨╛╨╗╨╛╨│. ╨Х╤Б╤В╤М ╨┐╤А╨╕╨▓╨╕╨▓╨╛╤З╨╜╤Л╨╣ ╨║╨░╨▒╨╕╨╜╨╡╤В ╤Б ╨╖╨░╨┐╨░╤Б╨╛╨╝ ╨▓╤Б╨╡╤Е ╨┐╨╗╨░╨╜╨╛╨▓╤Л╤Е ╨▓╨░╨║╤Ж╨╕╨╜.	43.278	76.999
12	╨У╨╛╤А╨╛╨┤╤Б╨║╨░╤П ╨║╨╗╨╕╨╜╨╕╤З╨╡╤Б╨║╨░╤П ╨▒╨╛╨╗╤М╨╜╨╕╤Ж╨░ тДЦ4 (╨У╨Ъ╨С тДЦ4)	╨С╨╛╨╗╤М╨╜╨╕╤Ж╨░	╤Г╨╗. ╨Я╨░╨┐╨░╨╜╨╕╨╜╨░, 220, ╨Р╨╗╨╝╨░╤В╤Л	30	t	2026-05-19 22:42:36.769119+00	+7 (727) 385-54-54	╨Ь╨╜╨╛╨│╨╛╨┐╤А╨╛╤Д╨╕╨╗╤М╨╜╤Л╨╣ ╤Б╤В╨░╤Ж╨╕╨╛╨╜╨░╤А ╤Б ╨║╤А╤Г╨│╨╗╨╛╤Б╤Г╤В╨╛╤З╨╜╤Л╨╝ ╨┐╤А╨╕╤С╨╝╨╜╤Л╨╝ ╨┐╨╛╨║╨╛╨╡╨╝. ╨Ю╤В╨┤╨╡╨╗╨╡╨╜╨╕╤П: ╤Е╨╕╤А╤Г╤А╨│╨╕╤П, ╤В╨╡╤А╨░╨┐╨╕╤П, ╨║╨░╤А╨┤╨╕╨╛╨╗╨╛╨│╨╕╤П, ╨╜╨╡╨▓╤А╨╛╨╗╨╛╨│╨╕╤П, ╤Г╤А╨╛╨╗╨╛╨│╨╕╤П. ╨ж╨╡╨╜╤В╤А ╤Н╨║╤Б╤В╤А╨╡╨╜╨╜╨╛╨╣ ╨╝╨╡╨┤╨╕╤Ж╨╕╨╜╤Б╨║╨╛╨╣ ╨┐╨╛╨╝╨╛╤Й╨╕ ╨б╨╡╨▓╨╡╤А╨╜╨╛╨│╨╛ ╨Р╨╗╨╝╨░╤В╤Л. ╨Ш╨╝╨╡╨╡╤В ╤А╨╡╨░╨╜╨╕╨╝╨░╤Ж╨╕╤О ╨╕ ╨╛╨┐╨╡╤А╨░╤Ж╨╕╨╛╨╜╨╜╤Л╨╣ ╨▒╨╗╨╛╨║.	43.319	76.963
13	╨ж╨╡╨╜╤В╤А╨░╨╗╤М╨╜╨░╤П ╨│╨╛╤А╨╛╨┤╤Б╨║╨░╤П ╨║╨╗╨╕╨╜╨╕╤З╨╡╤Б╨║╨░╤П ╨▒╨╛╨╗╤М╨╜╨╕╤Ж╨░ (╨ж╨У╨Ъ╨С)	╨С╨╛╨╗╤М╨╜╨╕╤Ж╨░	╤Г╨╗. ╨Ю╤А╨░╨╖╨░ ╨Ц╨░╨╜╨┤╨╛╤Б╨╛╨▓╨░, 6, ╨Р╨╗╨╝╨░╤В╤Л	40	t	2026-05-19 22:42:36.777882+00	+7 (727) 309-50-00	╨д╨╗╨░╨│╨╝╨░╨╜╤Б╨║╨╕╨╣ ╤Б╤В╨░╤Ж╨╕╨╛╨╜╨░╤А ╤Б╨╕╤Б╤В╨╡╨╝╤Л ╨╖╨┤╤А╨░╨▓╨╛╨╛╤Е╤А╨░╨╜╨╡╨╜╨╕╤П ╨Р╨╗╨╝╨░╤В╤Л. 28 ╨╛╤В╨┤╨╡╨╗╨╡╨╜╨╕╨╣, ╨▒╨╛╨╗╨╡╨╡ 800 ╨║╨╛╨╡╨║. ╨Ъ╨░╤А╨┤╨╕╨╛╤Е╨╕╤А╤Г╤А╨│╨╕╤П, ╨╜╨╡╨╣╤А╨╛╤Е╨╕╤А╤Г╤А╨│╨╕╤П, ╨╛╨╜╨║╨╛╨╗╨╛╨│╨╕╤П, ╤В╤А╨░╨╜╤Б╨┐╨╗╨░╨╜╤В╨╛╨╗╨╛╨│╨╕╤П. ╨Ь╨а╨в, ╨Ъ╨в, ╤А╨╛╨▒╨╛╤В╨╕╤З╨╡╤Б╨║╨░╤П ╤Е╨╕╤А╤Г╤А╨│╨╕╤П.	43.204	76.878
14	╨У╨╛╤А╨╛╨┤╤Б╨║╨░╤П ╨║╨╗╨╕╨╜╨╕╤З╨╡╤Б╨║╨░╤П ╨▒╨╛╨╗╤М╨╜╨╕╤Ж╨░ тДЦ7 (╨У╨Ъ╨С тДЦ7)	╨С╨╛╨╗╤М╨╜╨╕╤Ж╨░	╨╝╨║╤А. ╨Ъ╨░╨╗╨║╨░╨╝╨░╨╜, 20, ╨Р╨╗╨╝╨░╤В╤Л	35	t	2026-05-19 22:42:36.785473+00	+7 (727) 309-60-00	╨Ь╨╜╨╛╨│╨╛╨┐╤А╨╛╤Д╨╕╨╗╤М╨╜╤Л╨╣ ╤Б╤В╨░╤Ж╨╕╨╛╨╜╨░╤А ╨╜╨░ ╤О╨│╨╛-╨╖╨░╨┐╨░╨┤╨╡ ╨│╨╛╤А╨╛╨┤╨░. ╨б╨┐╨╡╤Ж╨╕╨░╨╗╨╕╨╖╨╕╤А╤Г╨╡╤В╤Б╤П ╨╜╨░ ╤Е╨╕╤А╤Г╤А╨│╨╕╨╕, ╤В╤А╨░╨▓╨╝╨░╤В╨╛╨╗╨╛╨│╨╕╨╕ ╨╕ ╨╛╤А╤В╨╛╨┐╨╡╨┤╨╕╨╕. ╨ж╨╡╨╜╤В╤А ╨│╨╡╨╝╨╛╨┤╨╕╨░╨╗╨╕╨╖╨░, ╨╛╤В╨┤╨╡╨╗╨╡╨╜╨╕╨╡ ╤А╨╡╨░╨▒╨╕╨╗╨╕╤В╨░╤Ж╨╕╨╕. 600+ ╨║╨╛╨╡╨║, 18 ╨╛╨┐╨╡╤А╨░╤Ж╨╕╨╛╨╜╨╜╤Л╤Е ╨╖╨░╨╗╨╛╨▓.	43.232	76.8
15	╨С╨╛╨╗╤М╨╜╨╕╤Ж╨░ ╤Б╨║╨╛╤А╨╛╨╣ ╨╝╨╡╨┤╨╕╤Ж╨╕╨╜╤Б╨║╨╛╨╣ ╨┐╨╛╨╝╨╛╤Й╨╕ (╨С╨б╨Ь╨Я)	╨С╨╛╨╗╤М╨╜╨╕╤Ж╨░	╤Г╨╗. ╨Ъ╨░╨╖╤Л╨▒╨╡╨║ ╨▒╨╕, 96, ╨Р╨╗╨╝╨░╤В╤Л	20	t	2026-05-19 22:42:36.791955+00	+7 (727) 278-36-33	╨У╨╗╨░╨▓╨╜╨░╤П ╤Н╨║╤Б╤В╤А╨╡╨╜╨╜╨░╤П ╨▒╨╛╨╗╤М╨╜╨╕╤Ж╨░ ╨│╨╛╤А╨╛╨┤╨░. ╨Я╤А╨╕╨╜╨╕╨╝╨░╨╡╤В ╨┐╨░╤Ж╨╕╨╡╨╜╤В╨╛╨▓ ╤Б ╨╛╤Б╤В╤А╤Л╨╝╨╕ ╤Б╨╛╤Б╤В╨╛╤П╨╜╨╕╤П╨╝╨╕ 24/7. ╨е╨╕╤А╤Г╤А╨│╨╕╤П, ╨╜╨╡╨╣╤А╨╛╤Е╨╕╤А╤Г╤А╨│╨╕╤П, ╤А╨╡╨░╨╜╨╕╨╝╨░╤В╨╛╨╗╨╛╨│╨╕╤П, ╨╛╨╢╨╛╨│╨╛╨▓╨╛╨╡ ╨╛╤В╨┤╨╡╨╗╨╡╨╜╨╕╨╡. ╨Т╨╡╤А╤В╨╛╨╗╤С╤В╨╜╨░╤П ╨┐╨╗╨╛╤Й╨░╨┤╨║╨░ ╨┤╨╗╤П ╤Б╨░╨╜╨░╨▓╨╕╨░╤Ж╨╕╨╕.	43.255	76.929
16	╨Ш╨╜╤Б╤В╨╕╤В╤Г╤В ╤А╨░╨┤╨╕╨░╤Ж╨╕╨╛╨╜╨╜╨╛╨╣ ╨╝╨╡╨┤╨╕╤Ж╨╕╨╜╤Л ╨╕ ╤Н╨║╨╛╨╗╨╛╨│╨╕╨╕ (╨Ш╨а╨Ь)	╨б╨┐╨╡╤Ж. ╨║╨╗╨╕╨╜╨╕╨║╨░	╤Г╨╗. ╨а╨╡╨╝╨╕╨╖╨╛╨▓╨║╨░, 4╨Р, ╨Р╨╗╨╝╨░╤В╤Л	50	t	2026-05-19 22:42:36.793364+00	+7 (727) 277-10-62	╨Т╨╡╨┤╤Г╤Й╨╕╨╣ ╨╜╨░╤Г╤З╨╜╨╛-╨║╨╗╨╕╨╜╨╕╤З╨╡╤Б╨║╨╕╨╣ ╤Ж╨╡╨╜╤В╤А ╨┐╨╛ ╤А╨░╨┤╨╕╨░╤Ж╨╕╨╛╨╜╨╜╨╛╨╣ ╨╝╨╡╨┤╨╕╤Ж╨╕╨╜╨╡ ╨▓ ╨ж╨╡╨╜╤В╤А╨░╨╗╤М╨╜╨╛╨╣ ╨Р╨╖╨╕╨╕. ╨Ю╨╜╨║╨╛╨╗╨╛╨│╨╕╤П, ╨│╨╡╨╝╨░╤В╨╛╨╗╨╛╨│╨╕╤П, ╨╗╤Г╤З╨╡╨▓╨░╤П ╨┤╨╕╨░╨│╨╜╨╛╤Б╤В╨╕╨║╨░. ╨Я╨н╨в-╤В╨╛╨╝╨╛╨│╤А╨░╤Д, ╨╗╨╕╨╜╨╡╨╣╨╜╤Л╨╡ ╤Г╤Б╨║╨╛╤А╨╕╤В╨╡╨╗╨╕. ╨Я╤А╨╕╨╜╨╕╨╝╨░╨╡╤В ╨┐╨░╤Ж╨╕╨╡╨╜╤В╨╛╨▓ ╤Б╨╛ ╨▓╤Б╨╡╨│╨╛ ╨Ъ╨░╨╖╨░╤Е╤Б╤В╨░╨╜╨░ ╨┐╨╛ ╨╜╨░╨┐╤А╨░╨▓╨╗╨╡╨╜╨╕╤О.	43.247	76.898
17	╨а╨╡╤Б╨┐╤Г╨▒╨╗╨╕╨║╨░╨╜╤Б╨║╨╕╨╣ ╨┤╨╕╨░╨│╨╜╨╛╤Б╤В╨╕╤З╨╡╤Б╨║╨╕╨╣ ╤Ж╨╡╨╜╤В╤А (╨а╨Ф╨ж)	╨б╨┐╨╡╤Ж. ╨║╨╗╨╕╨╜╨╕╨║╨░	╤Г╨╗. ╨Р╨╣╤В╨╡╨║╨╡ ╨▒╨╕, 66, ╨Р╨╗╨╝╨░╤В╤Л	25	t	2026-05-19 22:42:36.79535+00	+7 (727) 250-96-47	╨Ъ╤А╤Г╨┐╨╜╨╡╨╣╤И╨╕╨╣ ╨┤╨╕╨░╨│╨╜╨╛╤Б╤В╨╕╤З╨╡╤Б╨║╨╕╨╣ ╤Ж╨╡╨╜╤В╤А ╤Б╤В╤А╨░╨╜╤Л. ╨Ь╨а╨в, ╨Ъ╨в, ╨Я╨н╨в, ╨░╨╜╨│╨╕╨╛╨│╤А╨░╤Д╨╕╤П, ╨╗╨░╨▒╨╛╤А╨░╤В╨╛╤А╨╜╤Л╨╡ ╨╕╤Б╤Б╨╗╨╡╨┤╨╛╨▓╨░╨╜╨╕╤П. ╨Ъ╨╛╨╜╤Б╤Г╨╗╤М╤В╨╕╤А╤Г╤О╤В ╨┐╤А╨╛╤Д╨╡╤Б╤Б╨╛╤А╨░ ╨╕ ╨┤╨╛╨║╤В╨╛╤А╨░ ╨╜╨░╤Г╨║ ╨┐╨╛ 30+ ╤Б╨┐╨╡╤Ж╨╕╨░╨╗╤М╨╜╨╛╤Б╤В╤П╨╝.	43.249	76.921
18	╨У╨╛╤А╨╛╨┤╤Б╨║╨╛╨╣ ╨║╨░╤А╨┤╨╕╨╛╨╗╨╛╨│╨╕╤З╨╡╤Б╨║╨╕╨╣ ╤Ж╨╡╨╜╤В╤А	╨б╨┐╨╡╤Ж. ╨║╨╗╨╕╨╜╨╕╨║╨░	╤Г╨╗. ╨Ц╨░╨╜╨┤╨╛╤Б╨╛╨▓╨░, 14, ╨Р╨╗╨╝╨░╤В╤Л	30	t	2026-05-19 22:42:36.800244+00	+7 (727) 309-57-00	╨б╨┐╨╡╤Ж╨╕╨░╨╗╨╕╨╖╨╕╤А╨╛╨▓╨░╨╜╨╜╤Л╨╣ ╤Ж╨╡╨╜╤В╤А ╨║╨░╤А╨┤╨╕╨╛╨╗╨╛╨│╨╕╨╕ ╨╕ ╨║╨░╤А╨┤╨╕╨╛╤Е╨╕╤А╤Г╤А╨│╨╕╨╕. ╨Ъ╨░╤В╨╡╤В╨╡╤А╨╕╨╖╨░╤Ж╨╕╨╛╨╜╨╜╤Л╨╡ ╨╗╨░╨▒╨╛╤А╨░╤В╨╛╤А╨╕╨╕, ╨░╨╛╤А╤В╨╛-╨║╨╛╤А╨╛╨╜╨░╤А╨╜╨╛╨╡ ╤И╤Г╨╜╤В╨╕╤А╨╛╨▓╨░╨╜╨╕╨╡, ╨╕╨╝╨┐╨╗╨░╨╜╤В╨░╤Ж╨╕╤П ╨║╨░╤А╨┤╨╕╨╛╤Б╤В╨╕╨╝╤Г╨╗╤П╤В╨╛╤А╨╛╨▓. ╨Ъ╤А╤Г╨│╨╗╨╛╤Б╤Г╤В╨╛╤З╨╜╨╛╨╡ ╨╛╤В╨┤╨╡╨╗╨╡╨╜╨╕╨╡ ╨Ю╨Ъ╨б.	43.213	76.889
19	╨У╨╛╤А╨╛╨┤╤Б╨║╨╛╨╣ ╨╛╨╜╨║╨╛╨╗╨╛╨│╨╕╤З╨╡╤Б╨║╨╕╨╣ ╤Ж╨╡╨╜╤В╤А	╨б╨┐╨╡╤Ж. ╨║╨╗╨╕╨╜╨╕╨║╨░	╤Г╨╗. ╨С╨░╨╗╤Е╨░╤И╤Б╨║╨░╤П, 4, ╨Р╨╗╨╝╨░╤В╤Л	45	t	2026-05-19 22:42:36.806011+00	+7 (727) 292-64-44	╨Ю╤Б╨╜╨╛╨▓╨╜╨╛╨╣ ╨╛╨╜╨║╨╛╨╗╨╛╨│╨╕╤З╨╡╤Б╨║╨╕╨╣ ╤Б╤В╨░╤Ж╨╕╨╛╨╜╨░╤А ╨│╨╛╤А╨╛╨┤╨░ ╤Б ╨┐╨╛╨╗╨╕╨║╨╗╨╕╨╜╨╕╤З╨╡╤Б╨║╨╕╨╝ ╨┐╤А╨╕╤С╨╝╨╛╨╝. ╨е╨╕╤А╤Г╤А╨│╨╕╤П, ╤Е╨╕╨╝╨╕╨╛╤В╨╡╤А╨░╨┐╨╕╤П, ╨╗╤Г╤З╨╡╨▓╨░╤П ╤В╨╡╤А╨░╨┐╨╕╤П. ╨а╨░╨▒╨╛╤В╨░╨╡╤В ╨╛╨╜╨║╨╛╨┐╤Б╨╕╤Е╨╛╨╗╨╛╨│, ╨┐╨░╨╗╨╗╨╕╨░╤В╨╕╨▓╨╜╨░╤П ╨┐╨╛╨╝╨╛╤Й╤М.	43.258	76.95
20	╨б╤В╨╛╨╝╨░╤В╨╛╨╗╨╛╨│╨╕╤З╨╡╤Б╨║╨░╤П ╨┐╨╛╨╗╨╕╨║╨╗╨╕╨╜╨╕╨║╨░ тДЦ1	╨б╨┐╨╡╤Ж. ╨║╨╗╨╕╨╜╨╕╨║╨░	╤Г╨╗. ╨д╤Г╤А╨╝╨░╨╜╨╛╨▓╨░, 233, ╨Р╨╗╨╝╨░╤В╤Л	20	t	2026-05-19 22:42:36.807835+00	+7 (727) 291-11-32	╨У╨╗╨░╨▓╨╜╨░╤П ╨│╨╛╤Б╤Г╨┤╨░╤А╤Б╤В╨▓╨╡╨╜╨╜╨░╤П ╤Б╤В╨╛╨╝╨░╤В╨╛╨╗╨╛╨│╨╕╤З╨╡╤Б╨║╨░╤П ╨┐╨╛╨╗╨╕╨║╨╗╨╕╨╜╨╕╨║╨░. ╨Т╨╖╤А╨╛╤Б╨╗╤Л╨╣ ╨╕ ╨┤╨╡╤В╤Б╨║╨╕╨╣ ╨┐╤А╨╕╤С╨╝. ╨в╨╡╤А╨░╨┐╨╕╤П, ╨╛╤А╤В╨╛╨┐╨╡╨┤╨╕╤П, ╤Е╨╕╤А╤Г╤А╨│╨╕╤П, ╨╛╤А╤В╨╛╨┤╨╛╨╜╤В╨╕╤П. ╨а╨╡╨╜╤В╨│╨╡╨╜-╨┤╨╕╨░╨│╨╜╨╛╤Б╤В╨╕╨║╨░. ╨Ы╤М╨│╨╛╤В╤Л ╨┤╨╗╤П ╨┐╨╡╨╜╤Б╨╕╨╛╨╜╨╡╤А╨╛╨▓ ╨╕ ╨╝╨╜╨╛╨│╨╛╨┤╨╡╤В╨╜╤Л╤Е ╤Б╨╡╨╝╨╡╨╣.	43.249	76.921
\.


--
-- Data for Name: appointments_passwordresetcode; Type: TABLE DATA; Schema: public; Owner: medqueue
--

COPY public.appointments_passwordresetcode (id, email, code, created_at) FROM stdin;
\.


--
-- Data for Name: appointments_paymentcard; Type: TABLE DATA; Schema: public; Owner: medqueue
--

COPY public.appointments_paymentcard (id, card_holder, brand, last4, exp_month, exp_year, token, created_at, updated_at, user_id, is_verified) FROM stdin;
\.


--
-- Data for Name: appointments_paymenttransaction; Type: TABLE DATA; Schema: public; Owner: medqueue
--

COPY public.appointments_paymenttransaction (id, amount, currency, status, transaction_ref, merchant_name, card_last4, card_brand, description, authorization_code, paid_at, created_at, subscription_id, user_id) FROM stdin;
\.


--
-- Data for Name: appointments_userprofile; Type: TABLE DATA; Schema: public; Owner: medqueue
--

COPY public.appointments_userprofile (id, role, phone, user_id) FROM stdin;
1	admin		1
2	doctor		2
3	doctor		3
4	doctor		4
\.


--
-- Data for Name: appointments_usersubscription; Type: TABLE DATA; Schema: public; Owner: medqueue
--

COPY public.appointments_usersubscription (id, plan, status, auto_taxi_enabled, started_at, next_billing_date, updated_at, user_id, social_reason, social_reason_confirmed_at) FROM stdin;
\.


--
-- Data for Name: appointments_verificationcode; Type: TABLE DATA; Schema: public; Owner: medqueue
--

COPY public.appointments_verificationcode (id, email, code, name, password, created_at, role, doctor_code, username) FROM stdin;
\.


--
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: medqueue
--

COPY public.auth_group (id, name) FROM stdin;
\.


--
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: medqueue
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
\.


--
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: medqueue
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add log entry	1	add_logentry
2	Can change log entry	1	change_logentry
3	Can delete log entry	1	delete_logentry
4	Can view log entry	1	view_logentry
5	Can add permission	2	add_permission
6	Can change permission	2	change_permission
7	Can delete permission	2	delete_permission
8	Can view permission	2	view_permission
9	Can add group	3	add_group
10	Can change group	3	change_group
11	Can delete group	3	delete_group
12	Can view group	3	view_group
13	Can add user	4	add_user
14	Can change user	4	change_user
15	Can delete user	4	delete_user
16	Can view user	4	view_user
17	Can add content type	5	add_contenttype
18	Can change content type	5	change_contenttype
19	Can delete content type	5	delete_contenttype
20	Can view content type	5	view_contenttype
21	Can add session	6	add_session
22	Can change session	6	change_session
23	Can delete session	6	delete_session
24	Can view session	6	view_session
25	Can add ╨С╨╛╨╗╤М╨╜╨╕╤Ж╨░	7	add_hospital
26	Can change ╨С╨╛╨╗╤М╨╜╨╕╤Ж╨░	7	change_hospital
27	Can delete ╨С╨╛╨╗╤М╨╜╨╕╤Ж╨░	7	delete_hospital
28	Can view ╨С╨╛╨╗╤М╨╜╨╕╤Ж╨░	7	view_hospital
29	Can add ╨Ч╨░╨┐╨╕╤Б╤М	8	add_appointment
30	Can change ╨Ч╨░╨┐╨╕╤Б╤М	8	change_appointment
31	Can delete ╨Ч╨░╨┐╨╕╤Б╤М	8	delete_appointment
32	Can view ╨Ч╨░╨┐╨╕╤Б╤М	8	view_appointment
33	Can add ╨Ъ╨╛╨┤ ╨▓╨╡╤А╨╕╤Д╨╕╨║╨░╤Ж╨╕╨╕	9	add_verificationcode
34	Can change ╨Ъ╨╛╨┤ ╨▓╨╡╤А╨╕╤Д╨╕╨║╨░╤Ж╨╕╨╕	9	change_verificationcode
35	Can delete ╨Ъ╨╛╨┤ ╨▓╨╡╤А╨╕╤Д╨╕╨║╨░╤Ж╨╕╨╕	9	delete_verificationcode
36	Can view ╨Ъ╨╛╨┤ ╨▓╨╡╤А╨╕╤Д╨╕╨║╨░╤Ж╨╕╨╕	9	view_verificationcode
37	Can add ╨Т╤А╨░╤З	10	add_doctor
38	Can change ╨Т╤А╨░╤З	10	change_doctor
39	Can delete ╨Т╤А╨░╤З	10	delete_doctor
40	Can view ╨Т╤А╨░╤З	10	view_doctor
41	Can add ╨Ъ╨╛╨┤ ╨┐╤А╨╕╨│╨╗╨░╤И╨╡╨╜╨╕╤П ╨▓╤А╨░╤З╨░	11	add_doctorinvitecode
42	Can change ╨Ъ╨╛╨┤ ╨┐╤А╨╕╨│╨╗╨░╤И╨╡╨╜╨╕╤П ╨▓╤А╨░╤З╨░	11	change_doctorinvitecode
43	Can delete ╨Ъ╨╛╨┤ ╨┐╤А╨╕╨│╨╗╨░╤И╨╡╨╜╨╕╤П ╨▓╤А╨░╤З╨░	11	delete_doctorinvitecode
44	Can view ╨Ъ╨╛╨┤ ╨┐╤А╨╕╨│╨╗╨░╤И╨╡╨╜╨╕╤П ╨▓╤А╨░╤З╨░	11	view_doctorinvitecode
45	Can add ╨Я╤А╨╛╤Д╨╕╨╗╤М ╨┐╨╛╨╗╤М╨╖╨╛╨▓╨░╤В╨╡╨╗╤П	12	add_userprofile
46	Can change ╨Я╤А╨╛╤Д╨╕╨╗╤М ╨┐╨╛╨╗╤М╨╖╨╛╨▓╨░╤В╨╡╨╗╤П	12	change_userprofile
47	Can delete ╨Я╤А╨╛╤Д╨╕╨╗╤М ╨┐╨╛╨╗╤М╨╖╨╛╨▓╨░╤В╨╡╨╗╤П	12	delete_userprofile
48	Can view ╨Я╤А╨╛╤Д╨╕╨╗╤М ╨┐╨╛╨╗╤М╨╖╨╛╨▓╨░╤В╨╡╨╗╤П	12	view_userprofile
49	Can add ╨Ъ╨╛╨┤ ╤Б╨▒╤А╨╛╤Б╨░ ╨┐╨░╤А╨╛╨╗╤П	13	add_passwordresetcode
50	Can change ╨Ъ╨╛╨┤ ╤Б╨▒╤А╨╛╤Б╨░ ╨┐╨░╤А╨╛╨╗╤П	13	change_passwordresetcode
51	Can delete ╨Ъ╨╛╨┤ ╤Б╨▒╤А╨╛╤Б╨░ ╨┐╨░╤А╨╛╨╗╤П	13	delete_passwordresetcode
52	Can view ╨Ъ╨╛╨┤ ╤Б╨▒╤А╨╛╤Б╨░ ╨┐╨░╤А╨╛╨╗╤П	13	view_passwordresetcode
53	Can add ╨Я╨╗╨░╤В╤С╨╢╨╜╨░╤П ╨║╨░╤А╤В╨░	14	add_paymentcard
54	Can change ╨Я╨╗╨░╤В╤С╨╢╨╜╨░╤П ╨║╨░╤А╤В╨░	14	change_paymentcard
55	Can delete ╨Я╨╗╨░╤В╤С╨╢╨╜╨░╤П ╨║╨░╤А╤В╨░	14	delete_paymentcard
56	Can view ╨Я╨╗╨░╤В╤С╨╢╨╜╨░╤П ╨║╨░╤А╤В╨░	14	view_paymentcard
57	Can add ╨Я╨╛╨┤╨┐╨╕╤Б╨║╨░	15	add_usersubscription
58	Can change ╨Я╨╛╨┤╨┐╨╕╤Б╨║╨░	15	change_usersubscription
59	Can delete ╨Я╨╛╨┤╨┐╨╕╤Б╨║╨░	15	delete_usersubscription
60	Can view ╨Я╨╛╨┤╨┐╨╕╤Б╨║╨░	15	view_usersubscription
61	Can add ╨Я╨╗╨░╤В╤С╨╢	16	add_paymenttransaction
62	Can change ╨Я╨╗╨░╤В╤С╨╢	16	change_paymenttransaction
63	Can delete ╨Я╨╗╨░╤В╤С╨╢	16	delete_paymenttransaction
64	Can view ╨Я╨╗╨░╤В╤С╨╢	16	view_paymenttransaction
65	Can add ╨Ъ╨╛╨┤ ╨┐╨╛╨┤╤В╨▓╨╡╤А╨╢╨┤╨╡╨╜╨╕╤П ╨║╨░╤А╤В╤Л	17	add_cardverificationcode
66	Can change ╨Ъ╨╛╨┤ ╨┐╨╛╨┤╤В╨▓╨╡╤А╨╢╨┤╨╡╨╜╨╕╤П ╨║╨░╤А╤В╤Л	17	change_cardverificationcode
67	Can delete ╨Ъ╨╛╨┤ ╨┐╨╛╨┤╤В╨▓╨╡╤А╨╢╨┤╨╡╨╜╨╕╤П ╨║╨░╤А╤В╤Л	17	delete_cardverificationcode
68	Can view ╨Ъ╨╛╨┤ ╨┐╨╛╨┤╤В╨▓╨╡╤А╨╢╨┤╨╡╨╜╨╕╤П ╨║╨░╤А╤В╤Л	17	view_cardverificationcode
69	Can add ╨Ю╤В╨╖╤Л╨▓ ╨╛ ╨▓╤А╨░╤З╨╡	18	add_doctorreview
70	Can change ╨Ю╤В╨╖╤Л╨▓ ╨╛ ╨▓╤А╨░╤З╨╡	18	change_doctorreview
71	Can delete ╨Ю╤В╨╖╤Л╨▓ ╨╛ ╨▓╤А╨░╤З╨╡	18	delete_doctorreview
72	Can view ╨Ю╤В╨╖╤Л╨▓ ╨╛ ╨▓╤А╨░╤З╨╡	18	view_doctorreview
\.


--
-- Data for Name: auth_user; Type: TABLE DATA; Schema: public; Owner: medqueue
--

COPY public.auth_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined) FROM stdin;
1	pbkdf2_sha256$720000$Pzpf9CHT26fvAfvxkTEPsq$eldDzlc8AAMSsWEac6AAHAvE1SKasqnRQXyiCBVJxZY=	2026-05-19 22:40:53.118779+00	t	admin			admin@example.com	t	t	2026-05-19 22:40:23.599058+00
2	pbkdf2_sha256$720000$2nvomiXvUWhA5PalM3uOYr$1qCO21HjSQGz3yZlIfE7DrihldKw3qSMMM9QkV9ezq8=	\N	f	doctor_asel	╨Р╤Б╨╡╨╗╤М ╨Э╤Г╤А╨╗╨░╨╜╨╛╨▓╨░		doctor_asel@medqueue.kz	f	t	2026-05-19 22:42:48.471992+00
3	pbkdf2_sha256$720000$88YswQByloBkXl508OnkX4$9t/kOlmoKgI3osaBRK6Tpe7v7V/D1eD7U9XEbESiJbM=	\N	f	doctor_arman	╨Р╤А╨╝╨░╨╜ ╨б╨╡╨╣╤В╨║╨░╨╗╨╕		doctor_arman@medqueue.kz	f	t	2026-05-19 22:42:48.610945+00
4	pbkdf2_sha256$720000$RaYbokT4hJP6EA4QKOlXoZ$MLGgdn6BOovMU+Yad6Xsfo0XD5n0DvcBaf0PMKz2CVM=	\N	f	doctor_zarina	╨Ч╨░╤А╨╕╨╜╨░ ╨С╨╡╨║╨╛╨▓╨░		doctor_zarina@medqueue.kz	f	t	2026-05-19 22:42:48.741734+00
\.


--
-- Data for Name: auth_user_groups; Type: TABLE DATA; Schema: public; Owner: medqueue
--

COPY public.auth_user_groups (id, user_id, group_id) FROM stdin;
\.


--
-- Data for Name: auth_user_user_permissions; Type: TABLE DATA; Schema: public; Owner: medqueue
--

COPY public.auth_user_user_permissions (id, user_id, permission_id) FROM stdin;
\.


--
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: medqueue
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
\.


--
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: medqueue
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1	admin	logentry
2	auth	permission
3	auth	group
4	auth	user
5	contenttypes	contenttype
6	sessions	session
7	appointments	hospital
8	appointments	appointment
9	appointments	verificationcode
10	appointments	doctor
11	appointments	doctorinvitecode
12	appointments	userprofile
13	appointments	passwordresetcode
14	appointments	paymentcard
15	appointments	usersubscription
16	appointments	paymenttransaction
17	appointments	cardverificationcode
18	appointments	doctorreview
\.


--
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: medqueue
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	contenttypes	0001_initial	2026-05-19 22:33:34.31105+00
2	auth	0001_initial	2026-05-19 22:33:34.390503+00
3	admin	0001_initial	2026-05-19 22:33:34.412901+00
4	admin	0002_logentry_remove_auto_add	2026-05-19 22:33:34.418301+00
5	admin	0003_logentry_add_action_flag_choices	2026-05-19 22:33:34.423946+00
6	appointments	0001_initial	2026-05-19 22:33:34.453729+00
7	appointments	0002_verificationcode_appointment_user	2026-05-19 22:33:34.473956+00
8	appointments	0003_alter_appointment_specialty_doctor_and_more	2026-05-19 22:33:34.505628+00
9	appointments	0004_hospital_description_latitude_longitude_phone	2026-05-19 22:33:34.521024+00
10	appointments	0005_doctordinvitecode_userprofile_verificationcode_role	2026-05-19 22:33:34.574596+00
11	appointments	0006_passwordresetcode	2026-05-19 22:33:34.581321+00
12	appointments	0007_add_username_to_verificationcode	2026-05-19 22:33:34.586416+00
13	appointments	0008_add_user_to_doctor	2026-05-19 22:33:34.601005+00
14	appointments	0009_add_comment_to_appointment	2026-05-19 22:33:34.615262+00
15	appointments	0010_subscription_and_recommendation	2026-05-19 22:33:34.696971+00
16	appointments	0011_card_verification_flow	2026-05-19 22:33:34.736171+00
17	appointments	0012_doctorreview	2026-05-19 22:33:34.763033+00
18	appointments	0013_appointment_exam_summary_and_more	2026-05-19 22:33:34.785716+00
19	appointments	0014_usersubscription_social_reason	2026-05-19 22:33:34.809992+00
20	appointments	0015_appointment_prescription_confirmation	2026-05-19 22:33:34.843633+00
21	contenttypes	0002_remove_content_type_name	2026-05-19 22:33:34.86366+00
22	auth	0002_alter_permission_name_max_length	2026-05-19 22:33:34.876726+00
23	auth	0003_alter_user_email_max_length	2026-05-19 22:33:34.888804+00
24	auth	0004_alter_user_username_opts	2026-05-19 22:33:34.899812+00
25	auth	0005_alter_user_last_login_null	2026-05-19 22:33:34.946203+00
26	auth	0006_require_contenttypes_0002	2026-05-19 22:33:34.94818+00
27	auth	0007_alter_validators_add_error_messages	2026-05-19 22:33:34.958982+00
28	auth	0008_alter_user_username_max_length	2026-05-19 22:33:34.975129+00
29	auth	0009_alter_user_last_name_max_length	2026-05-19 22:33:34.98606+00
30	auth	0010_alter_group_name_max_length	2026-05-19 22:33:35.001268+00
31	auth	0011_update_proxy_permissions	2026-05-19 22:33:35.01241+00
32	auth	0012_alter_user_first_name_max_length	2026-05-19 22:33:35.023968+00
33	sessions	0001_initial	2026-05-19 22:33:35.038508+00
\.


--
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: medqueue
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
b3r3k1kei8ypt7j2r68tdwuwonzbc7i7	.eJxVjEEOwiAUBe_C2pBPCwVcuvcM5AE_UjWQlHZlvLs26UK3b2beSwRsawlb5yXMWZyFEqffLSI9uO4g31FvTaZW12WOclfkQbu8tszPy-H-HRT08q01wWVPdtI8-GThyagxEhnjMXlnVSKXmcB6UGA7EmsATo82Za8SxPsDvRs3Yg:1wPT7N:vtKB3k4juThTcTnrw81cZDBwdn3Gf9AD3khK1r9lPBQ	2026-06-02 22:40:53.121058+00
\.


--
-- Name: appointments_appointment_id_seq; Type: SEQUENCE SET; Schema: public; Owner: medqueue
--

SELECT pg_catalog.setval('public.appointments_appointment_id_seq', 12, true);


--
-- Name: appointments_cardverificationcode_id_seq; Type: SEQUENCE SET; Schema: public; Owner: medqueue
--

SELECT pg_catalog.setval('public.appointments_cardverificationcode_id_seq', 1, false);


--
-- Name: appointments_doctor_id_seq; Type: SEQUENCE SET; Schema: public; Owner: medqueue
--

SELECT pg_catalog.setval('public.appointments_doctor_id_seq', 258, true);


--
-- Name: appointments_doctorinvitecode_id_seq; Type: SEQUENCE SET; Schema: public; Owner: medqueue
--

SELECT pg_catalog.setval('public.appointments_doctorinvitecode_id_seq', 1, false);


--
-- Name: appointments_doctorreview_id_seq; Type: SEQUENCE SET; Schema: public; Owner: medqueue
--

SELECT pg_catalog.setval('public.appointments_doctorreview_id_seq', 1, false);


--
-- Name: appointments_hospital_id_seq; Type: SEQUENCE SET; Schema: public; Owner: medqueue
--

SELECT pg_catalog.setval('public.appointments_hospital_id_seq', 20, true);


--
-- Name: appointments_passwordresetcode_id_seq; Type: SEQUENCE SET; Schema: public; Owner: medqueue
--

SELECT pg_catalog.setval('public.appointments_passwordresetcode_id_seq', 1, false);


--
-- Name: appointments_paymentcard_id_seq; Type: SEQUENCE SET; Schema: public; Owner: medqueue
--

SELECT pg_catalog.setval('public.appointments_paymentcard_id_seq', 1, false);


--
-- Name: appointments_paymenttransaction_id_seq; Type: SEQUENCE SET; Schema: public; Owner: medqueue
--

SELECT pg_catalog.setval('public.appointments_paymenttransaction_id_seq', 1, false);


--
-- Name: appointments_userprofile_id_seq; Type: SEQUENCE SET; Schema: public; Owner: medqueue
--

SELECT pg_catalog.setval('public.appointments_userprofile_id_seq', 4, true);


--
-- Name: appointments_usersubscription_id_seq; Type: SEQUENCE SET; Schema: public; Owner: medqueue
--

SELECT pg_catalog.setval('public.appointments_usersubscription_id_seq', 1, false);


--
-- Name: appointments_verificationcode_id_seq; Type: SEQUENCE SET; Schema: public; Owner: medqueue
--

SELECT pg_catalog.setval('public.appointments_verificationcode_id_seq', 1, false);


--
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: medqueue
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 1, false);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: medqueue
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: medqueue
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 72, true);


--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: medqueue
--

SELECT pg_catalog.setval('public.auth_user_groups_id_seq', 1, false);


--
-- Name: auth_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: medqueue
--

SELECT pg_catalog.setval('public.auth_user_id_seq', 4, true);


--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: medqueue
--

SELECT pg_catalog.setval('public.auth_user_user_permissions_id_seq', 1, false);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: medqueue
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 1, false);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: medqueue
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 18, true);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: medqueue
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 33, true);


--
-- Name: appointments_appointment appointments_appointment_code_key; Type: CONSTRAINT; Schema: public; Owner: medqueue
--

ALTER TABLE ONLY public.appointments_appointment
    ADD CONSTRAINT appointments_appointment_code_key UNIQUE (code);


--
-- Name: appointments_appointment appointments_appointment_pkey; Type: CONSTRAINT; Schema: public; Owner: medqueue
--

ALTER TABLE ONLY public.appointments_appointment
    ADD CONSTRAINT appointments_appointment_pkey PRIMARY KEY (id);


--
-- Name: appointments_cardverificationcode appointments_cardverificationcode_pkey; Type: CONSTRAINT; Schema: public; Owner: medqueue
--

ALTER TABLE ONLY public.appointments_cardverificationcode
    ADD CONSTRAINT appointments_cardverificationcode_pkey PRIMARY KEY (id);


--
-- Name: appointments_doctor appointments_doctor_pkey; Type: CONSTRAINT; Schema: public; Owner: medqueue
--

ALTER TABLE ONLY public.appointments_doctor
    ADD CONSTRAINT appointments_doctor_pkey PRIMARY KEY (id);


--
-- Name: appointments_doctor appointments_doctor_user_id_key; Type: CONSTRAINT; Schema: public; Owner: medqueue
--

ALTER TABLE ONLY public.appointments_doctor
    ADD CONSTRAINT appointments_doctor_user_id_key UNIQUE (user_id);


--
-- Name: appointments_doctorinvitecode appointments_doctorinvitecode_code_key; Type: CONSTRAINT; Schema: public; Owner: medqueue
--

ALTER TABLE ONLY public.appointments_doctorinvitecode
    ADD CONSTRAINT appointments_doctorinvitecode_code_key UNIQUE (code);


--
-- Name: appointments_doctorinvitecode appointments_doctorinvitecode_pkey; Type: CONSTRAINT; Schema: public; Owner: medqueue
--

ALTER TABLE ONLY public.appointments_doctorinvitecode
    ADD CONSTRAINT appointments_doctorinvitecode_pkey PRIMARY KEY (id);


--
-- Name: appointments_doctorinvitecode appointments_doctorinvitecode_used_by_id_key; Type: CONSTRAINT; Schema: public; Owner: medqueue
--

ALTER TABLE ONLY public.appointments_doctorinvitecode
    ADD CONSTRAINT appointments_doctorinvitecode_used_by_id_key UNIQUE (used_by_id);


--
-- Name: appointments_doctorreview appointments_doctorreview_pkey; Type: CONSTRAINT; Schema: public; Owner: medqueue
--

ALTER TABLE ONLY public.appointments_doctorreview
    ADD CONSTRAINT appointments_doctorreview_pkey PRIMARY KEY (id);


--
-- Name: appointments_hospital appointments_hospital_pkey; Type: CONSTRAINT; Schema: public; Owner: medqueue
--

ALTER TABLE ONLY public.appointments_hospital
    ADD CONSTRAINT appointments_hospital_pkey PRIMARY KEY (id);


--
-- Name: appointments_passwordresetcode appointments_passwordresetcode_pkey; Type: CONSTRAINT; Schema: public; Owner: medqueue
--

ALTER TABLE ONLY public.appointments_passwordresetcode
    ADD CONSTRAINT appointments_passwordresetcode_pkey PRIMARY KEY (id);


--
-- Name: appointments_paymentcard appointments_paymentcard_pkey; Type: CONSTRAINT; Schema: public; Owner: medqueue
--

ALTER TABLE ONLY public.appointments_paymentcard
    ADD CONSTRAINT appointments_paymentcard_pkey PRIMARY KEY (id);


--
-- Name: appointments_paymentcard appointments_paymentcard_user_id_key; Type: CONSTRAINT; Schema: public; Owner: medqueue
--

ALTER TABLE ONLY public.appointments_paymentcard
    ADD CONSTRAINT appointments_paymentcard_user_id_key UNIQUE (user_id);


--
-- Name: appointments_paymenttransaction appointments_paymenttransaction_pkey; Type: CONSTRAINT; Schema: public; Owner: medqueue
--

ALTER TABLE ONLY public.appointments_paymenttransaction
    ADD CONSTRAINT appointments_paymenttransaction_pkey PRIMARY KEY (id);


--
-- Name: appointments_paymenttransaction appointments_paymenttransaction_transaction_ref_key; Type: CONSTRAINT; Schema: public; Owner: medqueue
--

ALTER TABLE ONLY public.appointments_paymenttransaction
    ADD CONSTRAINT appointments_paymenttransaction_transaction_ref_key UNIQUE (transaction_ref);


--
-- Name: appointments_userprofile appointments_userprofile_pkey; Type: CONSTRAINT; Schema: public; Owner: medqueue
--

ALTER TABLE ONLY public.appointments_userprofile
    ADD CONSTRAINT appointments_userprofile_pkey PRIMARY KEY (id);


--
-- Name: appointments_userprofile appointments_userprofile_user_id_key; Type: CONSTRAINT; Schema: public; Owner: medqueue
--

ALTER TABLE ONLY public.appointments_userprofile
    ADD CONSTRAINT appointments_userprofile_user_id_key UNIQUE (user_id);


--
-- Name: appointments_usersubscription appointments_usersubscription_pkey; Type: CONSTRAINT; Schema: public; Owner: medqueue
--

ALTER TABLE ONLY public.appointments_usersubscription
    ADD CONSTRAINT appointments_usersubscription_pkey PRIMARY KEY (id);


--
-- Name: appointments_usersubscription appointments_usersubscription_user_id_key; Type: CONSTRAINT; Schema: public; Owner: medqueue
--

ALTER TABLE ONLY public.appointments_usersubscription
    ADD CONSTRAINT appointments_usersubscription_user_id_key UNIQUE (user_id);


--
-- Name: appointments_verificationcode appointments_verificationcode_pkey; Type: CONSTRAINT; Schema: public; Owner: medqueue
--

ALTER TABLE ONLY public.appointments_verificationcode
    ADD CONSTRAINT appointments_verificationcode_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: medqueue
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: medqueue
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: medqueue
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: medqueue
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: medqueue
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: medqueue
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: medqueue
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_user_id_group_id_94350c0c_uniq; Type: CONSTRAINT; Schema: public; Owner: medqueue
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_group_id_94350c0c_uniq UNIQUE (user_id, group_id);


--
-- Name: auth_user auth_user_pkey; Type: CONSTRAINT; Schema: public; Owner: medqueue
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: medqueue
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_permission_id_14a6b632_uniq; Type: CONSTRAINT; Schema: public; Owner: medqueue
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_permission_id_14a6b632_uniq UNIQUE (user_id, permission_id);


--
-- Name: auth_user auth_user_username_key; Type: CONSTRAINT; Schema: public; Owner: medqueue
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_username_key UNIQUE (username);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: medqueue
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: medqueue
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: medqueue
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: medqueue
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: medqueue
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: appointments_appointment_code_42526ee1_like; Type: INDEX; Schema: public; Owner: medqueue
--

CREATE INDEX appointments_appointment_code_42526ee1_like ON public.appointments_appointment USING btree (code varchar_pattern_ops);


--
-- Name: appointments_appointment_doctor_id_fb58c3a1; Type: INDEX; Schema: public; Owner: medqueue
--

CREATE INDEX appointments_appointment_doctor_id_fb58c3a1 ON public.appointments_appointment USING btree (doctor_id);


--
-- Name: appointments_appointment_hospital_id_b5912582; Type: INDEX; Schema: public; Owner: medqueue
--

CREATE INDEX appointments_appointment_hospital_id_b5912582 ON public.appointments_appointment USING btree (hospital_id);


--
-- Name: appointments_appointment_user_id_ae788a47; Type: INDEX; Schema: public; Owner: medqueue
--

CREATE INDEX appointments_appointment_user_id_ae788a47 ON public.appointments_appointment USING btree (user_id);


--
-- Name: appointments_cardverificationcode_card_id_7e62003a; Type: INDEX; Schema: public; Owner: medqueue
--

CREATE INDEX appointments_cardverificationcode_card_id_7e62003a ON public.appointments_cardverificationcode USING btree (card_id);


--
-- Name: appointments_cardverificationcode_user_id_07129849; Type: INDEX; Schema: public; Owner: medqueue
--

CREATE INDEX appointments_cardverificationcode_user_id_07129849 ON public.appointments_cardverificationcode USING btree (user_id);


--
-- Name: appointments_doctor_hospital_id_c349f3c8; Type: INDEX; Schema: public; Owner: medqueue
--

CREATE INDEX appointments_doctor_hospital_id_c349f3c8 ON public.appointments_doctor USING btree (hospital_id);


--
-- Name: appointments_doctorinvitecode_code_26c29864_like; Type: INDEX; Schema: public; Owner: medqueue
--

CREATE INDEX appointments_doctorinvitecode_code_26c29864_like ON public.appointments_doctorinvitecode USING btree (code varchar_pattern_ops);


--
-- Name: appointments_doctorinvitecode_hospital_id_3c6062bb; Type: INDEX; Schema: public; Owner: medqueue
--

CREATE INDEX appointments_doctorinvitecode_hospital_id_3c6062bb ON public.appointments_doctorinvitecode USING btree (hospital_id);


--
-- Name: appointments_doctorreview_doctor_id_a7b9b989; Type: INDEX; Schema: public; Owner: medqueue
--

CREATE INDEX appointments_doctorreview_doctor_id_a7b9b989 ON public.appointments_doctorreview USING btree (doctor_id);


--
-- Name: appointments_paymenttransaction_subscription_id_0c044137; Type: INDEX; Schema: public; Owner: medqueue
--

CREATE INDEX appointments_paymenttransaction_subscription_id_0c044137 ON public.appointments_paymenttransaction USING btree (subscription_id);


--
-- Name: appointments_paymenttransaction_transaction_ref_1acaa913_like; Type: INDEX; Schema: public; Owner: medqueue
--

CREATE INDEX appointments_paymenttransaction_transaction_ref_1acaa913_like ON public.appointments_paymenttransaction USING btree (transaction_ref varchar_pattern_ops);


--
-- Name: appointments_paymenttransaction_user_id_da3c2b3b; Type: INDEX; Schema: public; Owner: medqueue
--

CREATE INDEX appointments_paymenttransaction_user_id_da3c2b3b ON public.appointments_paymenttransaction USING btree (user_id);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: medqueue
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: medqueue
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: medqueue
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: medqueue
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: auth_user_groups_group_id_97559544; Type: INDEX; Schema: public; Owner: medqueue
--

CREATE INDEX auth_user_groups_group_id_97559544 ON public.auth_user_groups USING btree (group_id);


--
-- Name: auth_user_groups_user_id_6a12ed8b; Type: INDEX; Schema: public; Owner: medqueue
--

CREATE INDEX auth_user_groups_user_id_6a12ed8b ON public.auth_user_groups USING btree (user_id);


--
-- Name: auth_user_user_permissions_permission_id_1fbb5f2c; Type: INDEX; Schema: public; Owner: medqueue
--

CREATE INDEX auth_user_user_permissions_permission_id_1fbb5f2c ON public.auth_user_user_permissions USING btree (permission_id);


--
-- Name: auth_user_user_permissions_user_id_a95ead1b; Type: INDEX; Schema: public; Owner: medqueue
--

CREATE INDEX auth_user_user_permissions_user_id_a95ead1b ON public.auth_user_user_permissions USING btree (user_id);


--
-- Name: auth_user_username_6821ab7c_like; Type: INDEX; Schema: public; Owner: medqueue
--

CREATE INDEX auth_user_username_6821ab7c_like ON public.auth_user USING btree (username varchar_pattern_ops);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: medqueue
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: medqueue
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: medqueue
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: medqueue
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: appointments_appointment appointments_appoint_doctor_id_fb58c3a1_fk_appointme; Type: FK CONSTRAINT; Schema: public; Owner: medqueue
--

ALTER TABLE ONLY public.appointments_appointment
    ADD CONSTRAINT appointments_appoint_doctor_id_fb58c3a1_fk_appointme FOREIGN KEY (doctor_id) REFERENCES public.appointments_doctor(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: appointments_appointment appointments_appoint_hospital_id_b5912582_fk_appointme; Type: FK CONSTRAINT; Schema: public; Owner: medqueue
--

ALTER TABLE ONLY public.appointments_appointment
    ADD CONSTRAINT appointments_appoint_hospital_id_b5912582_fk_appointme FOREIGN KEY (hospital_id) REFERENCES public.appointments_hospital(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: appointments_appointment appointments_appointment_user_id_ae788a47_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: medqueue
--

ALTER TABLE ONLY public.appointments_appointment
    ADD CONSTRAINT appointments_appointment_user_id_ae788a47_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: appointments_cardverificationcode appointments_cardver_card_id_7e62003a_fk_appointme; Type: FK CONSTRAINT; Schema: public; Owner: medqueue
--

ALTER TABLE ONLY public.appointments_cardverificationcode
    ADD CONSTRAINT appointments_cardver_card_id_7e62003a_fk_appointme FOREIGN KEY (card_id) REFERENCES public.appointments_paymentcard(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: appointments_cardverificationcode appointments_cardver_user_id_07129849_fk_auth_user; Type: FK CONSTRAINT; Schema: public; Owner: medqueue
--

ALTER TABLE ONLY public.appointments_cardverificationcode
    ADD CONSTRAINT appointments_cardver_user_id_07129849_fk_auth_user FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: appointments_doctor appointments_doctor_hospital_id_c349f3c8_fk_appointme; Type: FK CONSTRAINT; Schema: public; Owner: medqueue
--

ALTER TABLE ONLY public.appointments_doctor
    ADD CONSTRAINT appointments_doctor_hospital_id_c349f3c8_fk_appointme FOREIGN KEY (hospital_id) REFERENCES public.appointments_hospital(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: appointments_doctor appointments_doctor_user_id_8531bc5a_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: medqueue
--

ALTER TABLE ONLY public.appointments_doctor
    ADD CONSTRAINT appointments_doctor_user_id_8531bc5a_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: appointments_doctorinvitecode appointments_doctori_hospital_id_3c6062bb_fk_appointme; Type: FK CONSTRAINT; Schema: public; Owner: medqueue
--

ALTER TABLE ONLY public.appointments_doctorinvitecode
    ADD CONSTRAINT appointments_doctori_hospital_id_3c6062bb_fk_appointme FOREIGN KEY (hospital_id) REFERENCES public.appointments_hospital(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: appointments_doctorinvitecode appointments_doctori_used_by_id_5d3d13ec_fk_auth_user; Type: FK CONSTRAINT; Schema: public; Owner: medqueue
--

ALTER TABLE ONLY public.appointments_doctorinvitecode
    ADD CONSTRAINT appointments_doctori_used_by_id_5d3d13ec_fk_auth_user FOREIGN KEY (used_by_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: appointments_doctorreview appointments_doctorr_doctor_id_a7b9b989_fk_appointme; Type: FK CONSTRAINT; Schema: public; Owner: medqueue
--

ALTER TABLE ONLY public.appointments_doctorreview
    ADD CONSTRAINT appointments_doctorr_doctor_id_a7b9b989_fk_appointme FOREIGN KEY (doctor_id) REFERENCES public.appointments_doctor(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: appointments_paymenttransaction appointments_payment_subscription_id_0c044137_fk_appointme; Type: FK CONSTRAINT; Schema: public; Owner: medqueue
--

ALTER TABLE ONLY public.appointments_paymenttransaction
    ADD CONSTRAINT appointments_payment_subscription_id_0c044137_fk_appointme FOREIGN KEY (subscription_id) REFERENCES public.appointments_usersubscription(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: appointments_paymenttransaction appointments_payment_user_id_da3c2b3b_fk_auth_user; Type: FK CONSTRAINT; Schema: public; Owner: medqueue
--

ALTER TABLE ONLY public.appointments_paymenttransaction
    ADD CONSTRAINT appointments_payment_user_id_da3c2b3b_fk_auth_user FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: appointments_paymentcard appointments_paymentcard_user_id_9621ae3c_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: medqueue
--

ALTER TABLE ONLY public.appointments_paymentcard
    ADD CONSTRAINT appointments_paymentcard_user_id_9621ae3c_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: appointments_userprofile appointments_userprofile_user_id_5a834edb_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: medqueue
--

ALTER TABLE ONLY public.appointments_userprofile
    ADD CONSTRAINT appointments_userprofile_user_id_5a834edb_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: appointments_usersubscription appointments_usersubscription_user_id_bca5cc2b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: medqueue
--

ALTER TABLE ONLY public.appointments_usersubscription
    ADD CONSTRAINT appointments_usersubscription_user_id_bca5cc2b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: medqueue
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: medqueue
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: medqueue
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_group_id_97559544_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: medqueue
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_group_id_97559544_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_user_id_6a12ed8b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: medqueue
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_6a12ed8b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: medqueue
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: medqueue
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: medqueue
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: medqueue
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

\unrestrict qhQffPNIfzYZc9sFhWzVfXzQGgT1LhYgoiEIUakQBAcV82stU9R4wIGxS2hnUL4

