# Generated by Django 5.0 on 2026-03-03 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0008_add_user_to_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='comment',
            field=models.TextField(blank=True, default='', verbose_name='Комментарий пациента'),
        ),
    ]
