# Generated by Django 5.0 on 2026-04-03 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0011_card_verification_flow'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=200, verbose_name='Имя пациента')),
                ('rating', models.PositiveSmallIntegerField(verbose_name='Рейтинг')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='appointments.doctor')),
            ],
            options={
                'verbose_name': 'Отзыв о враче',
                'verbose_name_plural': 'Отзывы о врачах',
                'ordering': ['-created_at'],
            },
        ),
    ]
