# Generated by Django 5.0 on 2026-06-05 12:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0016_verificationcode_phone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubscription',
            name='plan',
            field=models.CharField(choices=[('free', 'Базовая (0 тг)'), ('social', 'Льготная Care (0 тг/мес)'), ('plus', 'Care Plus (2 990 тг/мес)')], default='free', max_length=20, verbose_name='Тариф'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['user', 'status'], name='appt_user_status_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['user', 'created_at'], name='appt_user_created_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['doctor', 'status', 'datetime'], name='appt_doctor_status_dt_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['hospital', 'status', 'datetime'], name='appt_hospital_status_dt_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['code'], name='appt_code_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['status'], name='appt_status_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['created_at'], name='appt_created_at_idx'),
        ),
        migrations.AddIndex(
            model_name='doctor',
            index=models.Index(fields=['hospital', 'is_active'], name='doctor_hospital_active_idx'),
        ),
        migrations.AddIndex(
            model_name='doctor',
            index=models.Index(fields=['specialty', 'is_active'], name='doctor_specialty_active_idx'),
        ),
        migrations.AddIndex(
            model_name='doctor',
            index=models.Index(fields=['is_active'], name='doctor_is_active_idx'),
        ),
        migrations.AddIndex(
            model_name='doctorreview',
            index=models.Index(fields=['doctor', 'created_at'], name='review_doctor_created_idx'),
        ),
        migrations.AddIndex(
            model_name='doctorreview',
            index=models.Index(fields=['doctor'], name='review_doctor_idx'),
        ),
        migrations.AddIndex(
            model_name='hospital',
            index=models.Index(fields=['is_active'], name='hospital_is_active_idx'),
        ),
        migrations.AddIndex(
            model_name='hospital',
            index=models.Index(fields=['is_active', 'name'], name='hospital_active_name_idx'),
        ),
        migrations.AddIndex(
            model_name='passwordresetcode',
            index=models.Index(fields=['email', 'created_at'], name='resetcode_email_created_idx'),
        ),
        migrations.AddIndex(
            model_name='passwordresetcode',
            index=models.Index(fields=['email'], name='resetcode_email_idx'),
        ),
        migrations.AddIndex(
            model_name='verificationcode',
            index=models.Index(fields=['email', 'created_at'], name='vercode_email_created_idx'),
        ),
        migrations.AddIndex(
            model_name='verificationcode',
            index=models.Index(fields=['email'], name='vercode_email_idx'),
        ),
    ]
