# Generated by Django 6.0.6 on 2026-06-15 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0017_add_db_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar_base64',
            field=models.TextField(blank=True, help_text='Base64 encoded avatar image', null=True),
        ),
    ]
