# Generated by Django 6.0.6 on 2026-06-17 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0018_userprofile_avatar_base64'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttransaction',
            name='status',
            field=models.CharField(choices=[('processing', 'Обрабатывается'), ('paid', 'Оплачен'), ('failed', 'Ошибка'), ('refunded', 'Возврат')], default='processing', max_length=20, verbose_name='Статус'),
        ),
    ]
